### ISSUE TITLE
Translation Synchronization Locks Options

### ISSUE THREAD

**Issue by ImOnMars** [GM-Alex/user-access-manager#101]
I have custom taxonomies synchronization for Polylang disabled and still this seems to synchronize, which isn't a huge issue as that is what I want, but for some reason when I set an access group on the default language version of the product, it locks the option on both translations so it's impossible to change back.

**Comment by ImOnMars** [comment]
Attached is a screenshot for example. Notice that the checkboxes are checked and disabled.

![Image](https://user-images.githubusercontent.com/15960236/27694522-52bae1a2-5cba-11e7-889f-ba2713332c24.png)

**Comment by GM-Alex** [comment]
I wasn't able to reproduce the issue. Is it still there with the latest version?

**Comment by GM-Alex** [comment]
I will close this for now, until you have new information.
