### ISSUE TITLE
Plugin working but conflict with Revolution Slider

### ISSUE THREAD

**Issue by zcwebdesign** [GM-Alex/user-access-manager#104]
Plugin is working to restrict pages. Revolution Slider works fine if you're logged in. However having problems with Revolution Slider if you are NOT logged in. Front page shows a missing image and white screen. then it eventually pops in. It then disappears rather than cyling through. Basically it is doing some buggy stuff with Revolution slider. Can you please help me out or tell me if this is a known issue ASAP cause site is about to go live. Thanks.

**Comment by GM-Alex** [comment]
Should be fixed with the extended file handling logic at 2.1.7. If it's released choose `Wordpress` at `UAM > Settings > File settings > Locked directory type`.
