### ISSUE TITLE
“Block file access” feature

### ISSUE THREAD

**Issue by logemi** [GM-Alex/user-access-manager#106]
**Me:** The blocking of files with possible access for their owner does not work: the files are blocked and their owners can not access them either. The user redirection function does not work either.

**Comment by logemi** [comment]
**GM-Alex:** File locking is a quiet complex topic and depends strongly on your setup. Could you test the solution here https://github.com/GM-Alex/user-access-manager/issues/103 and give feedback if that solves your issue?

**Comment by logemi** [comment]
**Me:** I opened the .htaccess file and here is its contents:
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ – [L]
RewriteRule ^([^?]*)$ /index.php?uamfiletype=attachment&uamgetfile=$1 [QSA,L]
RewriteRule ^(.*)\?(((?!uamfiletype).)*)$ /index.php?uamfiletype=attachment&uamgetfile=$1&$2 [QSA,L]
RewriteRule ^(.*)\?(.*)$ /index.php?uamgetfile=$1&$2 [QSA,L]
</IfModule>
The .htaccess file is located in the Uploads directory.
The pdf files that users upload are automatically placed in subdirectories of Uploads directory. These pdf files should not be accessible by entering their URL directly into a web browser and should only be accessible by their owner.
What do you want to know and what do you want me to change?

**Comment by logemi** [comment]
**GM-Alex:** Seems I miss understood the files issue, and it seems it doesn’t depend on the .htaccess file, expect you have trouble with the restricted files in general. Where are the files uploaded, at the backend? Are the “Uploaded by” users the user which don’t have access after the upload? Is the option “Authors always has access to own posts/pages” set to “Yes”? Which version are you using? Before 2.0.12 there was an bug with the “Authors always has access to own posts/pages” option.

**Comment by logemi** [comment]
**Me:** As stated in my previous message, the files are placed in a subdirectory of wp-content/uploads. For example: wp-content/uploads/archieve/clients/name1/account/file1.pdf.
Users who have sent files no longer have access to them if I enable the “Block file access” feature of UAM.
The option “Authors always has access to own posts/pages” is set to “Yes”.
I’m using 2.0.12 version.

**Comment by logemi** [comment]
**GM-Alex:** So files are directly uploaded, for example via FTP? If so UAM will never be able to handle the access for such files. The only possible way with UAM is to use the WordPress backend for uploads and assign the uploads a user group to handle the access. To archive such a solution you need to map the FTP user groups to the file system users and need enough FTP users. This is way to complex for a “normal” user and so I think that will never be part of UAM. Or did I got you totally wrong?

**Comment by logemi** [comment]
**Me:** The visitor registers with a registration form and appends a pdf file with a download field. It is a hook that allows to file the file in the right place. The files are not sent with an FTP client and in the WordPress dashboard, the files are assigned to an author.

**Comment by logemi** [comment]
**GM-Alex:** Is the file available at the media library? I tested it right now and it works without any issues. Seems your logic is a custom extension, right? I think you will understand that’s impossible for me to provide file locking support for a custom hook out of the box. The media must be existing as post type attachment at the WordPress database and be assigned the the author or group which should have access. Could you provide me your custom hook? Then I will see what I can do.

About the redirection, can you confirm that it works for not completely hidden content or do you still have discovered any issue with that?

**Comment by GM-Alex** [comment]
Cold you give me some more information (see my questions above)?

**Comment by masimies** [comment]
I'm starting now to understand this :-)
Tested several of file upload plugins, and they take care only of "own"-files only. Yes, UAM cannot handle them without hook.
Here we come to there what i was trying to ask before. If UAM could read the file list in subfolder, like in this case "wp-content/uploads/archieve/clients/name1/account/", and take access control by that?
As we can see here in screenshot WFU can read the folder with uploader information. There you got the username for access control?
![filecontrol](https://user-images.githubusercontent.com/17984661/27779691-5db7f69c-5fcd-11e7-86f2-7695885f8485.JPG)
I'm still hoping that we could get the first extension what can do this for WP file protection, no matter what 3rd party extensions are in use  ;-)

**Comment by GM-Alex** [comment]
The files must be listed at the media gallery of Wordpress and be the post type attachment, otherwise it will not work. The only way to get third party plugins to work with UAM is to integrate UAM in the plugins.

@logemi Are the file listed at the media gallery and are the attachments?

**Comment by logemi** [comment]
![capture1](https://user-images.githubusercontent.com/29835951/27780896-d5485064-5fcb-11e7-9e98-13d8d6f9f418.JPG)

**Comment by logemi** [comment]
When I save the settings, here is the error that appears:
![capture2](https://user-images.githubusercontent.com/29835951/27780990-4142a3e6-5fcc-11e7-8742-cf2e15af77a4.JPG)

**Comment by logemi** [comment]
I had to make a Reset to make disappear this error

**Comment by logemi** [comment]
The settings:
![capture](https://user-images.githubusercontent.com/29835951/27781310-9b235fbc-5fcd-11e7-991c-1177b0ceca5a.JPG)

**Comment by GM-Alex** [comment]
The the settings issue appears because your server has a (probably low) upload size limit. See the following links to see how to solve that:

https://serverfault.com/questions/256838/apache-responding-with-request-entity-too-large
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
https://stackoverflow.com/questions/24306335/413-request-entity-too-large-file-upload-issue

The config screen is also redone in the upcoming version which should also prevent this issue, but you are the first one with it.

**Comment by logemi** [comment]
When the user tries to access its file:
![capture](https://user-images.githubusercontent.com/29835951/27781436-200c0e86-5fce-11e7-9d78-035523f993ae.JPG)

**Comment by logemi** [comment]
Redirection setting:
![capture](https://user-images.githubusercontent.com/29835951/27781525-7fde1156-5fce-11e7-8347-577b3ebaeda7.JPG)

**Comment by logemi** [comment]
In your ".htaccess" file you refer to an "index.php" file: where should it be located?

**Comment by GM-Alex** [comment]
At the wordpress root dir.

**Comment by logemi** [comment]
**it's OK. Do you think its content is correct?**
<?php
/**
 * Front to the WordPress application. This file doesn't do anything, but loads
 * wp-blog-header.php which does and tells WordPress to load the theme.
 *
 * @package WordPress
 */

/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define('WP_USE_THEMES', true);

/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wp-blog-header.php' );

**Comment by logemi** [comment]
**For your information, here is the kind of text that is in your fields "Articles title", "Articles comment text", etc ...**
Aucune autorisation d\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'accès !

**Comment by logemi** [comment]
Désolé vous n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'avez pas l\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'autorisation de voir les commentaires !

**Comment by logemi** [comment]
The number of back-slashes increases each time I save the settings.

**Comment by logemi** [comment]
Here are some of the problems I have faced. How can I not ask whether other underlying problems exist? That's why I say that the plugin is unstable because I do not know what it can cause in the short term! On the other hand, my goal is to be constructive and as I have already indicated, I have respect for the work of the developers. So I agreed to take the time to give you all the information I have, hoping that this will help you to improve your plugin. UAM seems to want to do things that no other plugin has yet managed to do; So I think we have to be indulgent. I corrected my review for the week ... I hope you will achieve a positive result.

**Comment by logemi** [comment]
I set up a test website with minimal plugins. It allows to reproduce the problems I encounter. If you give me your email, I will send you an administrator ID and you will be able to do your tests there.

**Comment by GM-Alex** [comment]
My mail is alexanderschneider85@gmail.com. Could you also grant me FTP access that I'm able to debug?

**Comment by GM-Alex** [comment]
Should resolved by version 2.1.3.
