### ISSUE TITLE
UAM experience - likely bug

### ISSUE THREAD

**Issue by jdla** [GM-Alex/user-access-manager#107]
Dear,

I got a hard time protecting my /wp-content/uploads with your plugin. 

I believe it should be better documented.
I now understand it is relying on apache rewrite rules, redirecting to your plugin.
The rewrite rule being written in .htaccess.
Therefore a user should be made more aware :
- `a2enmod rewrite` is needed on apache to enable the rewrite module. 
- The conf file for the site must be adapted to allow for rewrite rules in .htaccess : 
```

<Directory /var/www/html> 
    Options Indexes FollowSymLinks MultiViews 
    AllowOverride All 
    Require all granted 
</Directory>

```
Maybe your plugin should try to check on all of this ?

And then there was likely a bug as well. I have my WP under `/var/www/html/nl/`.
The .htaccess rewrite rule contains `RewriteBase nl/` which results in `500` errors : RewriteBase: argument is not a valid URL. The rule should be `RewriteBase /nl/`.

Thanks for the plugin !

**Comment by GM-Alex** [comment]
a2enmod currently is default so I think I will not add an extra check, the bug will be fixed with the next release.
