### ISSUE TITLE
Broken image bug

### ISSUE THREAD

**Issue by molinpierre** [GM-Alex/user-access-manager#108]
For registered users (excluding admin) I have a problem, so only for registered users, only on the private/restricted pages, images are broken, has like cutted off url, examples are attached.
<img width="806" alt="schermata 2017-07-06 alle 16 32 15" src="https://user-images.githubusercontent.com/29952220/27916434-58fe731c-6269-11e7-810e-7ea5ba5f475f.png">
![schermata 2017-07-06 alle 16 32 24](https://user-images.githubusercontent.com/29952220/27916435-59005506-6269-11e7-86e2-d117bd6ff446.png)
![schermata 2017-07-06 alle 16 32 35](https://user-images.githubusercontent.com/29952220/27916433-58fe448c-6269-11e7-94f4-43b07b5258ef.png)

**Comment by masimies** [comment]
Hi,
Lookup my comment in #103 as you are using membersite.
At least Ultimate Member is conflicting with main-site.
br,

-matti

**Comment by molinpierre** [comment]
Hello there, thanks for your respond. I don’t have any files called "um-filters-files.php”. What file I have to edit to solve this issue? thank u
--

Pierre Molin

Web Designer | Web Developer | Graphic Designer



C4B srl

Sede Legale: Viale Andrea Doria 5, 20124 Milano (MI)

Sede Operativa/Amministrativa: Via Enrico Reginato 85/H, Treviso (TV)

Tel: +39 0422263802 <applewebdata://BBFB4B22-82C9-46EA-8234-DE56FBDD00B1/+390422263802> Fax: +39 04221622160 <applewebdata://BBFB4B22-82C9-46EA-8234-DE56FBDD00B1/+3904221622160>
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


La presente comunicazione è ad esclusivo utilizzo del destinatario cui è indirizzata. Il presente messaggio contiene informazioni tutelate dal segreto professionale, di natura confidenziale o eventualmente protette dalle norme sul copyright in conformità alla normativa vigente. Qualora la presente comunicazione non fosse a Voi indirizzata, vogliate prendere nota che anche la parziale utilizzazione, riproduzione, duplicazione o divulgazione di quanto in essa contenuto sono severamente vietate. In tale caso siete pregati sin d'ora di voler contattare il mittente e di eliminare il presente messaggio di posta elettronica dal Vostro sistema. Il presente messaggio di posta elettronica non è da intendersi quale consenso all'utilizzo dei dati relativi al mittente per scopi commerciali o promozionali (direct marketing) o di trasferimento dei medesimi a terzi. Non stampare se non necessario!


This communication is for use by the intended recipient and contains information that may be privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail, in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties. Think before you print!


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by masimies** [comment]
If you have UM, that file is in plugins/ultimatemember/core-folder.
I assume that you have 3rd party plugin in use where those images are came from?
Anyway, those images are in subfolders, somewhere in your folder tree, and may be have special access attributes. They may be out of common WP media folder. That why UAM cannot handle them.
There could be many combination of configuration, so trying to solve this without seeing the environment is quite hard to complete.
With my case, solution was simple. Adding pre slashes to htaccess-file like RewriteBase /teamsin/
Even files in subfolders are protected and displayed to logged in users then. 
But this is changed to default with every changes in settings.

**Comment by GM-Alex** [comment]
Should be fixed with the extended file handling logic at 2.1.7. If it's released choose `Wordpress` at `UAM > Settings > File settings > Locked directory type`.
