### ISSUE TITLE
Selective Hiding of Articles

### ISSUE THREAD

**Issue by dlklement** [GM-Alex/user-access-manager#110]
Hello,

Is there way to use UAM to selectively hide content by either Role and/or Category?  

Situation: We setup a new site as a knowledge base accessible by our customers (previously it was just used internally at our company).  We are using S2Member and categorize our articles by level of access.  In general, I want all registered users of the site to see all of our content pop up on searches but, for some articles, only users granted the required level of access can actually open them.  If a user sees content on a search that they cannot access, they can ask us for the access.  It works that way now.

But...we also have stored some articles that are just for internal use only (e.g. company work instructions, etc.).  For those articles, I do NOT want those to show up on searches by anyone but individuals assigned to that Group.

However, it seems the "Hide Complete Articles" feature is global for searches.  Either everyone can see the information in searches (even though they don't have access) or no one can see it.  I want to be able to 'Hide Complete Articles' for just one group.

It is possible?

Dave.

**Comment by GM-Alex** [comment]
Currently the only way is to create a new post type for your internal posts, because it's possible to change the settings by post type. But I will keep that open as enhancement, but there is no estimate for that now.

**Comment by GM-Alex** [comment]
I thought a lot of this but doing this in the way like you want puts to much complexity to the plugin, using custom post types for internal articles is the way to go, in my opinion. So I will not implement that, sorry.
