### ISSUE TITLE
Non numeric value encountered 

### ISSUE THREAD

**Issue by duderion** [GM-Alex/user-access-manager#112]
Hi Alex,

i have setup 2 roles, have 2 sites (1 for role1, 1 for role2)

and if i try to look at the page list, i get the error

wp-content/plugins/user-access-manager/src/UserAccessManager/AccessHandler/AccessHandler.php on line 262

**Comment by duderion** [comment]
it happens because $ip seems to be ipv6 in my case 

i changed the line to "return 0;" and everyting's fine ;]

<img width="464" alt="bildschirmfoto 2017-07-20 um 15 04 56" src="https://user-images.githubusercontent.com/949964/28418696-ee5d28c4-6d5c-11e7-9af5-3800196ad335.png">

**Comment by GM-Alex** [comment]
Duplicates #97
