### ISSUE TITLE
Problem with page access

### ISSUE THREAD

**Issue by fepiro** [GM-Alex/user-access-manager#114]
Hi, I've just installed your plugin and I follow the intructions but when I access as new private group, the page doesn't appears, I only can see page 404
![captura de pantalla 2017-08-19 a las 12 52 36](https://user-images.githubusercontent.com/31157658/29486040-55b2b84e-84dd-11e7-8219-549c26dac5b3.png)
By admin I can see it

**Comment by GM-Alex** [comment]
If you hide content complete the 404 page is shown. Otherwise you could guess the content by the url. If you want to use the redirect feature for example don't hide the content completely.
