### ISSUE TITLE
Access based on IP no longer working after upgrade from 2.0.12 to 2.0.13

### ISSUE THREAD

**Issue by iSpaceGitHub** [GM-Alex/user-access-manager#119]
I’m using UAM with a list of IP addresses. Anyone connecting to the site from one of these IP addresses is automatically logged on, and has access to a number of forms.

After upgrading to UAM 2.0.13 however, the forms are no longer accessible from those IP addresses. As soon as I put back version 2.0.12, it works again.

You asked me to add the setting for the IP range in this post. I'm not sure what you mean by that, so I'm adding some screenshots of all the settings. If you need more information, please let me know.

1.
![image](https://user-images.githubusercontent.com/4669252/30022347-47082690-916b-11e7-9a02-64e210eeb00a.png)

2.
![image](https://user-images.githubusercontent.com/4669252/30022366-5963e1b2-916b-11e7-9b69-42216a666f4b.png)

3.
![image](https://user-images.githubusercontent.com/4669252/30022382-6afa1f86-916b-11e7-95d0-38c7a83eb8f8.png)

4.
![image](https://user-images.githubusercontent.com/4669252/30022413-82eecc0e-916b-11e7-85aa-ab99fe8396db.png)

Can you please look into this?
Thank you!

**Comment by GM-Alex** [comment]
Could it be that there is a typo at your setup. 2.0.13 is more restrictive. Could you start with one IP test if it works and add more and more of your IPs to see if the issue start to appear?

**Comment by GM-Alex** [comment]
Closed because of missing feedback. I you have more information for me just let me know and I will reopen this issue.

**Comment by iSpaceGitHub** [comment]
Hi Alex,

 

Yes, sorry I haven’t had time yet. Also, it’s a live site where I need to confer with several parties before shutting service down partially.  When I have updated info, I will contact you so you can re-open the ticket.

 

Regards,
Boris

**Comment by iSpaceGitHub** [comment]
Today I re-installed the latest plugin version, copy/pasted the list of IP addresses in Notepad, re-ordered them and took out all spaces. After re-insering the list, it all seems to work again.
So it looks like it wasn't a bug at all, just a faulty character or space that slipped into the list somewhere along the line. Thanks for the support!

**Comment by GM-Alex** [comment]
Great! Thanks for the feedback!
