### ISSUE TITLE
SSL with "locked files" setting breaks images

### ISSUE THREAD

**Issue by cfatiuk** [GM-Alex/user-access-manager#120]
I added an ssl to our domain for the front and backend and all is working well on the site except the images on the frontend. They are missing on the frontend of the site and in the media library on the backend. The media files have been updated to https. In the UAM tab when i set lock files to 'no' they images on the site appear again. 

How can I resolve this? Thanks in advance.

**Comment by cfatiuk** [comment]
I've also discovered that the link to the images doesn't work (https://www.XXXXX.org/wp-content/uploads/2017/05/Laugh-For-Life-05-11-2017.jpg) but this link does:
https://www.XXXXX.org/?uamfiletype=attachment&uamgetfile=2017/05/Laugh-For-Life-05-11-2017.jpg

If you want the actual URL, please let me know. Didn't want to post on this forum.

**Comment by GM-Alex** [comment]
Do you have permalinks activated? If not activate them and store the file lock settings again.

**Comment by cfatiuk** [comment]
Thanks for your response. 

I do have them activated. I tried turning off file lock settings and saving permalink and then turning on the settings again and reserving permalinks but it not updating the settings. Images still don't show. I've viewed the site in a private window.

**Comment by GM-Alex** [comment]
Setting permalinks to active should put a .htaccess file at your uploads folder like this:
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteRule ^([^?]*)$ /index.php?uamfiletype=attachment&uamgetfile=$1 [QSA,L]
RewriteRule ^(.*)\?(((?!uamfiletype).)*)$ /index.php?uamfiletype=attachment&uamgetfile=$1&$2 [QSA,L]
RewriteRule ^(.*)\?(.*)$ /index.php?uamgetfile=$1&$2 [QSA,L]
</IfModule>
```

Is a file like that present?

**Comment by cfatiuk** [comment]
Also the theme is genesis and has minimal images but theme images are displaying. It is just the uploads that are not displaying.

**Comment by cfatiuk** [comment]
Yes, the htaccess file is the same in the uploads folder.

**Comment by GM-Alex** [comment]
Hm that should work. Are links for your blog like https://www.XXXXX.org/2017/06/04/posttitle/ working? If yes please have a look at the .htaccess file in your wordpress root folder. Should look like

```
DirectoryIndex index.php

# BEGIN WordPress
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^wp-admin$ wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^(wp-(content|admin|includes).*) $1 [L]
RewriteRule ^(.*\.php)$ $1 [L]
RewriteRule . index.php [L]

# END WordPress
```

Is the rewrite base (`RewriteBase /`) different than `/`?

**Comment by cfatiuk** [comment]
Yes, all page urls work, t is only images that don't show. 

My root htaccess looks a little different:

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

**Comment by cfatiuk** [comment]
`RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
`

**Comment by cfatiuk** [comment]
![screen shot 2017-09-15 at 6 12 51 pm](https://user-images.githubusercontent.com/32001168/30505252-9678f086-9a41-11e7-9a2e-c02f62b8d2a3.png)

**Comment by GM-Alex** [comment]
Does https://www.XXXXX.org/?uamfiletype=attachment&uamgetfile=https://www.XXXXX.org/wp-content/uploads/2017/05/Laugh-For-Life-05-11-2017.jpg work?

**Comment by cfatiuk** [comment]
That doesn't work and neither does the link I sent before: https://www.xxx/?uamfiletype=attachment&uamgetfile=2017/05/Laugh-For-Life-05-11-2017.jpg

**Comment by cfatiuk** [comment]
This is the link https://www.yonkersclsa.org/?uamfiletype=attachment&uamgetfile=2017/05/Laugh-For-Life-05-11-2017.jpg

**Comment by GM-Alex** [comment]
I released version 2.1.0 maybe that fixes the issue, if not just write again. I have to go to bed now, but I will have a look the next days.

**Comment by cfatiuk** [comment]
Okay, will do. Thanks and good night.

**Comment by GM-Alex** [comment]
@cfatiuk Did the new version solved your issue?

**Comment by GM-Alex** [comment]
Closed because of missing feedback. I you have more information for me just let me know and I will reopen this issue.
