### ISSUE TITLE
Latest version do not hide title and comment

### ISSUE THREAD

**Issue by iObi** [GM-Alex/user-access-manager#124]
In the post type section I have hide complete enabled but still title and comments are shown on posts when there is no access.

How can I solve this issue?

**Comment by GM-Alex** [comment]
Please double check the settings. You can define the behaviour for every post type. Check if the settings are correct for every of them.

**Comment by GM-Alex** [comment]
@iObi Did it work for you?

**Comment by iObi** [comment]
Unfortunately not.

Met vriendelijke groet,

Chris Schoeman

**Comment by GM-Alex** [comment]
I'm not able to reproduce the issue. Could you give me access to your page that I could have a look. FTP access would be great, too to debug.

**Comment by iObi** [comment]
Unfortunately due the latest update also some links to pictures were broken. So I have to restore a backup.

Met vriendelijke groet,

Chris Schoeman

**Comment by GM-Alex** [comment]
Any news on that? I think it's the sames issue than here: https://wordpress.org/support/topic/after-2-1-3-update-all-user-lost-the-uam-user-groups

I close this one for now. If you have more feedback or could provide me access to your page I could have a look.
