### ISSUE TITLE
Latest version (2.1.3) Media library error

### ISSUE THREAD

**Issue by emilslv** [GM-Alex/user-access-manager#125]
Plugin version 2.1.3 Causes problem with media library, cant upload media also can't show . Same problem with posts. Cant edit. When disabling plugin everything works.

**Comment by GM-Alex** [comment]
Posts in general aren't editable? Do you have some server error logs for me? You could alos try to disable all other modules expect UAM. If everything works then there is an incompatibility with an other plugin. Just start enabling the other modules and test again after every activation. So we can tear down which plugin makes trouble.

**Comment by emilslv** [comment]
Here are log entries :
PHP Fatal error:  Class 'UserAccessManager\\Config\\SelectionConfigParameter' not found in /user-access-manager/src/Config/ConfigParameterFactory.php

**Comment by emilslv** [comment]
Unknown column 'from_date' in 'field list'  SELECT object_id AS id, object_type AS objectType, from_date AS fromDate, to_date AS toDate\n                FROM wp_uam_accessgroup_to_object\n                WHERE group_id = '0'\n                  AND group_type = 'user'\n                  AND object_id != ''\n                  AND (general_object_type = '_term_' OR object_type = '_term_') AND (from_date IS NULL OR from_date <= '2017-09-19 15:31:15') AND (to_date IS NULL OR to_date >= '2017-09-19 15:31:15'), ko izdar\xc4\xabjis require('wp-blog-header.php'), wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts, apply_filters_ref_array, WP_Hook->apply_filters, call_user_func_array, UserAccessManager\\Controller\\Frontend\\PostController->showPosts, UserAccessManager\\Controller\\Frontend\\PostController->filterRawPosts, UserAccessManager\\Controller\\Frontend\\PostController->processPost, UserAccessManager\\Access\\AccessHandler->checkObjectAccess, UserAccessManager\\Access\\AccessHandler->getUserGroupsForObject, UserAccessManager\\UserGroup\\AbstractUserGroup->isObjectMember, UserAccessManager\\ObjectMembership\\PostMembershipHandler->isMember, UserAccessManager\\ObjectMembership\\PostMembershipHandler->assignRecursiveMembershipByTerm, UserAccessManager\\UserGroup\\AbstractUserGroup->isTermMember, UserAccessManager\\UserGroup\\AbstractUserGroup->isObjectMember, UserAccessManager\\ObjectMembership\\TermMembershipHandler->isMember, UserAccessManager\\ObjectMembership\\ObjectMembershipWithMapHandler->getMembershipByMap, UserAccessManager\\UserGroup\\AbstractUserGroup->isObjectAssignedToGroup, UserAccessManager\\UserGroup\\AbstractUserGroup->getAssignedObjects, UserAccessManager\\Database\\Database->getResults,

**Comment by GM-Alex** [comment]
Seems the installation failed. The first error is a hint that the plugins is corrupted. Please download it again and reinstall it. The second error say that the database table aren't installed proper. Use UAM > Setup > Reset User Access Manager to drop and recreate the plugin tables.

**Comment by GM-Alex** [comment]
@emilslv Did that fixes your issue? I close this one until the next feedback.
