### ISSUE TITLE
Escaping  $_SERVER['REQUEST_URI'] in LoginControllerTrait.php

### ISSUE THREAD

**Issue by bunglegrind** [GM-Alex/user-access-manager#127]
In function getRedirectLoginUrl(), , line 125, file src/Controller/Frontend/LoginControllerTrait.php, should $_SERVER['REQUEST_URI'] be escaped by esc_url?

Cheers

**Comment by GM-Alex** [comment]
`urlencode` should be enough, or do I miss something?

**Comment by bunglegrind** [comment]
Indeed... sorry I haven't noticed that it was a query parameter. My bad
