### ISSUE TITLE
Automatic translation of a user into a group

### ISSUE THREAD

**Issue by login2030** [GM-Alex/user-access-manager#129]
Hey. I make a personal cabinet with access to a monthly fee. The plugin is super. Is there an API for automatically transferring a user to a private group? Thank you so much!

**Comment by login2030** [comment]
Use the functions ($wpdb->insert and $wpdb->insert), to change the table 'uam_accessgroup_to_object' is a bad idea?

**Comment by GM-Alex** [comment]
I don't get the second question. Currently there is no API for that but I'm working on a subscription handler which will you allow to extend it via a custom subscription handler.

**Comment by login2030** [comment]
In any case, thanks for developing )
