### ISSUE TITLE
LOGIN FORM

### ISSUE THREAD

**Issue by Legapro** [GM-Alex/user-access-manager#130]
Hi login form short code not display why?

**Comment by GM-Alex** [comment]
The login form is only shown if you are not logged in and on a single page (not at the post list view).

**Comment by GM-Alex** [comment]
@Legapro Did that solve your issue?

**Comment by Legapro** [comment]
In Atto le have inserti this message is visibile for... Etc etc and inserti
Short code

Il 27 set 2017 10:54 AM, "Alexander Schneider" <notifications@github.com>
ha scritto:

@Legapro <https://github.com/legapro> Did that solve your issue?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GM-Alex/user-access-manager/issues/130#issuecomment-332455525>,
or mute the thread

**Comment by GM-Alex** [comment]
Sorry I really don't understand what you are trying to say? Is this Italian mixed with English?

**Comment by Legapro** [comment]
Scrivo Italiano allora 😁

Volevo sapere se il login form può apparire per i visitatori sotto il
titolo dell'articolo

Il 27 set 2017 11:00 AM, "Alexander Schneider" <notifications@github.com>
ha scritto:

**Comment by GM-Alex** [comment]
Sorry I still don't get it. Just add the tag to the post content and the login form will be shown if the conditions in my first post are fulfilled.

**Comment by GM-Alex** [comment]
Closed because no update since seven days or more. I there is any new just put it here and I will reopen the issue.
