### ISSUE TITLE
PHP 5.6 - strict standards error

### ISSUE THREAD

**Issue by bunglegrind** [GM-Alex/user-access-manager#134]
Loading the homepage:

Strict standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\BaseControllerTrait define the same property ($php) in the composition of UserAccessManager\Controller\Controller. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in C:\wamp64\www\web\wp-content\plugins\user-access-manager\src\Controller\Controller.php on line 161

Using PHP 7 it does not appear.

**Comment by GM-Alex** [comment]
Already fixed for the next release.

**Comment by dhunink** [comment]
Just updated to version 2.1.4. There are still warnings…
No cache in place.
The notices appear to regard different lines though.

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\AdminOutputControllerTrait define the same property ($wordpress) in the composition of UserAccessManager\Controller\Frontend\PostController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/PostController.php on line 538

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\AdminOutputControllerTrait define the same property ($wordpressConfig) in the composition of UserAccessManager\Controller\Frontend\PostController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/PostController.php on line 538

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($wordpress) in the composition of UserAccessManager\Controller\Frontend\ShortCodeController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/ShortCodeController.php on line 137

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($php) in the composition of UserAccessManager\Controller\Frontend\ShortCodeController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/ShortCodeController.php on line 137

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($wordpressConfig) in the composition of UserAccessManager\Controller\Frontend\ShortCodeController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/ShortCodeController.php on line 137

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($template) in the composition of UserAccessManager\Controller\Frontend\ShortCodeController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/ShortCodeController.php on line 137

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\AdminOutputControllerTrait define the same property ($wordpress) in the composition of UserAccessManager\Controller\Frontend\TermController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/TermController.php on line 380

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\AdminOutputControllerTrait define the same property ($wordpressConfig) in the composition of UserAccessManager\Controller\Frontend\TermController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/TermController.php on line 380

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($wordpress) in the composition of UserAccessManager\Controller\Frontend\RedirectController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/RedirectController.php on line 415

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($php) in the composition of UserAccessManager\Controller\Frontend\RedirectController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/RedirectController.php on line 415

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($wordpressConfig) in the composition of UserAccessManager\Controller\Frontend\RedirectController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/RedirectController.php on line 415

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($template) in the composition of UserAccessManager\Controller\Frontend\RedirectController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/RedirectController.php on line 415

**Comment by GM-Alex** [comment]
Please try 2.1.5

**Comment by dhunink** [comment]
Just updated. Most are gone now, but two remain:

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($template) in the composition of UserAccessManager\Controller\Frontend\ShortCodeController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/ShortCodeController.php on line 145

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($template) in the composition of UserAccessManager\Controller\Frontend\RedirectController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/users/topogftp/staging.topografieindeklas.nl/wp-content/plugins/user-access-manager/src/Controller/Frontend/RedirectController.php on line 423

**Comment by GM-Alex** [comment]
Oh man... I'm starting to hate traits :). Ok I will this soon.
