### ISSUE TITLE
My category Order Option Hide Empty no seting

### ISSUE THREAD

**Issue by Kminowa** [GM-Alex/user-access-manager#136]
hello

Empty's category is not displayed even if Hide Empty is not checked because the category "Empty" is also displayed by using "My category Order" widget.

1.ture display
Hide Empty option off 

category1 (10)
category2 (0) <- no display
category3 (8)
category4 (7)

2.now bug display

Hide Empty option off 
category1 (10)
category3 (8)
category4 (7)

**Comment by GM-Alex** [comment]
I'm sorry I don't understand the issue. Could you describe it a little more? Thanks.

**Comment by GM-Alex** [comment]
Closed because of none response. If you have more information I will reopen the issue.
