### ISSUE TITLE
wordpress login and log out issue. not working.

### ISSUE THREAD

**Issue by sagartroublehunt** [GM-Alex/user-access-manager#137]
[https://troublehunt.com/wp-admin/plugins.php?plugin_status=all&paged=1&s](url)

**Comment by GM-Alex** [comment]
The strict standard is a warning and will not break the site (expect the not so nice output). What is the real issue is the `Fatal error: Allowed memory size of 134217728 bytes **exhausted` error. You need to increase the memory limit of PHP.

**Comment by sagartroublehunt** [comment]
but how can i do that..I'm using wordpress online. with the panelsecure
server. i don't have any application or software of wordpress. how do i
increase limit of that file.


please, I'm waiting for your valuable response, and i hope you guys will
definitely give me a solution.





With Regards,
Mr. Sagar Wani
CEO, Entrepreneur
www.troublehunt.com
09923024433

**Comment by GM-Alex** [comment]
Sometimes you can do it at the backend of your hoster. But the best way is to ask your hoster to increase the php memory limit.
