### ISSUE TITLE
The message on the settings page.

### ISSUE THREAD

**Issue by Maxnik2000** [GM-Alex/user-access-manager#138]
Hi,

A message appeared on the "Post type settings" page of the plug-in "User Access Manager" - 
"Warning: array_fill (): Number of elements must be positive in /home/.../wp-content/plugins/user-access-manager/src/Wrapper/Php .php on line 47 ".

The  "Post type settings" page does not show the old settings, in particular in the form of "Displayed text".

What should we do?

**Comment by GM-Alex** [comment]
Fixed with 2.1.4
