### ISSUE TITLE
Users of other groups visible in user editor 

### ISSUE THREAD

**Issue by a3vd** [GM-Alex/user-access-manager#141]
On our website, with several groups and for every group an editor which is able to edit users (in his group) i have a big problem because all editors can see all users.(even if not in that group)

In de user editor in the dashboard the UAM User Group is displayed as none , which is logical because the editor is not in that group.

I am using latest version (2.1.5), no problems with database
![uam2](https://user-images.githubusercontent.com/29863575/31653512-1d9cd3ee-b323-11e7-985d-c3482a9c055e.JPG)
![uam1](https://user-images.githubusercontent.com/29863575/31653514-1db2096c-b323-11e7-81ad-2f5dee7b8c6d.JPG)

**Comment by GM-Alex** [comment]
Users aren't handled of filtered by UAM. It should be the same behavior without the UAM plugin. Or do I miss understand something?
