### ISSUE TITLE
Catchable fatal error: Object of class WP_Term could not be converted to string

### ISSUE THREAD

**Issue by Brozgar** [GM-Alex/user-access-manager#143]
Hi,

Whenever I try to change moderation rules for users using this plugin I get an error: **Catchable fatal error: Object of class WP_Term could not be converted to string in .../wp-includes/taxonomy.php on line 2283**

Can it be caused by the PHP version 7+? We've upgraded it recently and before that it worked fine, so that's the best guess we have. However, personally, I don't see why that would cause such error. It's tricky to debug due to the amount of source files of the plugin, so I decided to ask here first. Thanks!

I don't know if that'd help, but here are the screenshots of where the changes are made in a post: https://yadi.sk/i/39yv8kUn3NsfHB
And here: https://yadi.sk/i/k0C57VwQ3NsfSL
After the changes in these boxes are done we get the error after saving.

Plugin version: 2.1.5
WP version: 4.8.2

**Comment by GM-Alex** [comment]
How did you solve it?

**Comment by Brozgar** [comment]
It seems to be not related to this plugin, because we also get the same error with another plugin. And what's weird - if we create a new post and apply these changes there's no error.
