### ISSUE TITLE
update gives error

### ISSUE THREAD

**Issue by cloudquarter** [GM-Alex/user-access-manager#145]
Since i updated today this text is appearing on every screen???

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($template) in the composition of UserAccessManager\Controller\Frontend\ShortCodeController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/goingrur/public_html/wp-content/plugins/user-access-manager/src/Controller/Frontend/ShortCodeController.php on line 145

Strict Standards: UserAccessManager\Controller\Controller and UserAccessManager\Controller\Frontend\LoginControllerTrait define the same property ($template) in the composition of UserAccessManager\Controller\Frontend\RedirectController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed in /home/goingrur/public_html/wp-content/plugins/user-access-manager/src/Controller/Frontend/RedirectController.php on line 423

**Comment by GM-Alex** [comment]
Please try 2.1.6. Should be available within the next 60 minutes.
