### ISSUE TITLE
Group limit and docs

### ISSUE THREAD

**Issue by atabar2** [GM-Alex/user-access-manager#146]
Is there a limit to the number of groups that you can form?  I plan on forming potentially a hundred plus unique groups and wanted to know if there was an upper limit.  Also, you mentioned the documentation or user manual at the Wiki home but I can't find anything that talks about this plugin or  how to use it.  Where would I find those docs.  Also would like to know if you can determine who all  is in a group.  It looks like they show in the Users section of WP but would be great to be able to select a group somewhere in the UAM  plugin section and have it show who is in the group, especially because some people will  belong to multiple  groups and I will have many users to page through.
Thanks!

**Comment by GM-Alex** [comment]
The documentation can be found at https://github.com/GM-Alex/user-access-manager/wiki, but it's still WIP. There is no limit but I think on certain point many groups will result in performance issues. There is currently no plan to make a view for the group assignation. You could use some of the code snippets here https://github.com/GM-Alex/user-access-manager/wiki/Code-Snippets to do it by your own.
