### ISSUE TITLE
I can't edit notification content it stay the same. 

### ISSUE THREAD

**Issue by danio987** [GM-Alex/user-access-manager#149]
I tried to change notification but I still get message Sorry you have no rights to view this entry!

**Comment by realpb** [comment]
I have the same problem. I added custom text in the "content" field but it doesn't work. Always just shows the default text.

**Comment by GM-Alex** [comment]
Please check if you have changed it for the correct post type (called `Object Type` at the settings section). Each post type has a different setting or can inherit the text from the default type, but then you have to set `Use default settings for Pages` to `Yes`.

**Comment by danio987** [comment]
Thanks, this worked fine!

2017-10-28 20:28 GMT+02:00 Alexander Schneider <notifications@github.com>:
