### ISSUE TITLE
Lock files blocks content on pages

### ISSUE THREAD

**Issue by monchib** [GM-Alex/user-access-manager#151]
Hi Alex, I've being using this plugin for a while. I love it. Unfortunately few weeks ago we found out users were downloading videos using the direct link to the file. Those videos were linked to a user role and published only on the page associated to that user role. So I tried locking the files but the video disappear also on the page. I get an error on the player saying " error loading this resource". 
If I lock all the files, on some browsers the website looks strange like if the css are not totally working. If I limit the the lock to mp4 files the site looks good.
Permalinks are set to postname.
I thought it was a conflict with some plugin so i deactivated all of them and left the main ones: 
Media Library Assistant
User Profiles Made Easy
WPFront User Role Editor
and of course User Access Manager.

Is there anything I can do? 
Thank you very much for the awesome plugin and for the help,
Simo :)

**Comment by GM-Alex** [comment]
Are you using the default video player of wordpress? For me it works without problems.

**Comment by monchib** [comment]
Hi Alex, thanks for the reply. Yes I am. Any chance I can give you access
to the site and you can check why it's behaving this way? I'm using php7,
can be this a problem?
Thanks

**Comment by GM-Alex** [comment]
I also using PHP 7 for testing. Just send me the credentials for your site to alexanderschneider85@gmail.com. I will have a look the next few days.

**Comment by GM-Alex** [comment]
Should be working with the lastest version setting ´Locked directory type´ to ´Wordpress´ at Settings > File settings. Note that the path structure must be the default one (YOURDOMAIN/uploads/YEAR/MONTH/FILENAME).
