### ISSUE TITLE
Bulk Import

### ISSUE THREAD

**Issue by crookesa** [GM-Alex/user-access-manager#152]
Hi

I am using UAM and want to bulk import some users to my wordpress site.

Can I bulk import the users first and then assign a group or can it be done a field during the import.
Trying to work out how to make the import work with the least amount of problems

**Comment by GM-Alex** [comment]
There is currently no field for assign the group during the import. You have to bulk import the users first and then assign the groups at the backend.

**Comment by ccaraway1** [comment]
How do I assign users on the backend?? We had to create a new UAM group, and I need to add all users into that group. We have thousands of users, so it would be ideal not to have to update their UAM group manually.... please say there is a way!!
