### ISSUE TITLE
User group selection not saved when adding a user

### ISSUE THREAD

**Issue by jangellmsn** [GM-Alex/user-access-manager#154]
I have UAM installed and when adding a new user via the User tool in WordPress, I select one or more UAM user groups at the bottom of the tool to assign the user to those selected groups.  However, upon the save of the new user, the selected user groups were not retained. Instead, you have to go in and edit the user that you just created to re-select the user group selections. This happens when both 1 or more user groups are selected. If it is not possible to retain the user group selection during the ADD mode of a user, then the selections should be hidden from display otherwise the admin will assume their selection was made.  Can you please advise if this is a bug or "feature" (heh) and how to resolve it?  I am running the most recent version of WordPress 4.8.2 and version 2.1.6 of UAM.

Thank you in advance,
Jennifer

**Comment by GM-Alex** [comment]
What ist the user tool? A plugin?

**Comment by jangellmsn** [comment]
The User Tool that comes packaged with WordPress.  I do not have any additional plug-ins installed associated with Users other than your UAM plug-in.

**Comment by GM-Alex** [comment]
The users section at the backend? Sorry I'm a little confused because of the term "Tool". Could you provide me a screen?

**Comment by jangellmsn** [comment]
Sorry - once you have logged into the admin area of a website running on the WordPress framework, select "Users" on the left sidebar and then select the "Add new user" option.  That will bring you into the User utility/section/tool to add a new user to the website.  The UAM user group selection options appear at the bottom of this area.  If you check any of the UAM user group options that you have setup using the UAM section, they are not saved upon ADD.  You are forced to go back in and edit a user and re-select the user group selections.

**Comment by GM-Alex** [comment]
Thanks for your explanation. I was able to fix it.
