### ISSUE TITLE
Change the "All" option of read/right access to "All connected and not connected users"

### ISSUE THREAD

**Issue by Dostoi** [GM-Alex/user-access-manager#156]
The "All" option is misleading at first I tough it meant "all member of any group/all connected users", so I set it and discovered later while doing some test that  even if I'm not connected I could access those pages.
It would be better if it was more obvious what you mean by all by changing how this option is named

**Comment by GM-Alex** [comment]
I changed it to `All users (group and none group users)`.

**Comment by Dostoi** [comment]
I'm not sure if it's enough. There is several situation for a user :

- Connected and belonging to the group of the page
- Connected and belonging to another group
- Connected and belonging to no group
- Not connected user (so it's not important if they're supposed to belong to a group or not)

Right now the way it's written make it look like it's the three first case whereas it's all of them.
But it's still better this way.
