### ISSUE TITLE
Custom post type access issue

### ISSUE THREAD

**Issue by nicksss93** [GM-Alex/user-access-manager#157]
Hello,

We've received a report from a user on our website today, who didn't have access to a certain custom post type he used to have access to before.
In order to explain where the issue is, I need to get a bit more specific with our access hierarchy and organization. We're running a sort of a freelance website, where one could post a job request and then receive bids for them by "freelancers". Users always have access to own posts, while freelancers have (or don't have) access based on their user groups participations. This used to work OK. However, since the latest update (probably), the user no longer can see the bids to his project - bids are a custom post type that is related to the 'project' custom post type.

I tried setting all bids (as a custom post type) to be always accessible for a user group with all regular users in it from the default user group setting in the plugin, but that didn't seem to work.

Another possible solution would be to make the "author has access to own" option extend access to related post types and pages as well, not just the original one.

Hope this is helpful.

I could elaborate on the issue and what we're trying to achieve in more detail, if needed.

Thank you for your time!

**Comment by GM-Alex** [comment]
I changed the settings so that every custom post type can have it's own settings, maybe that is the issue, that since that the post types aren't configured right. Could that be? If recursive locking is active the access level will be inherit from the "parent" post. For example attachments will have the same user groups than the post which they are connected to.

**Comment by nicksss93** [comment]
Hi,

I updated to the new version from yesterday, but I don't find any difference from now. Recursive locking is active and access is inherited - yes, but that doesn't take in account the author access to the parent page - the new one has a different author and thus an error message displays to the parent post author that he doesn't have access to the new child post. And that is what we're trying to achieve. Hope this is a bit more clear now.

One way to fix it would be to be able to automatically add another user group to the child post type from settings - I don't see this as an existing option now. I tried with the default user group setting, but what that does is pre-select the default user group when the new child post is posted through the admin panel - it doesn't get added automatically when it's published by a user on the website.

Or, there could also be an option that "author has access to own" grants access to all child posts as well. This could also fix it.

I can test some fixes in the meantime, if that's needed.

Thanks!

**Comment by GM-Alex** [comment]
I think the fix of bug #133 results in this issue for you. Both solutions you are suggesting put to much complexity to the plugin in my opinion. What I could/would do is add a hook (filter) to the checkObjectAccess (https://github.com/GM-Alex/user-access-manager/blob/master/src/Access/AccessHandler.php#L158) function that you can check if the post type of the parent post is a job request and the user is the author. Would that ok for you?

**Comment by nicksss93** [comment]
Hi,

I think this might work, if I got it correctly.

Then, I would need to specify which custom post type is to be considered as a job request, right?

I'm still using v.2.1.5 in the meantime, where it works good for me - it's the 2.1.6 update after which the access issue happens.

Thanks.

**Comment by GM-Alex** [comment]
The filter will be `uam_get_user_user_groups_for_object_access`.
