### ISSUE TITLE
Whitescreen after update from 2.0.13 to newer version

### ISSUE THREAD

**Issue by Rewilon** [GM-Alex/user-access-manager#158]
Hi there,
as I told in your support site... until the update from 2.0.13 to 2.1.0 the plugin works great.
But from then when I try to update, the website doesn’t work anymore. (“whitescreen”)
After replacing the plugin-directory to old version 2.0.13 everything works well again.

I tried to make a complete reinstallation of the plugin (version 2.1.6).
Good: Installation of version 2.1.6 worked, no problems.
Bad: Activation failed with “Class ‘UserAccessManager\Wrapper\Php’ not found”.

Any ideas? :-)

**Comment by GM-Alex** [comment]
No. I would need full access to your page to debug it.

**Comment by GM-Alex** [comment]
I will close this because there wasn't any future feedback. Anyway, please see the troubleshoot section here: https://github.com/GM-Alex/user-access-manager/wiki/Troubleshoot
