### ISSUE TITLE
Site is not shown – subpage – recursive lock

### ISSUE THREAD

**Issue by wpdon** [GM-Alex/user-access-manager#16]
Hello, here is wpdon from Germany.
I have the following problem:

For my site I created two user groups (Administrator and Customer).

Then I have a parent page (It’s called “user management”) and some different subpages (e. g. my documents).
The page “user management” is assigned to the Group “Administrator”, the subpages are assigned to the Group “customer”.

Now if the user “customer” opens the site “my document”s, there is shown an error page (404).

I have also checked the plugin settings. The checkbox of the recursive lock is turned off. The pages are all released.
When I remove the lock from the parent page, then all subpages will be shown.

**Comment by GM-Alex** [comment]
Fixed for 2.0.0
