### ISSUE TITLE
get all groups for a user

### ISSUE THREAD

**Issue by SaMeHub** [GM-Alex/user-access-manager#160]
Hi Alex

Is it possible that your code snippet to get all groups for a given user (https://github.com/GM-Alex/user-access-manager/wiki/Code-Snippets#get-all-user-groups-for-user) doesn't work anymore in version 2.1.7?
All relevant functions seem to be private now!?

Thanks in advance!!

Cheers
Sascha

**Comment by GM-Alex** [comment]
They aren't private, but I split the access handler to access handler and user group handler. However I forgot to add a getter at the UserAccessManager main class and change the snippets. I will do this soon.
