### ISSUE TITLE
Partially hiding content (shortcodes)? 

### ISSUE THREAD

**Issue by newoceans** [GM-Alex/user-access-manager#161]
Support request: is it possible to hide parts of a page or post, for example by using shortcodes?

If not: feature request, may be?

**Comment by GM-Alex** [comment]
Yes. The `User Access Manager Private & Public Extension` (https://wordpress.org/plugins/user-access-manager-private-public-extension/) is build in, expect negation like !groupName and showprivate and shownotauthorized parameter.

**Comment by newoceans** [comment]
Allright, great! Thnx for the quick reply! ;-)

**Comment by newoceans** [comment]
One question: you say it 'is build in'. Does it mean I don't have to download and install the plugin you mentioned?

**Comment by GM-Alex** [comment]
No you don't have to download it, but it works the same way the plugin did.

**Comment by newoceans** [comment]
Hi Alexander, sorry for annoying you... But I added this code to a page:
`[public]Public text a logged-in user won’t see[/public]`

It shows up literally the same (that is: [public]Public text a logged-in user won’t see[/public]), both when logged in and logged out. This is the page (see bottom):
https://www.heerlenstandby.nl/organisatie/

Any idea what I'm doing wrong?

**Comment by newoceans** [comment]
Hi Alexander, can you please take a look at what's going wrong? My client wants to know when I can fix this issue... Otherwise I have to find another solution. Thnx! ;-)

**Comment by GM-Alex** [comment]
Hey, sorry for the delay, I prefixed the commands with `uam_`, so `[uam_public]Public text a logged-in user won’t see[/uam_public]`. Currently I'm working on the wiki, I will add this soon.

**Comment by newoceans** [comment]
Hi Alexander, no worries! ;-)

Thnx for the extra info, indeed, with the prefix it seems to work nicely! 

Little detail: it conflicts when used in between sections and content blocks of a page builder (like Avia's Layout Builder of Enfold Theme). 

For example, I paste `[uam_public]` in a code block at the beginning of the page. Then I have a full width content block for page title and subtitle. Then a 50% percent wide content block for a column with text, and another 50% wide content block for a second column. And then I paste `[/uam_public]`. 

That does not work. Guess it conflicts with shortcodes of the Layout Builder.

It does work when I paste `[uam_public]` at the beginning of each content block (separately), and paste `[/uam_public]` at the end of each content block too. So basicly in the html part only, so there's no interference with the Layout Builder shortcodes. This way I have to past the UAM shortcodes 3 times, which is a bit clunky - so if you have a solution or workaround, that would be nice! 

Anyway, really happy for now, thnx for replying and keep up the good work! :-D
