### ISSUE TITLE
Not working with page templates that don’t use the loop

### ISSUE THREAD

**Issue by xbd63** [GM-Alex/user-access-manager#163]
Hi there,

I’ve realised that the plugin is only working for page templates that use the standard WordPress loop.

I have some page templates that don’t use the WordPress loop and these are still being shown publicly even when I’ve set them to be restricted to certain user roles.

I’ve tested with other page templates and the plugin works fine, correctly hiding them from the public. It only seems to fail when I don’t use a loop.

Is there a way around this?

Thanks
Sean

**Comment by GM-Alex** [comment]
Could you name me a template which doesn't work, that would be great.

**Comment by xbd63** [comment]
It's a custom page template which displays a list of meetings (a custom post type), here's the file.

If I create a page with this template and add it to an access group, the page is still fully publicly accessible. Whereas pages that use the standard page template are only accessible to that group.

`<?php
/*
Template Name: Meetings Page
*/

get_header(); ?>

    <div id="container">
<?php
          get_template_part( 'loop', 'page' );

          $args=array('post_type' => 'meeting','post_status' => 'publish','posts_per_page' => -1);
          $my_query = new WP_Query($args);
          if( $my_query->have_posts() ) {
            while ($my_query->have_posts()) : $my_query->the_post(); 
?>
              <a href="<?php the_permalink() ?>"><?php the_title(); ?></a>
              
<?php
            endwhile;
          }
          wp_reset_query();  // Restore global post data stomped by the_post().
?>
              
    </div>

<?php get_sidebar(); ?>
<?php get_footer(); ?>
`

![screen shot 2017-11-07 at 10 32 50](https://user-images.githubusercontent.com/7498955/32489232-315fa6c4-c3a7-11e7-9961-7139872f146a.png)

**Comment by GM-Alex** [comment]
Works for me as expected (for the default post type). Could it be that you don't choose to inherit the settings from the default post settings to your new type meetings?

**Comment by xbd63** [comment]
Ok I've done some more tests, and it appears that the only part that's affected by the group's rules is what's called with this line:

`get_template_part( 'loop', 'page' );`

So if I add anything before or after that line into the template file, it's visible publicly.

I'm using a child theme, based on the twentyten template. Could that be part of the issue?

**Comment by GM-Alex** [comment]
I will close this issue until you have some new information for me. Hope this ok for you.
