### ISSUE TITLE
AccessHandler::getUserGroupsForObject() throws fatal error

### ISSUE THREAD

**Issue by cleuenberg** [GM-Alex/user-access-manager#164]
Hello!

You may remember my little code snippet provided in this WordPress-thread: https://wordpress.org/support/topic/how-to-tell-if-the-logged-in-user-is-in-a-group/

Since last plugin update (v2.1.7), this does not work anymore. I checked the code snippets here at your Github-Page and noticed that you slightly changed it, but I still get the following error:

> Fatal error: Uncaught Error: Call to undefined method UserAccessManager\Access\AccessHandler::getUserGroupsForObject() 

Any idea or solution to this problem?
Thank you!

**Comment by GM-Alex** [comment]
Yes please see issue #160
