### ISSUE TITLE
Post is public, access restriction not working

### ISSUE THREAD

**Issue by visionaris** [GM-Alex/user-access-manager#170]
I need to use this plugin for a site who has a blog, only access by login to blog, but free access to site.
When I select the users group and mark a post for access only this group, the title post says title and "need access" but I can clic and see all the post without registration.
Otherwise I cant configure a form to register or login to see posts.
Please help me!
Thanks!

**Comment by GM-Alex** [comment]
Please set `Hide complete` to `Yes` for all post types at `Settings > Post type settings` and test if the posts which are assigned to a user group are hidden for not logged in users. If yes I think you don't grab the post content by the default Wordpress function. First try the default template. If it works as expected you need to adjust your template.

**Comment by GM-Alex** [comment]
I will close this until we have more information.
