### ISSUE TITLE
Prompt to upgrade database even though it has been clicked

### ISSUE THREAD

**Issue by Nybster** [GM-Alex/user-access-manager#173]
I'm getting the prompt to upgrade the database and, even though I click to upgrade it, the prompt doesn;t go away

Looking at my error log I can see loads of entries like this one

[15-Nov-2017 15:04:32 UTC] WordPress database error Unknown column 'from_date' in 'field list' for query SELECT object_id AS id, object_type AS objectType, from_date AS fromDate, to_date AS toDate
                FROM nphcwp_uam_accessgroup_to_object
                WHERE group_id = '0'
                  AND group_type = 'user'
                  AND object_id != ''
                  AND (general_object_type = '_term_' OR object_type = '_term_') AND (from_date IS NULL OR from_date <= '2017-11-15 15:04:32') AND (to_date IS NULL OR to_date >= '2017-11-15 15:04:32') 

I'm guess in my DB is screwed?? (although the site seems to work OK)

I've tried uninstalling and reinstalling

Any advice?

**Comment by GM-Alex** [comment]
Please try the database repair function at the backend setup section.

**Comment by Nybster** [comment]
Thanks for responding

If I click on Setup from the UAM menu in wordpress I just get a blank screen with

Please update the database of the User Access Manager. Click here to proceed

In fact, I get the same no matter what UAM menu option I click

**Comment by GM-Alex** [comment]
Seems the database isn't the main problem. Which PHP Version you are using? Are you using linux or windows?

**Comment by Nybster** [comment]
Server PHP version is 5.

**Comment by Nybster** [comment]
5.4.45

**Comment by GM-Alex** [comment]
Could you provide me ftp access and create me an admin user for wordpress?

**Comment by Nybster** [comment]
Will do, but it will need to wait until Monday when I am back on a PC if that’s ok?

**Comment by GM-Alex** [comment]
Sure my mail is alexanderschneider85@gmail.com

**Comment by GM-Alex** [comment]
PHP 5.4.45 causes the issue. The update solved it.
