### ISSUE TITLE
Hide the edit page option if the user doesn't have the right to edit this page

### ISSUE THREAD

**Issue by Dostoi** [GM-Alex/user-access-manager#174]
I don't know if it's something that you can do but it would be great to hide the edit page option in the admin bar if the user doesn't have the right to edit this page. Because currently it's always shown and when you click on it a new page load and tells you that you don't have the right to edit this page, which can be confusing for users and doesn't make it easy to know when you actually have the right to edit a page.

**Comment by GM-Alex** [comment]
Could you provide me a screenshot?

**Comment by Dostoi** [comment]
Sorry I wasn't clear enough. I'm talking about the "Edit this page" option that is in the toolbar at the top of every page when you're logged in and that allow you an easy access to the edition of the page you're currently seeing. It's an option that is shown once you give the page edition right to an user by modifying it's role (not through your plugin).

The issue is that this option is shown for every page regardless of the fact that you can actually edit it or not (that the group that you belong too allow you the edition for this page or not).

I'm sorry, I can't add a screenshot right now, tell me if it's still not clear enough and I'll try to take one as quick as possible.

**Comment by Dostoi** [comment]
It's id is "wp-admin-bar-edit", you can see it in the html once you're connected to a wordpress and on any page (except main page).

**Comment by Dostoi** [comment]
Thanks for the quick implementation of the three issue :)

**Comment by Dostoi** [comment]
I'm still having this issue. The button I'd like to see only if I can edit the page is the one on the top right (here it's in french "Modifier la page" but it should be "Edit this page" in english).
![issue](https://user-images.githubusercontent.com/7694864/33009199-5fe32258-cdd6-11e7-8f42-26fa0ce8ff7f.jpg)

The issue is about a page (actually ma whole site, but it's an example to make it simpler) that have a group which allow users to see but not to edit the page (G1) and another one that allow to see and edit the page (G2). My user has edit right given by a wordpress role and is only member of G1 so he can see the page but not edit it. 
I'd like him not to see the "Edit this page" button in the top bar as it's confusing and not helping to know which page you can actually edit or not.

**Comment by Dostoi** [comment]
Hi,
I've made a fix for this issue. Here's the sample code :


```
/**
     * Check the page group and compare it with the user's ones
     * then check for wirte access if there's a match between the page group and he user's group
     * @param $user_groups ArrayObject of the user's groups
     */
    private function hideEditButton($user_groups)
    {
        global $wpdb;
        global $post;
        $page_id = $post->ID;
        $page_groups = $wpdb->get_col("SELECT group_id FROM " . $wpdb->prefix . "uam_accessgroup_to_object
          WHERE object_id = $page_id");
        
        $write_match = false;
        
        foreach ($page_groups as $tested_page_group) {
            foreach ($user_groups as $user_group) {
                if ($tested_page_group == $user_group) {
                    $write_access = $wpdb->get_col("SELECT write_access FROM " . $wpdb->prefix . "uam_accessgroups
          WHERE ID = $tested_page_group");
                    if ($write_access[0] != "none") {
                        $write_match = true;
                        break;
                    }
                }
            }
            if ($write_match)
                break;
        }
        if (! $write_match) 
           $this->cssHide();
    }
    
    /**
     * Add css code to hide the edit button
     */
    private  function  cssHide(){
        ?>
<style type="text/css">
#wp-admin-bar-edit {
	display: none;
}
</style>
<?php
    }
```

I'm new to php so my code musn't be the best way but it still work ^^
I didn't make a pull request as I didn't know where to put this code in yours.

**Comment by Dostoi** [comment]
I juste discovered after doing some test that if an user is only in the default group he won't be in the uam_accessgroup_to_object table, so this only work if the user isn't only in the default group.
And you need to watch out for the admin user too.
