### ISSUE TITLE
WordPress 4.9.

### ISSUE THREAD

**Issue by iacsaragon** [GM-Alex/user-access-manager#175]
Hi! My wordpress has been updated to version 4.9 and user access manager stopped working (in fact, it made my web getting crazy...) Is there any planned update? Thank you very much in advance!

**Comment by GM-Alex** [comment]
What is exactly not working? Tested it several days ago and it worked like expected.

**Comment by iacsaragon** [comment]
My website gets deconfigured when this plugin is active. All the menus get wrong (the menus appearing are not the correct ones) for example. If I deactivate the plugin, everything is correct.

**Comment by iacsaragon** [comment]
Deactivated:
![imagen](https://user-images.githubusercontent.com/33748266/32942428-537bd072-cb89-11e7-966e-c2b306358379.png)

Activated:
![imagen](https://user-images.githubusercontent.com/33748266/32942495-820ead88-cb89-11e7-84dd-28c89d0cdf57.png)

**Comment by GM-Alex** [comment]
Did you update or change something else? The plugin worked with 4.8?

**Comment by iacsaragon** [comment]
Yes, the plugin worked perfectly with last version (4.8). Wordpress updated automatically and it began to work like that. I deactivated all the plugins and reactivated all of them one by one. And the only conflict was with this one. I had to deactivate it, but I would like to make it work, I was using it intensively...

**Comment by GM-Alex** [comment]
Could you give it a try with the default template. For my test environment it works everything like expected with 4.9.

**Comment by masimies** [comment]
When this issue is targeted to menu only?
Have you any other plugin, what affects to menu or menu fonts?
If that plugin conflicts, not UAM.

I have no issues either in my site with 4.9.

br,

-matti

**Comment by GM-Alex** [comment]
@It75 Which theme are you using?

**Comment by krangownik** [comment]
Hi,
I have problem with menu too.
Main menu bar on my page is missing. When I am logged in it is visible but for non logged in users it is missing.
I am using Generate Press theme, but it is probably not a problem with theme because I downloaded two other random themes and for both menu is missing too. When I turn of UAM plugin menu is back. I tried to downgrade UAM to older version and error is the same. So this is something between UAM and Wordpress 4.9.

Let me know if you need more information.

**Comment by GM-Alex** [comment]
Could you guys test with a new menu that uses static elements, not restricted content and so on that we can tear down what causes the issue because for my test environment it works at it should.

**Comment by krangownik** [comment]
Yep,
I created new menu with only one entry to not restricted page and for logged in works ok for non logged its missing.

One entry logged in
![1](https://user-images.githubusercontent.com/8676206/32989858-dbb58fe6-cd1e-11e7-9fcc-80cf1ffe5005.png)

No menu bar for non logged in
![2](https://user-images.githubusercontent.com/8676206/32989865-f057083a-cd1e-11e7-8f9e-e4e52466034b.png)

**Comment by krangownik** [comment]
And when I turn off UAM widget that new test menu is visible everywhere without issue.

**Comment by krangownik** [comment]
My server is Nginx, PHP version is 7 and database is Maria. Probably with Wordpress version 4.8 it will work. I just know that my theme provider also had to update theme code because after update to Wordpress 4.9 they had a problem with missing menu too.

**Comment by GM-Alex** [comment]
Could you create me an admin user and grant me ftp access to your page (best would be a Dev environment)? My mail is alexanderschneider85@gmail.com

**Comment by krangownik** [comment]
I am afraid I can't :( maybe some other user can do this. I know this would speed things up but my server is located in Tor network and as you can understand it's location is a secret.

**Comment by iacsaragon** [comment]
Hi, I am using Divi Theme. We are trying to make it work in another environment just in case it was a problem with our own configuration. I will keep you informed.

**Comment by apriloneil** [comment]
Same problem here.
I reset settings in Menu->Setup then menu was ok. So I added new group and set permission for few pages and categories and then menu dissapeared. In my menu I have one page witch is restricted and menu also contains link to restricted category. Maybe category in menu is a problem?

**Comment by GM-Alex** [comment]
@apriloneil Also categories work for me. Are you using the default theme? If not could you try that? Could you give me a detailed description how your menu looks and what items you did restrict? For example

- A (Post, not restricted)
-- B (Post, not restricted)
-- C  (Post, restricted)
-D (Category, not restricted)

**Comment by apriloneil** [comment]
- Page - not restricted
- Placeholder (empty link)
-- Page - not restricted
-- **Category - restricted**
-- **Page - restricted**
-- Page - not restricted
- Page - not restricted
- Placeholder (empty link)
-- Page - not restricted
-- Category - not restricted

Default Wordpress theme.

**Comment by GM-Alex** [comment]
@apriloneil Great (shouldn't be great but now I can fix it) that works. :)

**Comment by apriloneil** [comment]
You know what, I disabled plugin https://wordpress.org/plugins/ultimate-category-excluder/ and looks everything works fine. The category in my menu was excluded from main page with this plugin. Holy moly! Sorry for the problem.

**Comment by GM-Alex** [comment]
@apriloneil I was wrong, it still works, I forgot to assign the new menu...

**Comment by apriloneil** [comment]
Because it should :) take a look at my comment above!

**Comment by iacsaragon** [comment]
Same for me. I also disabled plugin ultimate-category-excluder and it works.

**Comment by GM-Alex** [comment]
Ok seems to be related to ultimate-category-excluder, I will close this one.

**Comment by muxip** [comment]
I don't have ultimate-category-excluder but same problem
