### ISSUE TITLE
Posts removed from WP_Query results in Ajax requests for unprivileged users

### ISSUE THREAD

**Issue by lilaeamedia** [GM-Alex/user-access-manager#176]
There are points where the code is bypassing controls when is_admin() is true. Since all asyncronous calls are passed through admin-ajax.php, the flag is set even for front-end request.

In several cases WP_Query results are being filtered for unpriviledged users when DOING_AJAX is defined.

I have identified the points in the code to fix this temporarily, but a permanent solution should be implemented in the stable production code that conforms to the broader framework.

**WordpressConfig::atAdminPanel line 65** 

```
    public function atAdminPanel()
    {
        if ( defined( 'DOING_AJAX' ) && DOING_AJAX && ! empty( $_REQUEST['action'] ) ) {
            return FALSE;
        }
        return $this->wordpress->isAdmin();
    }

```

**AccessHandler::checkObjectAccess line 160** 

 ```
       if ( defined( 'DOING_AJAX' ) && DOING_AJAX && ! empty( $_REQUEST['action'] ) ) {
            $admin = 'noAdmin';
       } else {
            $admin = $this->wordpress->isAdmin() === true ? 'admin' : 'noAdmin';
       }
```

**AccessHandler::getNoneHiddenPostTypes line 245** 

```
 if ($this->wordpress->isAdmin() === false
               || ( ( defined( 'DOING_AJAX' ) && DOING_AJAX ) && ! empty( $_REQUEST['action'] ) ) 
               ) {

```

**Comment by GM-Alex** [comment]
I found an article about your problem [https://facetwp.com/is_admin-and-ajax-in-wordpress/](https://facetwp.com/is_admin-and-ajax-in-wordpress/), but what if you are doing ajax request from an admin page? It will return false instead of true what shouldn't be the case...

**Comment by lilaeamedia** [comment]
That does not matter, because the action is either wp_ajax or wp_ajax_priv. With ajax calls, the code should not care if it is in the front or back end, only the capability of the user.


Jason C Fleming
Senior Lead Developer
solutions@lilaeamedia.com
910 550 8109

**Comment by lilaeamedia** [comment]
To put this in context, try using UAM with “The Event Calendar.” You will see that any request using the navigation controls (which call via Ajax) do not return any posts for unprivileged users.

By checking for DOING_AJAX, the code treats the request as a “front-end” request so all of the normal capability checks will still apply (assuming that is being handled appropriately).

Jason C Fleming
Senior Lead Developer
solutions@lilaeamedia.com
910 550 8109

**Comment by GM-Alex** [comment]
It matters because the function is also wrong than it's now. Changing that will also create edge cases where this will break something, because you cannot trust this function. But good news I made a function which should work properly:

```
function saveIsAdmin() {
    //Ajax request are always identified as administrative interface page
    //so let's check if we are calling the data for the frontend or backend
    if (wp_doing_ajax() === true) {
        $adminUrl = get_admin_url();
        //If the referer is an admin url we are requesting the data for the backend
        return (substr($_SERVER['HTTP_REFERER'], 0, strlen($adminUrl)) === $adminUrl);
    }

    //No ajax request just use the normal function
    return is_admin();
}
```

Would be nice if you could test it, too.

**Comment by lilaeamedia** [comment]
Got it.

So to be clear, we are replacing all instances of $this->wordpress->isAdmin() with $this->wordpress->saveIsAdmin() and removing the conditions I wrote, correct?


Jason C Fleming
Senior Lead Developer
solutions@lilaeamedia.com
910 550 8109

**Comment by GM-Alex** [comment]
Just use the next branch version, that contains the fix.

**Comment by lilaeamedia** [comment]
So far all tests are working correctly.

  - calendar navigation from front end (Ajax)
  - edit list from admin, all post types
  - edit post from admin, all post types
  - edit post from front-end, all post types

Jason C Fleming
Senior Lead Developer
solutions@lilaeamedia.com
910 550 8109
