### ISSUE TITLE
UAM last update

### ISSUE THREAD

**Issue by lt75** [GM-Alex/user-access-manager#177]
Hi,
SInce I updated UAM to v2.1.9, my website is partly hidden to visitors.
Sidebars and footer are hidden, they appear again when I log in  as administrator.

They contain widgets that are not supposed to be hidden. 

Is there a new option that I have to check to get those parts of my website appear again to everyone

Thanks !

**Comment by GM-Alex** [comment]
There is a new option called `Hide edit link on no access` at `UAM > Settings > Other settings`. Maybe that causes the issue.

**Comment by lt75** [comment]
Thanks for your quick answer.
It actually wasn't "hide edit link" that caused the issue but (in my french version) : "blocage permanent"
the first option in UAM > Settings > Other settings.

Problem solved :)

**Comment by lt75** [comment]
No !! 
Other big issue !

All my articles had a specific autorisation. All these autorisations have been removed !!!
(unchecked in the article edit page)
Everyone has free access to these articles !

What happened ?!

**Comment by GM-Alex** [comment]
Reactivate the "blocage permanent" that means "lock recursive" and inherits the access from categories to post and so on.

**Comment by lt75** [comment]
ok
So my problem is not solved without creating another one....

I reactivated "blocage permanent", autorisations are ok now

But my website is a mess just as mentionned in my first post...
no sidebars and footers....

"Hide edit link on no access" doesn't change anything

**Comment by GM-Alex** [comment]
Could you downgrade to 2.1.8 and test if every think works?

**Comment by lt75** [comment]
ok
Where can I find v2.1.8 install files ?

**Comment by GM-Alex** [comment]
https://downloads.wordpress.org/plugin/user-access-manager.2.1.8.zip But first check if it works with the default template. Could be the same like #175

**Comment by lt75** [comment]
to downgrade to 2.1.8, I have to uninstall UAM 2.1.9 first, or there is an install failure
Isn't it going to remove all my UAM settings and autorisations ??

**Comment by GM-Alex** [comment]
Just replace the plugin folder. There wasn't any database change so it should be save.

**Comment by lt75** [comment]
Thanks for your responses and for your time.

but ok...
it doesn't work better with the previous version of UAM....
I don't understand.
When I unactivate UAM, the website works fine. Everything is displayed as it should be.
When I activate UAM it's not working anymore...

It might be because of the template.... but it doesn't help. I can't change it , the whole website wouldn't make any sense anymore...

Maybe I should downgrade wordpress to previous version

**Comment by lt75** [comment]
Ok
Problem solved
I downgraded Wordpress to 4.8
Updated to the latest version of UAM
And it works fine !

I'll wait for an update of my template before updating to wordpress 4.9

**Comment by GM-Alex** [comment]
Would be nice if we can continue at #175 because this one seems to be a duplicate. I will close this one.
