### ISSUE TITLE
Catchable fatal error in UserAccessManagerNextGenGalleryExtension

### ISSUE THREAD

**Issue by bernhardwacker** [GM-Alex/user-access-manager#178]
Das Plugin User Access Manager - NextGEN Gallery Extension laesst sich nicht aktivieren. Die Fehler meldung lautet: 

Catchable fatal error: Argument 5 passed to UserAccessManagerNextGenGallery\Controller\FrontendController::__construct() must be an instance of UserAccessManager\AccessHandler\AccessHandler, instance of UserAccessManager\Access\AccessHandler given, called in .../wordpress/wp-content/plugins/user-access-manager-nextgen-gallery-extension/user-access-manager-nextgen-gallery-extension.php on line 118 and defined in .../wordpress/wp-content/plugins/user-access-manager-nextgen-gallery-extension/src/UserAccessManagerNextGenGallery/Controller/FrontendController.php on line 41

Gibt es einen Bugfix oder Workaround?

**Comment by GM-Alex** [comment]
Das Plugin Plugin User Access Manager - NextGEN Gallery Extension ist nur bis Version 2.0.13 kompatibel. Ob und wann ich das Plugin weiter entwickle kann ich aktuell nicht sagen.
