### ISSUE TITLE
Hide Product Pages for WooCommerce

### ISSUE THREAD

**Issue by ImOnMars** [GM-Alex/user-access-manager#18]
**Note:** The original issue was brought up [here](https://wordpress.org/support/topic/hide-all-product-pages-for-woocommerce-using-uam/#post-8839565).

As the title says, it would be helpful if UAM added the ability to restrict access for WooCommerce product pages, as well as things like category pages, etc.

**Comment by ImOnMars** [comment]
**Update:** It actually seems to work in some way, but it goes to the 404 page for me, which is arguably okay.

**Comment by GM-Alex** [comment]
2.0.0 will have all settings known form pages and posts for custom post types, including WooCommerce product pages.
