### ISSUE TITLE
Function uamIsUserInGroup failing

### ISSUE THREAD

**Issue by aeneareid** [GM-Alex/user-access-manager#182]
For some time, I have been using the function uamIsUserInGroup as described in the Wordpress support forum https://wordpress.org/support/topic/how-to-tell-if-the-logged-in-user-is-in-a-group/

Recently (probably at update to v 2.1.8 but not sure of this) it stopped working with the following fatal error
  Call to undefined method UserAccessManager\Access\AccessHandler::getUserGroupsForObject() 

Following that up, I found the code at 
   https://github.com/GM-Alex/user-access-manager/wiki/Code-Snippets
was different from that posted on the support forum so I tried that instead.

However, that also failed, this time with the error message
  PHP Fatal error: Class 'objectHandler' not found

I have managed to fix it by changing the line
  $userGroupsForUser = $userGroupHandler->getUserGroupsForObject(ObjectHandler::GENERAL_USER_OBJECT_TYPE, $userId);

back to
  $userGroupsForUser = $userGroupHandler->getUserGroupsForObject('_user_', $userId);

Is this a sensible correction?

**Comment by GM-Alex** [comment]
Nope is also fine. To use `ObjectHandler::GENERAL_USER_OBJECT_TYPE` you have to import the full namespace or alternatively `\UserAccessManager\Object\ObjectHandler::GENERAL_USER_OBJECT_TYPE` to would be the cleanest solution in your case. I updated the wiki page too.
