### ISSUE TITLE
Fatal error class PHP not found

### ISSUE THREAD

**Issue by Nirzol** [GM-Alex/user-access-manager#183]
Hello
I get this error when I update the plugin can you help plz ?

PHP Fatal error: Uncaught Error: Class ‘UserAccessManager\\Wrapper\\Php’ not found in /…/wp-content/plugins/user-access-manager/init.php:38\nStack trace:\n#0 /…/wp-content/plugins/user-access-manager/user-access-manager.php(75): initUserAccessManger()\n#1 /…/wp-settings.php(305): include_once(‘/…/…’)\n#2 /var/www/infos/wp-config.php(124): require_once(‘/…/…’)\n#3 /…/wp-load.php(37): require_once(‘/…/…’)\n#4 /…/wp-blog-header.php(13): require_once(‘/…/…’)\n#5 /…/index.php(17): require(‘/…/…’)\n#6 {main}\n thrown in /…/wp-content/plugins/user-access-manager/init.php on line 38

**Comment by GM-Alex** [comment]
I would need FTP access and a valid admin backend user to your blog. Would that possible?

**Comment by Nirzol** [comment]
Sorry I can't give access to the server and backend wordpress. But if you tell what to look I can.
Thanks

**Comment by GM-Alex** [comment]
Can you debug the code?

**Comment by Nirzol** [comment]
Yes, if you mean put some var_dump where it stop into wrapper/php class ?

**Comment by GM-Alex** [comment]
Did you download the plugin directly from github or via the backend? If you did it via github go the plugin dir and run composer install if not try to debug the autoloader at `PLUGIN_DIR/vendor/composer/autoload_real.php`. You have to figure out if he is searching for the calls and which path the autoloader is using.

**Comment by Nirzol** [comment]
Via Backend. But I can install GitHub version and run composer install

**Comment by GM-Alex** [comment]
No that's fine, just debug the autoloader.

**Comment by Nirzol** [comment]
Sorry I got something to do last time.
What I have to do to debug the autoloader ?

**Comment by GM-Alex** [comment]
Start debugging at `vendor/composer/ClassLoader.php` method `loadClass`, we need to know which classes aren't found and where the auto loader is locking for the file.

**Comment by Nirzol** [comment]
ok i will try

**Comment by Nirzol** [comment]
Hey! I run composer dump-autoload -o  to re-generate autoload class. And it works 
My web site going well .
But in error.log get : 

[Wed Nov 22 10:30:09.460754 2017] [:error] [pid 19311] [client 172.20.143.128:57677] Erreur de la base de donn\xc3\xa9es WordPress Unknown column 'from_date' in 'field list' pour la requ\xc3\xaate SELECT object_id AS id, object_type AS objectType, from_date AS fromDate, to_date AS toDate\n                FROM prefix_3_uam_accessgroup_to_object\n                WHERE group_id = '1'\n                  AND group_type = 'UserGroup'\n                  AND object_id != ''\n                  AND (general_object_type = '_term_' OR object_type = '_term_') AND (from_date IS NULL OR from_date <= '2017-11-22 10:30:09') AND (to_date IS NULL OR to_date >= '2017-11-22 10:30:09') faite par require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Featured_Content::wp_loaded, get_term_by, get_terms, WP_Term_Query->query, WP_Term_Query->get_terms, apply_filters('get_terms_args'), WP_Hook->apply_filters, UserAccessManager\\Controller\\Frontend\\TermController->getTermArguments, UserAccessManager\\Access\\AccessHandler->getExcludedTerms, UserAccessManager\\Access\\AccessHandler->getExcludedObjects, UserAccessManager\\UserGroup\\AbstractUserGroup->getAssignedObjectsByType, UserAccessManager\\ObjectMembership\\TermMembershipHandler->getFullObjects, UserAccessManager\\ObjectMembership\\ObjectMembershipWithMapHandler->getFullObjectsByMap, UserAccessManager\\ObjectMembership\\ObjectMembershipHandler->getSimpleAssignedObjects, UserAccessManager\\UserGroup\\AbstractUserGroup->getAssignedObjects, UserAccessManager\\Database\\Database->getResults

**Comment by Nirzol** [comment]
Ok Finally I use your tool to repair database !! And it works like a charm !
Thanks ! But I don't know why I need to re-generate autoload class with dump-autoload.... weird isn't it ?

**Comment by GM-Alex** [comment]
Could you test if it fails if you do it without the -o flag?

**Comment by Nirzol** [comment]
I try nothing change
optimized or not still working now !

**Comment by GM-Alex** [comment]
Super strange...

**Comment by GM-Alex** [comment]
I added the fix at the [troubleshoot page](https://github.com/GM-Alex/user-access-manager/wiki/Troubleshoot).
