### ISSUE TITLE
How to access user group

### ISSUE THREAD

**Issue by Dostoi** [GM-Alex/user-access-manager#184]
Hi,

I'm trying to create a simple widget for my site and I'd like to access the group of my users to change the outcome depending on the group they're in. I'm new to wordpres dev so I'm struggling to find how to access the group of my user ^^
I though that I might find it in it's meta data but no, I also tried looking into your code but I didn't find it either. Could you tell me how I could know the group of an user (or if it's not possible from outside your plugin) ?

Thanks :)

**Comment by GM-Alex** [comment]
I'm sorry but this is not the right place to discuss how to develop a wordpress widget.

**Comment by Dostoi** [comment]
Yes I know sorry, I didn't know where else to ask you this. I was just hopping that you could point me to the best way to access an user group (as it is your plugin data) but I think I've found a way.
Sorry for the inconvenience
