### ISSUE TITLE
Broken site – “Error in SQL syntax”

### ISSUE THREAD

**Issue by whale74** [GM-Alex/user-access-manager#185]
My site (www.eltviller-carneval-verein.de) is obviously broken since some time. I’ve narrowed it down to the UAM plugin. Navigation menues aren’t showing and the page shows several database errors like this:

>     WordPress-Datenbank-Fehler: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘,225) ) ) AND cjxw3i2yh_posts.post_type = ‘nav_menu_item’ AND ((cjxw3i2yh_pos’ at line 5]
>     SELECT cjxw3i2yh_posts.* FROM cjxw3i2yh_posts WHERE 1=1 AND cjxw3i2yh_posts.ID IN (136,3843,4346) AND ( cjxw3i2yh_posts.ID NOT IN ( SELECT object_id FROM cjxw3i2yh_term_relationships WHERE term_taxonomy_id IN (6,,,225) ) ) AND cjxw3i2yh_posts.post_type = ‘nav_menu_item’ AND ((cjxw3i2yh_posts.post_status = ‘publish’)) GROUP BY cjxw3i2yh_posts.ID ORDER BY cjxw3i2yh_posts.menu_order ASC 

As soon as a user logs in, the site works as expected, errors also vanish if I deactivate the UAM plugin.

**Comment by GM-Alex** [comment]
Could you grant me access to your page (FTP and wordpress admin user)?

**Comment by whale74** [comment]
If this is really necessary... How can I provide the credentials?

**Comment by GM-Alex** [comment]
The query isn't part of wordpress or the user access manager as I can see, so if you are afraid of giving me access let's first try the following. Disable all other plugins expect the user access manager and see if it works. Please use the latest version of the user access manager.

**Comment by whale74** [comment]
Okay, did that and narrowed it further down: It is a conflict between UAM and the plugin Ultimate Category Excluder which I am using to exclude certain blog categories from showing on the front page.
As soon as I exclude a category, which is only accessible for logged in users through UAM, I get the SQL error unless I log in:
<img width="808" alt="ultimate-category-excluder" src="https://user-images.githubusercontent.com/33929867/33189289-8f8e42da-d0a1-11e7-80be-b923a6293f3c.png">
<img width="1351" alt="kategorien" src="https://user-images.githubusercontent.com/33929867/33189330-ee13e076-d0a1-11e7-8dfb-49ac7d169a39.png">
As long as I only exclude categories which have full access, the site is working as expected.
This is a workaround I can live with for now.

Thanks,
Markus

**Comment by GM-Alex** [comment]
Ticket and patch for WordPress is created. That should fix the issue if WordPress merges the changes. See https://core.trac.wordpress.org/ticket/42691
