### ISSUE TITLE
Add usergroups to New User-form

### ISSUE THREAD

**Issue by davidvandiepen** [GM-Alex/user-access-manager#189]
At the moment, you can only set a Usergroup for a User in the User Edit-form. It would be nice if there would also be an option to set the Usergroup in the New User-form

Like adding something like this (functions have to be written yet): 
add_action('user_new_form', array($oUserAccessManager, 'showUserRoles'));
add_action('user_register', array($oUserAccessManager, 'saveNewUserData'));

**Comment by GM-Alex** [comment]
They are already existing, see attached screen: 
![image](https://user-images.githubusercontent.com/1454864/33650576-e6c66ae4-da62-11e7-86a6-5e324e672bf2.png)

**Comment by davidvandiepen** [comment]
Ah, with the new update it is! nice!
