### ISSUE TITLE
Does not work correctly with custom post types

### ISSUE THREAD

**Issue by oobm** [GM-Alex/user-access-manager#19]
Hi!

I use plugins “The Events Calendar” and “WordPress FAQ Manager”. I set them the necessary rights of access. Then I create a regular post. And the right to access these plug-ins are reset!

See these screenshots:
1) I set rules. https://s30.postimg.org/p9oxa8t4x/image.png
2) All is well! https://s30.postimg.org/uz55ujzb5/image.png
3) Create and publish the post. https://s30.postimg.org/vpxw0c1oh/image.png
4) I go back to the FAQ …: – (((( https://s30.postimg.org/5vo3ak1oh/image.png
>>> I realized that it was due to some other plugin … But I do not understand what it is plugin.

>>> Oh! Something has changed … Now plug “WordPress FAQ Manager” is operating normally, but the plugin “The Events Calendar” still…

>>> I really do not understand anything…

>>> I do not believe that this could be! So I recorded the video https://youtu.be/vGGt4HPztZU . While I suspect that the problem in the plugin “Shortcodes Ultimate” (https://wordpress.org/plugins/shortcodes-ultimate/).

**Comment by GM-Alex** [comment]
Seems to work for me now.
