### ISSUE TITLE
IP range not working attached to Group

### ISSUE THREAD

**Issue by jab-au** [GM-Alex/user-access-manager#195]
I have identified an issue where in a group I have defined as being in our private local subnet the users are still blocked.

User group name: Local Network Only
IP range: 192.168.0.1-192.168.255.254 (I have tried a smaller subnet also 192.168.39.1-192.168.39.254)
Read access: Only Group Users
Write access: All Users
Role affiliation: None selected
Version installed 2.1.9

Objective was to allow only people access to the page if they are in the local subnet but still allow logged in users to access the page. This had previously worked.

Single IP address do work however.

Can anyone give me some tips on what might be wrong or if this is a bug in the range process.

**Comment by GM-Alex** [comment]
Could you please check if your server is using IPV6, if yes try IPV6 ranges.

**Comment by jab-au** [comment]
IPv6 is turned off on the server in question

**Comment by GM-Alex** [comment]
I'm not able to reproduce the issue, works for me like expected. Maybe `$_SERVER['HTTP_X_REAL_IP']` is set with a wrong IP? Could you also give me an IP which doesn't work with the range `192.168.0.1-192.168.255.254`, than I will test with this one.

**Comment by GM-Alex** [comment]
I did the following unit test

```php
$currentIp = [192, 168, 0, 1];

while (implode('.', $currentIp) !== '192.168.255.255') {
    self::assertTrue($userHandler->isIpInRange(implode('.', $currentIp), ['192.168.0.1-192.168.255.254']));
    echo implode('.', $currentIp).PHP_EOL;

    if ($currentIp[3] < 255) {
        $currentIp[3]++;
    } else {
        $currentIp[2]++;
        $currentIp[3] = 0;
    }
}
``` 

The IPs which are tested and true are the following (shorten):

192.168.0.1
192.168.0.2
...
192.168.0.254
192.168.0.255
192.168.1.0
192.168.1.1
...
192.168.1.254
192.168.1.255
...
192.168.253.255
192.168.254.0
192.168.254.1
...
192.168.254.254
192.168.254.255
192.168.255.0
192.168.255.1
...
192.168.255.253
192.168.255.254

So everything seems to work for me. If you have more information I will reopen this issue.

**Comment by jab-au** [comment]
I have identified the issue, $_SERVER['HTTP_X_REAL_IP'] is not valid in PHP versions prior to version 7.

It's not a bug in the plugin.
