### ISSUE TITLE
Request : Redirect after login

### ISSUE THREAD

**Issue by rjxeon** [GM-Alex/user-access-manager#197]
Hi @GM-Alex,

Love your plugin! Was wondering if it's possible to add in a way to redirect to a certain page after login? rather than staying on the current page you logged in on.

Much appreciated

Ryan

**Comment by GM-Alex** [comment]
Hey @rjxeon,

this feature comes with the latest version, just choose `To login page (wp-admin)` at the redirect options.

**Comment by rjxeon** [comment]
Hi @GM-Alex, thanks for the fast reply. It's once they have hit login I wanted it to take them to a certain url such as they first visit the home page. Login then are directed to a different pages such as /courses. 

Is this possible? The only settings I can find are to redirect them to the login page or another page if they are NOT logged in.

Many thanks
Ryan
