### ISSUE TITLE
Fatal Error memory size exhausted 

### ISSUE THREAD

**Issue by skiank** [GM-Alex/user-access-manager#199]
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in ..../wp-content/plugins/user-access-manager/src/Object/ObjectMapHandler.php on line 101

Version  2.1.10 on WP 4.9.1

The error happened on any pages  after a bbPress forum import with many posts (about 100.000)

**Comment by GM-Alex** [comment]
You need to increase your memory limit for PHP. See for example the WooCommerce documentation: https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/ 

I would suggest using the php.ini method.

**Comment by mbautista** [comment]
Hello,
Thank you for your plugin, it rocks :)

Unfortunately we have the same issue of "Allowed memory" with our dedicated config :
PHP : 7.4
WordPress : 5.7.1
UAM : 2.2.15
Memory limit : 3 GB (whatever the value we set, the program still needs more memory...)
Wp posts : we have a network with 3 sites and few millions of posts for each.

The problem showed up after upgrading UAM from 1.2.7.1 to 2.2.15 (We did not upgrade this website for a long time...)

The error is on `user-access-manager/src/Object/ObjectMapHandler.php on line 92` where there is a recursive function. 

As far as I understand the plugins tries to read all posts and make a map. If so I think this behaviour is not good for large websites. In our case, the millions of posts are custom post types and we don't need UAM for these types of post (we only use it for pages). I couldn't find a setting to disable UAM for some post types, or did I miss something ?

For now we had to roll back to the last version of UAM we used before upgrading : 1.2.7.1 (old version but it works...)

Do you have a hint to fix this ?

Thank you for your help.
Mathieu.

**Comment by GM-Alex** [comment]
The best would to get a dump of your database. With this I could see how to optimize the code or how we could find a way for your site.

**Comment by mbautista** [comment]
Sorry but this database contains sensitive data of our customer, I can't send it :/ Besides the db itself weights about 500MB...
I think a good thing we be to have a hook / filter or option to we can exclude some post types for the map.
