### ISSUE TITLE
Styles and Scripts wp_print_scripts/wp_print_styles vs. admin_enqueue_scripts

### ISSUE THREAD

**Issue by nwoetzel** [GM-Alex/user-access-manager#2]
currently, the styles ("css/uamAdmin.css","css/uamLoginForm.css") and the javascript ('js/functions.js') are registered using the action hooks in user-access-manager.php
<pre>
        add_action('wp_print_scripts', array($oUserAccessManager, 'addScripts'));
        add_action('wp_print_styles', array($oUserAccessManager, 'addStyles'));
</pre>
but the "css/uamAdmin.css" and 'js/functions.js' is only required in the admin dashboard, as far as I can tell. For that the 'admin_enqueue_scripts' action hook is the preferred way.
I would like to suggest some changes, so that it is only loaded for the dashboard ("css/uamAdmin.css"), and only for the actual plugin page ('js/functions.js').
I am not sure where the "css/uamLoginForm.css" comes into play? Is this relevant for a view where the user is not logged in?
Also the version was not increased after recent changes to the "css/uamAdmin.css". But this is required to bust the cache - so I would suggest using the '$_sUamVersion' variable instead of '1.0'.
Would you like a pull-request for that, or do you prefer working on this yourself.
Thanks

**Comment by GM-Alex** [comment]
I'm happy if you help, so if you have time, go ahead.

**Comment by GM-Alex** [comment]
See https://github.com/GM-Alex/user-access-manager/pull/3. Thanks for the PR!
