### ISSUE TITLE
User groups not assignable after updates

### ISSUE THREAD

**Issue by kaytino** [GM-Alex/user-access-manager#20]
I can’t unmark the checkboxes in the page or post. Previously it worked fine but I can’t say exactly after which update the problem occured.

I tried this, but this does not fix my problem:
https://wordpress.org/support/topic/user-groups-not-assignable-after-updates/

I’m using WordPress 4.7.2 and UAM 1.2.14

My Problem: I want to deselect groups like in the picture on the right, so everybody has access.

Screenshots of everything you can find here:
https://wordpress.org/support/topic/user-groups-not-assignable-after-updates-2/#post-8839562

**Comment by garethmcraig** [comment]
Also having this issue!

When creating a fresh post it is automatically ticking group restrictions when you publish, despite nothing being selected, and they cannot be cleared even though it’s intended to be a public post

**Comment by GM-Alex** [comment]
Closed because the [LR] is the recursive locking feature. See post comment from @garethmcraig
