### ISSUE TITLE
Identifying user group

### ISSUE THREAD

**Issue by bintrybill** [GM-Alex/user-access-manager#201]
Hi Alex, 
I've just installed user access manager and it all seems fine, except that I think I must be missing something. Is inserting each individual group member's IP address really the only way to identify users in a group? Surely there must be some form of login capability on the private sections?

Thanks,
Bill

**Comment by GM-Alex** [comment]
You can assign user to the UAM groups at the user edit form, using the IP is only a feature to allow access to users which are coming from an internal network, where you allow everyone from that network access.
