### ISSUE TITLE
"[L]" snippet in every post and site title

### ISSUE THREAD

**Issue by faekataucher** [GM-Alex/user-access-manager#202]
Hello, i have a issue with every post and site title which has a permission. 
For these contents the snippet "[L]" appears (see photo). Is there anything to avoid that?
<img width="873" alt="bildschirmfoto 2018-01-03 um 16 38 51" src="https://user-images.githubusercontent.com/35071724/34527165-fce2ffa6-f0a4-11e7-864e-36d458ebc041.png">

**Comment by GM-Alex** [comment]
See https://github.com/GM-Alex/user-access-manager/wiki/FAQ
