### ISSUE TITLE
Php 7 compatibility 

### ISSUE THREAD

**Issue by AkademiaDev** [GM-Alex/user-access-manager#206]
Good day

I was wondering if you could perhaps make the plugin compatible with php 7?

I found the following compatibility issues:
user-access-manager/src/Object/ObjectHandler.php
15 | ERROR | 'object' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

user-access-manager/src/Object/ObjectMapHandler.php
 15 | ERROR | 'object' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)

Any feedback would be appreciated.

Kind regards

**Comment by GM-Alex** [comment]
Hi,

as you can see here https://travis-ci.org/GM-Alex/user-access-manager the unit tests are running under PHP 7 and also my test env uses PHP 7.1, so it's fully PHP 7 compatible. Seems your version is somehow corrupt. Please redownload the plugin and replace all files with the downloaded one.
