### ISSUE TITLE
media element url includes references to the uam plugin

### ISSUE THREAD

**Issue by bunglegrind** [GM-Alex/user-access-manager#207]
If I upload a new file in the media library whose type I've blocked using uam, the url that appears in its details is very long and includes substrings related to uam:

http://localhost/?uamfiletype=attachment&uamgetfile=http://localhost/web/wp-content/uploads/2018/01/document17.pdf

I would like to know if uam can be configured in order to show in the url field only the path to the resource, e.g.:

http://localhost/web/wp-content/uploads/2018/01/document17.pdf

For sake of completeness, I've enabled permalink on my installation.

Thanks in advance.

**Comment by GM-Alex** [comment]
It seems that mod rewrite isn't enabled could that be?

**Comment by bunglegrind** [comment]
No, it's enabled. But I'll try tomorrow with a fresh install. I will let you know.

**Comment by bunglegrind** [comment]
On my development environment:

wamp64 - apache mod_rewrite enabled
php 7.0.10
wordpress 4.9.2
only UAM 2.1.10 installed
permalink enabled
UAM block file (type "pdf) enabled

Still appearing on the media url...

**Comment by bunglegrind** [comment]
btw,  2.0.13 is not affected.

**Comment by GM-Alex** [comment]
Could you test what the function got_mod_rewrite returns? I think that could be the issue, because I use this method now to detect if mod rewrite is enabled.

**Comment by bunglegrind** [comment]
it returns true.

**Comment by GM-Alex** [comment]
Super strange, this one replaces the logic with the permalinks. Could you change the function `gotModRewrite` at the `Wordpress` class (`/wp-content/plugins/user-access-manager/src/Wrapper/Wordpress.php`) to 

```
public function gotModRewrite()
{
    return true;
}
```

And test again. Thanks a lot.

**Comment by bunglegrind** [comment]
Nothing changes. Still appearing uamgetfile etc... in the url.

btw, the condition in the function getFileUrl($url, $id) in RedirectController.php it looks strange...

`if ($this->mainConfig->lockFile() === true
            && ($this->wordpress->isNginx() === false || $this->wordpress->gotModRewrite() === false)`

The second element of the AND statement is always true since I'm using Apache.

**Comment by bunglegrind** [comment]
Probably I found the issue...but I'm not 100% since I don't know UAM internals...

Substitute line 403 in RedirectController.php with 

` if (( $lockedFileTypes === 'all' || in_array($type, $fileTypes) === true)&& ($this->wordpress->gotModRewrite() === false)) {`

**Comment by bunglegrind** [comment]
Hi Alex,
did you have any free time to look at the solution above?

Cheers

**Comment by GM-Alex** [comment]
Sorry for the delay took me some time. Will be fixed with the next version.

**Comment by bunglegrind** [comment]
Thanks! I will let you know the patch is fixing this issue.

**Comment by bunglegrind** [comment]
I confirm. Thanks a lot!!!
