### ISSUE TITLE
Write - group only, not working

### ISSUE THREAD

**Issue by xtrim2000** [GM-Alex/user-access-manager#209]
Noticed possible bug, users from the same group cannot edit posts associated with the same group.
Group settings: Read - for all users, Write - for group only.
If the user is not the author of the post I can see in the Dashboard "View" only, edit is not an option.
Read access working as expected. Wordpress version 4.9.2.

**Comment by GM-Alex** [comment]
Works for me as expected. Could it be that the user isn't at least an editor?

**Comment by xtrim2000** [comment]
Hi Alex, all works. Thank you. 
I gave them Author role and thought their permissions will be escalated to the group posts.
Editor role I thought will be site wide. 
Now all works! Sorry for the inconvenience.
