### ISSUE TITLE
huge loss of pagespeed

### ISSUE THREAD

**Issue by j3ll3yfi5h** [GM-Alex/user-access-manager#21]
I'm using your plugin to currently gain 678 people access to the content of a specific post type. The problem is, that there is also a huge loss of pagespeed on all other pages/posts...

I've done a test with the «[P3 (Plugin Performance Profiler)](https://de.wordpress.org/plugins/p3-profiler/)»; the difference between the activated UAM and the deactivated is 119 vs. 1415 MySQL Queries per visit (loadingtime about 150ms vs. 3s)... that's a lot and explains the loss.

Is there a way to use the plugin only on a specific post type? Hacking the plugin at some lines?

**Comment by GM-Alex** [comment]
If you have a test environment it would be nice if you could test the current test version (https://github.com/GM-Alex/user-access-manager/archive/next.zip), but be warnt this version is not stable and has some known issues. So only use it at your test environment and not in production. This version should be faster. Feedback would be great.

**Comment by j3ll3yfi5h** [comment]
Unfortunately I can't activate the plugin; I get the following message:

> Fatal error: Call to undefined function UserAccessManager\Wrapper\get_sites() in (...)/wp-content/plugins/user-access-manager-next/src/UserAccessManager/Wrapper/Wordpress.php on line 664

**Comment by GM-Alex** [comment]
You have to rename the folder to user-access-manager instead of user-access-manager-next.

**Comment by j3ll3yfi5h** [comment]
doesn't make any difference, still the same error...

**Comment by GM-Alex** [comment]
Please redownload the archive, I pushed a new version.

**Comment by j3ll3yfi5h** [comment]
> Fatal error: Call to undefined function get_sites() in (...)/wp-content/plugins/user-access-manager/src/UserAccessManager/Wrapper/Wordpress.php on line 666

**Comment by GM-Alex** [comment]
Which version of wordpress are you using? get_sites is a default wordpress function since 4.6.0, are you using a wordpress version below?

**Comment by j3ll3yfi5h** [comment]
No, it is up to date, I'm using WordPress 4.7.3...

**Comment by GM-Alex** [comment]
Are any other plugins active?

**Comment by j3ll3yfi5h** [comment]
Yes, there were some others, but I just deactivated all of them - still the same error... Any other ideas?

**Comment by GM-Alex** [comment]
Ok, please download the archive again.

**Comment by j3ll3yfi5h** [comment]
It's working now, and a lot faster! 👍 
(The 1415 MySQL Queries per visit went down to 332, well done!)

**Comment by GM-Alex** [comment]
Nice to hear, I think it will get a little faster if I'm completely done, there are some potential place where I could optimize the code.

**Comment by j3ll3yfi5h** [comment]
Hm... I think I found a bug: After updating the database to make the new version work all the posts lost their usergroups...
I hope that's not the reason why it's faster now... ;)

**Comment by GM-Alex** [comment]
I discovered yesterday a issue with the user groups shown at the backend. It is possible that a admin user doesn't see that a object is assigned to a user groups. Could you check the database if there are still assignments? If yes download the latest version from the next branch, that will fix the issue.

**Comment by GM-Alex** [comment]
Speed improved with 2.0.0
