### ISSUE TITLE
I want a code to show the number of members in each group

### ISSUE THREAD

**Issue by soou2** [GM-Alex/user-access-manager#210]
I want a code to show the number of members in each group

**Comment by soou2** [comment]
I will create a page and show the names of all the groups and the number of members involved in each group and I want to help with that

**Comment by GM-Alex** [comment]
Github is not the right place, for questions like that. The issues are for broken logic or feature requests, please use the WordPress support section.

**Comment by soou2** [comment]
I am talking about this plugin
How to get the number of members within a group

**Comment by GM-Alex** [comment]
Sure, I got that you are talking about this plugin... But the Github issue section is still the wrong place for your questions, please got to https://wordpress.org/support/plugin/user-access-manager
