### ISSUE TITLE
Users have access to all groups

### ISSUE THREAD

**Issue by nagytimeabirge** [GM-Alex/user-access-manager#211]
I created group1 (1. osztály) a while ago, everything was ok for months, and now I created group 2. (2. osztály) It was working fine with the first user I added, and then suddenly all users got access to all groups and I can't even change it manually. Do you have any idea, how to solve this problem?
![kep](https://user-images.githubusercontent.com/35916059/35501108-364aabd4-04d9-11e8-88f0-36c00788788d.png)

**Comment by bunglegrind** [comment]
Is this a post? Try to look at the categories permissions.

**Comment by nagytimeabirge** [comment]
I1Ve found the problem, it was with subscriptions. Thanks!

**Comment by GM-Alex** [comment]
Thanks for the feedback.
