### ISSUE TITLE
Plugin Update

### ISSUE THREAD

**Issue by luisfbmelo** [GM-Alex/user-access-manager#216]
Each time I update this plugin, I get a request to update the database, and when I do this, everything breaks.
I allways have to reset the User Access Manager and reconfigure all over again.

**Comment by Zeuster** [comment]
I have this same issue. I've updated the plugin, then it shows that my Db is in good condition, but when i go back to the plugins page, it tells me to update the DB .

How can we fix this?

**Comment by GM-Alex** [comment]
Could it be that you have a mutli site installation running? If so you need to do the update for all pages.

**Comment by Zeuster** [comment]
Hi Alex,

No multi site

**Comment by GM-Alex** [comment]
What if you trigger the update even if the db is in good condition?

**Comment by Zeuster** [comment]
Its still doing the same thing...After i update it, it says its successfully updated, then when i go back to the plugins page it asks me to update again..

**Comment by luisfbmelo** [comment]
I have a multisite, and what Zeuster said happened to me. When making the update, I go back and it request an update again...

**Comment by GM-Alex** [comment]
Could someone of you grant me access to the backend and access to the plugin file. Than I'm able to debug the issue.

**Comment by GM-Alex** [comment]
Seems to be the same like that issue: https://wordpress.org/support/topic/warning-does-not-disappear-after-updating-the-database-missing-user/#post-10084277
Next version with the repair function should fix it.
