### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by janeb0112** [GM-Alex/user-access-manager#217]
i feel like i am missing something. none of the links in the profile work...
my account
edit profile
contact
also the new password. some people cannot log in. i feel like i am really missing something here. do i need pages for these things or should those links work out of box?  reset password and register are not working. my site is locked down, so giving you a link won't work. 
![screenshot 79](https://user-images.githubusercontent.com/36489526/36227666-c7f4989c-119f-11e8-86d7-9560f881e123.png)

**Comment by GM-Alex** [comment]
Are you sure you got the right plugin? The User Access Manger doesn't provide such features. I think you are using a different plugin which has the same name. Could you provide me the link where you downloaded the plugin?
