### ISSUE TITLE
Back door?

### ISSUE THREAD

**Issue by coltding** [GM-Alex/user-access-manager#218]
I have a page protected by UAM.  The page is locked when using the domain URL.  When the site URL is used the page is accessible.  How do I fix this?

**Comment by GM-Alex** [comment]
What is the difference between the two urls? Are you having a multisite WordPress installation?

**Comment by coltding** [comment]
The site address assigned by the host and the domain URL pointing to the site address.  Using the domain URL/page the page is locked.  Using the site address/page the page is unprotected.

**Comment by GM-Alex** [comment]
To be honest I have currently only an idea of what you are talking. Could it be you are talking about the `Site Address (URL)` and `WordPress Address (URL)` (see https://codex.wordpress.org/Changing_The_Site_URL). If yes how do the two settings look like at your page?

**Comment by coltding** [comment]
Both addresses are the same  in settings/general as the domain name (i.e. https://xxxxxxxxx.org/page).  The other is where the files physically reside (i.e. http://s69xxxxxxx.onlinehome.us/page).  The former is protected; the latter is not.

**Comment by coltding** [comment]
By the way, There have been two successful attacks on this page.  The first occurred several months ago and the second yesterday.  Wordfence identifies both attacks as originating from the same source by a bot.

**Comment by GM-Alex** [comment]
I have no idea what how your setup looks like for me it seems that something isn't right with it. If content pages (posts/pages etc.) are controlled via the database and the wordpress users, so that should be impossibel. If you are talking about files existing on two different servers, which should managed by the UAM, that will not work with UAM.

**Comment by GM-Alex** [comment]
I will close. If you have additional information I will reopen it.
