### ISSUE TITLE
"Hide complete posts" doesn not work with custom post

### ISSUE THREAD

**Issue by Japhys** [GM-Alex/user-access-manager#22]
I am using a child of twenty twelve and resume builder plugin which uses a custom post type resume.

'Resume' in my nav menu is visible to anyone , and I only set it up for one specific user. All other users don't have access to the post so at leat that's good. But I don't even want them to be aware of the post, hence 'hidden'

On defauft posts and pages it works perfectly

Kind regards

**Comment by GM-Alex** [comment]
2.0.0 adds the same variety of settings like for post and page for custom post types.
