### ISSUE TITLE
Get all Users in each User Group

### ISSUE THREAD

**Issue by loretoparisi** [GM-Alex/user-access-manager#223]
I want to retrieve all users objects for each registered group, but I'm not sure I'm doing in the right way:

```php
global $userAccessManager;
		//use UserAccessManager\ObjectMembership\UserMembershipHandler;
		
		// get a reference to the UserGroupHandler
		$userGroupHandler = $userAccessManager->getUserGroupHandler();
		// get a reference to the UserMembershipHandler
		$objectType = \UserAccessManager\Object\ObjectHandler::GENERAL_USER_OBJECT_TYPE;
		$userMembershipHandler = $userAccessManager->getObjectMembershipHandler($objectType);

		// get all user groups
		$userGroups = $userGroupHandler->getUserGroups();
		if (count($userGroups) > 0) { // has user groups
			foreach ($userGroups as $userGroup) {
				// get all users in a group 
				// getFullObjects(AbstractUserGroup $userGroup, $lockRecursive, $objectType = null)
				$users = $userMembershipHandler->getFullObjects($userGroup, false);
				if (count($users) > 0) { // has users
					//@TODO:...
				}
			}
		}
```

I'm my understanding I get a reference to the `UserGroupHandler` so that I can grab the users groups calling `getUserGroups`. Then  I will take a reference to the `UserMembershipHandler` of type `ObjectMembershipHandler` passing an object type `GENERAL_USER_OBJECT_TYPE` to the `getObjectMembershipHandler` method of the global `$userAccessManager` instance. At that point, for each group I can call the `getFullObjects` passing the `$userGroup` in order to retrieve the users, but I'm not sure this is formally correct in the `UserAccessManager` API actually.

**Comment by loretoparisi** [comment]
**[UPDATE]**
I have tried to above code but I get an undefined method `getObjectMembershipHandler` error

```
Fatal error: Call to undefined method UserAccessManager\UserAccessManager::getObjectMembershipHandler() in /home/wp-content/plugins/uam-export/uam-export.php on line 307
```

**Comment by GM-Alex** [comment]
Use `$userAccessManager->getObjectHandler()->getObjectMembershipHandler()`.

**Comment by loretoparisi** [comment]
@GM-Alex thank you Alex!

**Comment by loretoparisi** [comment]
@GM-Alex sorry I'm not sure of the output of that:

```php
foreach ($userGroups as $userGroup) {
    $users = $userAccessManager->getObjectHandler()->getObjectMembershipHandler()->getFullObjects($userGroup, false);
}
```

and the `var_dump($users)` gives me back a list like

```
array(105) { [58]=> string(6) "_user_" [7]=> string(6) "_user_" [70]=> string(6) "_user_" [14]=> string(6) "_user_" [100]=> string(6)
```

I have missed something?
