### ISSUE TITLE
bbPress Topics hidden

### ISSUE THREAD

**Issue by fbrines** [GM-Alex/user-access-manager#23]
When creating a topic with bbPress, users non-admin can see correct number of posts in topics table, but they can't see topic (only replies) when entering in topic.

![uam1](https://cloud.githubusercontent.com/assets/13052032/23791149/3dbf718a-0582-11e7-998a-d6e9e1434546.jpg)
![uam2](https://cloud.githubusercontent.com/assets/13052032/23791163/48909ecc-0582-11e7-9a91-783ce67fd091.jpg)

**Comment by fbrines** [comment]
Hi, GM-Alex

What about this issue? Do you know when you could fix it?

Thanks!

**Comment by GM-Alex** [comment]
Hey,

currently I'm refactoring the whole plugin which tooks more time than I estimated. You could try it with the current dev version (https://github.com/GM-Alex/user-access-manager/archive/next.zip), but be warnt this version is not stable and has some known issues. Anyway if you have a test environment you could test if it fixes your problem and give some feedback.

**Comment by fbrines** [comment]
Hi Alexander


I tried to install your dev version, but I got a fatal error when activating (see attachment) [☹]

Greetings

Fernando Brines
fbrines@hotmail.com



________________________________
De: Alexander Schneider <notifications@github.com>
Enviado: lunes, 13 de marzo de 2017 12:34
Para: GM-Alex/user-access-manager
Cc: Fernando Brines; Author
Asunto: Re: [GM-Alex/user-access-manager] bbPress Topics hidden (#23)


Hey,

currently I'm refactoring the whole plugin which tooks more time than I estimated. You could try it with the current dev version (https://github.com/GM-Alex/user-access-manager/archive/next.zip), but be warnt this version is not stable and has some known issues. Anyway if you have a test environment you could test if it fixes your problem and give some feedback.

**Comment by GM-Alex** [comment]
Hey Fernando,

the attachment isn't shown at the ticket, could you upload it using the web version of github?

**Comment by fbrines** [comment]
Here is the attachment.
![uam_activate_error](https://cloud.githubusercontent.com/assets/13052032/23853708/1a251f86-07ee-11e7-813d-c53022573816.jpg)

**Comment by GM-Alex** [comment]
Please try the latest version, I removed the PHP 5.6 dependency, didn't notice that the feature I used requires PHP 5.6.

**Comment by fbrines** [comment]
I tried latest version, but bug is not solved.

**Comment by fbrines** [comment]
Hi Alex

I wonder when new plugin release will be available.

Thanks!

**Comment by GM-Alex** [comment]
If I'm done. ;) To be serious I hope within the next three or four weeks, depends on my free time.

**Comment by fbrines** [comment]
Oh God!

I expected early... I'm in problems with bbPress and a website.

Ok, Alex. I will wait. May the Force be with you.


Many thanks

Un saludo

Fernando Brines
fbrines@hotmail.com



________________________________
De: Alexander Schneider <notifications@github.com>
Enviado: jueves, 23 de marzo de 2017 10:50
Para: GM-Alex/user-access-manager
Cc: Fernando Brines; Author
Asunto: Re: [GM-Alex/user-access-manager] bbPress Topics hidden (#23)


If I'm done. ;) To be serious I hope within the next three or four weeks, depends on my free time.

**Comment by GM-Alex** [comment]
Fixed in 2.0.0
