### ISSUE TITLE
UAM-CloudSearch plugin conflict, search page

### ISSUE THREAD

**Issue by amywieliczka** [GM-Alex/user-access-manager#244]
I'm using the CloudSearch plugin (https://wordpress.org/plugins/cloud-search/) to index our public facing content. The plugin overwrites the search results template with its own `cloud-search-template-default.php` and bypasses the WordPress search in favor of the CloudSearch index. Even when I overwrite the CloudSearch search results template with a 'hello world', I still see the following error: 

However, when I use the plugin alongside UAM, I get the following error: 

```
Fatal error: Uncaught TypeError: 
Argument 1 passed to UserAccessManager\Controller\Frontend\PostController::filterRawPosts() must be of the type array, null given, called in /Applications/MAMP/htdocs/wp-content/plugins/user-access-manager/src/Controller/Frontend/PostController.php on line 308 and defined in 
/Applications/MAMP/htdocs/wp-content/plugins/user-access-manager/src/Controller/Frontend/PostController.php:277 

Stack trace: 
#0 /Applications/MAMP/htdocs/wp-content/plugins/user-access-manager/src/Controller/Frontend/PostController.php(308): UserAccessManager\Controller\Frontend\PostController->filterRawPosts(NULL) 
#1 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(288): UserAccessManager\Controller\Frontend\PostController->showPosts(NULL) 
#2 /Applications/MAMP/htdocs/wp-includes/plugin.php(244): WP_Hook->apply_filters(NULL, Array) 
#3 /Applications/MAMP/htdocs/wp-includes/class-wp-query.php(2982): apply_filters_ref_array('the_posts', Array) 
#4 /Applications/MAMP/htdocs/wp-includes/class-wp-query.php(3230): WP_Q in /Applications/MAMP/htdocs/wp-content/plugins/user-access-manager/src/Controller/Frontend/PostController.php on line 277
```

With either UAM or CloudSearch deactivated, the search results page works (in one case searching the db, in the other searching the index). Ideally, I'd like to use both of these plugins. Any advice is greatly appreciated, thanks.

**Comment by GM-Alex** [comment]
Hi @amywieliczka,

the post list is defined as an array, so null shouldn't be returned. It seems that cloud search returns null instead of an empty array. That should be fixed in the cloud search plugin. Could you create an issue there? Thanks.
