### ISSUE TITLE
array_merge() Error

### ISSUE THREAD

**Issue by schokopress** [GM-Alex/user-access-manager#25]
Hi Alex,

I just noticed that one page of my website shows this error:

“Warning: array_merge(): Argument #1 is not an array in […]/wp-content/plugins/user-access-manager/class/UserAccessManager.php on line 1494”

I looked at the php-file and found this function:

if (count($aAllExcludedPosts) > 0) {
$oWpQuery->query_vars[‘post__not_in’] = array_merge(
_$oWpQuery->query_vars[‘post__not_in’],_
$aAllExcludedPosts
);
Line 1494 is highlighted in italic. This error appears only on one page, not on any other of the pages. As UAM has no specific function on this page, I cannot see why this error appears there. As soon as I log in, the error is gone, but any visitor will see it. (Installed version is 1.2.14 on Wordpress 4.7.3)
Any ideas how to fix this?

Thanks in advance,
schokopress

**Comment by oliverini** [comment]
We have the same issue, Started 17 Feb:
 PHP Warning:  array_merge() [<a href='function.array-merge'>function.array-merge</a>]: Argument #1 is not an array in /home/manorl92/public_html/wp-content/plugins/user-access-manager/class/UserAccessManager.php on line 1496

**Comment by GM-Alex** [comment]
Fixed with 2.0.0
