### ISSUE TITLE
issues with the login form of UAM

### ISSUE THREAD

**Issue by gadh** [GM-Alex/user-access-manager#26]
issue 1:
when using plugin that renames the login url (such as WP security rename login feature, or “Rename wp-login.php”, the login url still remains the same in UAM, for example in the login form UAM displays in a post page (instead of its contents) when the user access is forbidden.
i suggest using the wordpress functions that gets the login url automatically instead of using static “wp-login.php” string in the code.

issue 2: in wp 4.7.x hebrew version (RTL) (maybe also in the english version too) , in the above form, the “RegisterLost your password?” are too close to each other, there should be some space in between, like “Register Lost your password?

tnx
Gad

**Comment by gadh** [comment]
in issue 2, i suggest using hard spaces (&nbsp;) in the code

**Comment by GM-Alex** [comment]
There is no filter/action for the login url. The plugins archive the rename all in a different way. Use the `uam_login_form_url` filter to adjust the login url for the uam login form.

**Comment by GM-Alex** [comment]
Space is added in 2.0.4
