### ISSUE TITLE
How can i get Custom Post type Listing for all users irrespective of access group assigned to them.

### ISSUE THREAD

**Issue by niralisejpal** [GM-Alex/user-access-manager#264]
Hello,

I have created one custom field to admin side - which is a select dropdown - that contains a list of specific custom post type.

So, when i have logged in as an administrator of the site - i can get all posts in list to select the option but when i have tried by login as a editor - the list was of only those posts - which are belong to the same access group as assigned to that editor user.

So, here my question comes in - that is there any possibility that for that perticular select box - i can do any custom query or use any custom UAM hook that  will allow me to show all the posts in that select box options for all logged-in users irrespective of their access group.

Let me know if you want more details.

**Comment by niralisejpal** [comment]
Hello UAM Team,

When can i get answer for this one?

**Comment by GM-Alex** [comment]
You have to write a custom mysql query for that using $wpdb. 

Important side note: This is an issues tracker for bugs and feature requests not a support forum.
