### ISSUE TITLE
Loss of groups after update

### ISSUE THREAD

**Issue by DarrenM0** [GM-Alex/user-access-manager#271]
After the latest update all of our 10,000 users have lost their specified user groups and all posts have been made full access.
This is 100's of hours of work for us to fix, what went wrong?

**Comment by GM-Alex** [comment]
Hey I didn't changed anything related to the user groups or database from 2.1.11 to 2.1.12 so I haven't any idea what went wrong, I also would say it should be impossible that something goes wrong. Did you update from any version future instead of 2.1.11?

**Comment by DarrenM0** [comment]
Something definitely went wrong, we updated from 2.1.11 to version Version 2.1.12
We’ve used the plugin for at least 18 months.

**Comment by DarrenM0** [comment]
Everything was 100% functioning until we pressed to update the plugin within Wordpress

**Comment by GM-Alex** [comment]
Could you check the wp_uam_accessgroup_to_object table? Is it empty? Do you have a database backup?

**Comment by DarrenM0** [comment]
He's provided the following:

"as for "issues in new the new version, i think that the plugin don't have them ( or I don't know about them ) . One thing that causes problem is that in a new version plugin has different DB structure and all other project logic is based on the old structure."

**Comment by GM-Alex** [comment]
That's definitely not the case the structure is 100% the same. Last database change was introduced with version 2.1.1. So the database is the same since that.

**Comment by DarrenM0** [comment]
We're fixed from our side so we're happy again :)
I'm no developer so can only relay what I was told.

**Comment by GM-Alex** [comment]
Okay, glad to here but I'm a little confused for now. :) Anyway I will close this.
