### ISSUE TITLE
Portfolio page not hidden

### ISSUE THREAD

**Issue by bluelemonade** [GM-Alex/user-access-manager#288]
hello,

the plugin works great with pages and posts. but when Using a custom theme with a portfolio in the menu I got problems, where can I assign this topic to a group?its shown as inhaltstyp archiv in the menü editor.

regards

**Comment by bluelemonade** [comment]
ok, I changed the taxonomies setting, now the single portfolio is hidden, but in the overview site the portfolio is shown with one image. I can Click it an then the site is empty. the theme is kalium with Laborotr to confurate the theme. how can I hide the Portfolio from the menu.

**Comment by GM-Alex** [comment]
I seems for me that this a theme issue in combination with the plugin, so you should try to contact the author of the theme, if I'm wrong just write back and I will reopen the issue.
