### ISSUE TITLE
Not getting permission even after adding the IP

### ISSUE THREAD

**Issue by AshishAgrawal2** [GM-Alex/user-access-manager#292]
Hi, does the plugin not support dynamic IP. My IP was working fine till yesterday but not able to access today even after giving permission.

**Comment by GM-Alex** [comment]
Hi,

if your changes IP you also need to change it at the backend. How should the plugin know that your IP has changed?

**Comment by AshishAgrawal2** [comment]
Possibly, I did not explain it properly. What I meant was, even after updating the new IP, i am not able to access. I have to delete and reinstall the plugin to gain back access.
