### ISSUE TITLE
Post Access Settings

### ISSUE THREAD

**Issue by lukasmontanes** [GM-Alex/user-access-manager#30]
Hi I’m new with wordpress.

I installed the User Access Manager Plugin, to be able to create 3 author groups. The authors shall be able to create, edit and delete the posts within their groups. This works fine so far. But when the author creates a new post he is able to grant access to e groups he’s not an author of. So when he accidently checks the wrong access checkbox and publishes the post, he won’t see it anymore in the posts overview as he is in the “wrong” group.

E.G. Alfred is in author group A and writes a post, he then checks the access box for Group B instead of Group A. Now he saves the post and goes back to the posts overview. Now he won’t see his post as he is in Group A.

My question is now: Is there any possibility to either limit the access boxes to the groups the user is connected to or to set the default access to the users group?

Thank you in advance for your answer and help.

Kind regards
Lukas

You can see here, I can check all Access Checkboxes even so I'm member of the "Autoren-IT" group.
![image](https://cloud.githubusercontent.com/assets/27005043/24794983/04ceb568-1b88-11e7-813b-eb731aa0beb7.png)

**Comment by GM-Alex** [comment]
If you have give the authors full access to there own posts the should only see the groups which there are assigned to. But for such questions please use the support thread here: https://wordpress.org/support/plugin/user-access-manager/ There a "normal" users which can also help. This here is to track feature request and bugs. Thank you.
