### ISSUE TITLE
Problem when bulk editing

### ISSUE THREAD

**Issue by diegocgaona** [GM-Alex/user-access-manager#304]
Hi!!

First, thanks for your great plugin!!

I noticed a problem, when I'm bulk editing pages from "all pages" and selecting protected pages (that  I don't want to change the access group), I select nothing on UAM and left the option to "Add", what I think would only add an access group (if one is selected) but it remove all the access groups from the selected pages.

If I select "Add", it would to only add access groups if I select one, and not remove any group, right? I think it's a bug.

Thanks!!!!

**Comment by clarkadmin** [comment]
I came across this too.

If I'm just trying to update something through the Bulk Edit on "All Pages" listings, it should only update the UAM group if a change was made. If nothing was selected, nothing should change, however, it just removes all the UAM groups from the pages (exposing all pages / content)... this is a big flaw that needs to be fixed.

**Comment by GM-Alex** [comment]
Fixed with 2.2.14
