### ISSUE TITLE
Not compatible with PHP 7.4

### ISSUE THREAD

**Issue by bunglegrind** [GM-Alex/user-access-manager#307]
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in [...]wp-content\plugins\user-access-manager\src\Util\Util.php on line 100

Anyway, using the ternary operator in this way means trouble, expecially in PHP.

**Comment by GM-Alex** [comment]
Fixed.
