### ISSUE TITLE
The plugin need to be updated

### ISSUE THREAD

**Issue by PeopleInside** [GM-Alex/user-access-manager#311]
Hi, the Wordfence security plugin alerted me this plugin is not updated since different years.
Please update it it's an essental plugin.

**Comment by BlueDonutStudios** [comment]
We think this project may be discontinued?

**Comment by PeopleInside** [comment]
Will be nice if someone can mantain live this as is very useful or to know an alternative. I cannot stay without this..

**Comment by GM-Alex** [comment]
@PeopleInside I currently working on an update.

**Comment by BlueDonutStudios** [comment]
We that's good. It is a handy plugin. The push for updates especially security is oh so very important these days. :-)

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside I currently working on an update.

Great news, thanks <3

**Comment by GM-Alex** [comment]
Version 2.2.0 is available now.

**Comment by PeopleInside** [comment]
Thanks Alex.
My website was inaccessible after you release the update (don't know why) but Wordpress helped me with an email that helped to resume the website. I see the plugin needs an update, made the update, restarted the plugin and all now seems work fine.

Thank you!
