### ISSUE TITLE
2.2.0 breaks site with error

### ISSUE THREAD

**Issue by rumsrums** [GM-Alex/user-access-manager#315]
Hello,

The update to 2.2.0 breaks my site.  Reverting back to 2.1.12 works just perfectly.  If you search in Google for a bit of the error you can see a number of websites are broken by the update.  

I can see other websites with the error: 

[https://www.google.com/search?sxsrf=ALeKk02heGmHVOeQJ22R2NDB_MbVSvL4XQ%3A1613195556724&ei=JGknYKPbK5Xv-gSonL_oDw&q=%22wp-content%2Fplugins%2Fuser-access-manager%2Fsrc%2FObject%2FObjectHandler.php%22&oq=%22wp-content%2Fplugins%2Fuser-access-manager%2Fsrc%2FObject%2FObjectHandler.php%22&gs_lcp=Cgdnd3Mtd2l6EANQniNYniNgtyVoAXAAeACAAVKIAZkBkgEBMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwij_fHglebuAhWVt54KHSjOD_0Q4dUDCA0&uact=5
](url)

Here is the error:

`
Fatal error: Uncaught TypeError: Argument 2 passed to UserAccessManager\Object\ObjectHandler::registeredTaxonomy() must be of the type string, array given, called in /home/public_html/wp-includes/class-wp-hook.php on line 287 and defined in /home/public_html/wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php:225 Stack trace: #0 /home/public_html/wp-includes/class-wp-hook.php(287): UserAccessManager\Object\ObjectHandler->registeredTaxonomy('portfolio-tag', Array, Array) #1 /home/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /home/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /home/public_html/wp-includes/taxonomy.php(474): do_action('registered_taxo...', 'portfolio-tag', Array, Array) #4 /home/public_html/wp-content/themes/x/framework/functions/portfolio.php(98): register_taxonomy('portfolio-tag', Array, Array) #5 /home/public_html/wp-includes/class-wp-hook.php(287): x_port in /home/public_html/wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php on line 225`

**Comment by JaylonProd** [comment]
I just signed up for Git Hub to make this post and you beat me to it by 34 seconds.

**Comment by JaylonProd** [comment]
My error reads:

An error of type E_ERROR was caused in line 225 of the file /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php. Error message: Uncaught TypeError: Argument 2 passed to UserAccessManager\Object\ObjectHandler::registeredTaxonomy() must be of the type string, array given, called in /home/ourundoi/public_html/wp-includes/class-wp-hook.php on line 287 and defined in /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php:225

**Comment by rumsrums** [comment]
If you need your sites fixed before the dev gets to it, you can download 2.1.12 from here (scroll to the bottom and use the drop down)

[https://en-ca.wordpress.org/plugins/user-access-manager/advanced/](url)

I'd also highly recommend turning off auto-updates on the plug-in.  You may need to do it manually by editing the plug-ins readme.txt file and user-access-manager.php files and editing references to 2.1.12 to 99.1.12.  That way it won't try to update to 2.2.0 and break your site again.

**Comment by JaylonProd** [comment]
Thanks, rumsrums!

**Comment by rumsrums** [comment]
You're welcome!  Good luck.  Hopefully the developer of this fantastic plug-in can fix the issue.

**Comment by GM-Alex** [comment]
I tested a lot but seems that is was not enough, version 2.2.1 with a fix will be available within a few minutes. If you have future issues just open a new issue and I will fix them asap.
