### ISSUE TITLE
The login form does not appear after updating to 2.2.1

### ISSUE THREAD

**Issue by hohanLee** [GM-Alex/user-access-manager#317]
I was using the login form in widgets.
It was automatically updated to 2.2.1 today.
The login form does not appear as below.
![image](https://user-images.githubusercontent.com/79005671/107848559-abd43580-6e37-11eb-975a-75d8bbe0e150.png)

So, I modified it as below and it came out well.

at LoginForm.php

before
```
 <label class="input_label" for="user_login"><?php echo TXT_UAM_LOGIN_FORM_USERNAME; ?>:</label>
        <input name="log" value="<?php echo $controller->getUserLogin(); ?>" class="input" id="user_login"
               type="text"/>
        <label class="input_label" for="user_pass"><?php echo TXT_UAM_LOGIN_FORM_PASSWORD; ?>:</label>
```

after
```
        <label class="input_label" for="user_login"><?php echo TXT_UAM_LOGIN_FORM_USERNAME; ?>:</label>
        <input name="log" class="input" id="user_login" type="text"/>
        <label class="input_label" for="user_pass"><?php echo TXT_UAM_LOGIN_FORM_PASSWORD; ?>:</label>
```

Please check if it is a bug.

**Comment by GM-Alex** [comment]
Version 2.2.2 is now available and should fix the issue. Please let me know if it works for you.

**Comment by hohanLee** [comment]
Works well. Thanks for the quick fix!
