### ISSUE TITLE
Cannot Delete User Group

### ISSUE THREAD

**Issue by JaylonProd** [GM-Alex/user-access-manager#319]
This is the error message when I try to delete a new user group:

An error of type E_ERROR was caused in line 206 of the file /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/UserGroup/UserGroupHandler.php. Error message: Uncaught TypeError: Argument 1 passed to UserAccessManager\UserGroup\UserGroupHandler::deleteUserGroup() must be of the type int, string given, called in /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/Controller/Backend/UserGroupController.php on line 288 and defined in /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/UserGroup/UserGroupHandler.php:206 Stack trace: #0 /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/Controller/Backend/UserGroupController.php(288): UserAccessManager\UserGroup\UserGroupHandler->deleteUserGroup('2') #1 /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/Controller/Controller.php(173): UserAccessManager\Controller\Backend\UserGroupController->deleteUserGroupAction() #2 /home/ourundoi/public_html/wp-content/plugins/user-access-manager/src/Controller/Controller.php(182): UserAccessManager\Controller\Controller->processAction() #3 /home/ourundoi/public_html/wp-includes/class-wp-hook.php(287): UserAcce

**Comment by GM-Alex** [comment]
Fixed with version 2.2.3.
