### ISSUE TITLE
The language files disappeared with the update 2.0.0

### ISSUE THREAD

**Issue by wpdon** [GM-Alex/user-access-manager#32]
With the new update 2.0.0 the language files disappeared.

**Comment by GM-Alex** [comment]
Hi,

I did that on purpose. Sorry for the confusion but I want to use https://translate.wordpress.org/projects/wp-plugins/user-access-manager. If a translation reaches 95% the translation is downloaded automatically by Wordpress. So if you would like to translate the plugin to your native language I would really appreciate it if you contribute there.
