### ISSUE TITLE
fatal error after upgrade / database access handler uses incorrect interface

### ISSUE THREAD

**Issue by vogtadi** [GM-Alex/user-access-manager#321]
after upgrading to 2.2.3 on a WP 5.6.1 installation, I get the following runtime error

[Sat Feb 13 22:48:41.927993 2021] [php7:error] [pid 3905] [client x.x.x.x:13650] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to UserAccessManager\\Wrapper\\Wordpress::switchToBlog() must be of the type int, string given, called in /home/vereine/www-wordpress/wp-content/plugins/user-access-manager/src/Setup/Database/DatabaseHandler.php on line 305 and defined in /home/vereine/www-wordpress/wp-content/plugins/user-access-manager/src/Wrapper/Wordpress.php:251\nStack trace:\n#0 /home/vereine/www-wordpress/wp-content/plugins/user-access-manager/src/Setup/Database/DatabaseHandler.php(305): UserAccessManager\\Wrapper\\Wordpress->switchToBlog()\n#1 /home/vereine/www-wordpress/wp-content/plugins/user-access-manager/src/Setup/Database/DatabaseHandler.php(326): UserAccessManager\\Setup\\Database\\DatabaseHandler->getActivePluginSites()\n#2 /home/vereine/www-wordpress/wp-content/plugins/user-access-manager/src/Controller/Backend/BackendController.php(93): UserAccessManager\\Setup\\Database\\DatabaseHandler->isDatabaseUpdateNecessary()\n#3 /home/vereine/www-wordpress/wp-includes/class-wp-hook.php(287): UserAccessManager\\C in /home/vereine/www-wordpress/wp-content/plugins/user-access-manager/src/Wrapper/Wordpress.php on line 251, referer: https://xxx.yy/wp-admin/my-sites.php

**Comment by vogtadi** [comment]
Last version working before I did the update was 2.1.12. Restoring this from a Backup recovers the functionality.

**Comment by GM-Alex** [comment]
New version 2.2.4 should fix the issue.

**Comment by vogtadi** [comment]
Yes, that did the trick. Thanks😊 for the very quick reaction and fix.
