### ISSUE TITLE
Are there hooks to bypass the default restrictions?

### ISSUE THREAD

**Issue by bruno-barros** [GM-Alex/user-access-manager#336]
I'm searching on code, but no apply_filters found.

Just to let you know what I'm looking for. I want to restrict the category, but allow the category visualizarion. Only the posts should be restricted.

Thanks

**Comment by GM-Alex** [comment]
I'm afraid there are no hooks or filters for that. Please just make a PR with the needed hooks or filter, if possible with adjusted tests.

**Comment by bruno-barros** [comment]
ok!
