### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by habaumgardner** [GM-Alex/user-access-manager#339]
My site is down because of a problem with my User Access plugin. Here is what WordPress says:

**Plugin could not be activated because it triggered a fatal error.

Warning: require_once(/var/www/wp-content/plugins/user-access-manager/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/user-access-manager/user-access-manager.php on line 72

Fatal error: require_once(): Failed opening required '/var/www/wp-content/plugins/user-access-manager/vendor/autoload.php' (include_path='.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/wp-content/plugins/user-access-manager/user-access-manager.php on line 72**

Please help.

**Comment by GM-Alex** [comment]
Please reinstall the plugin, it seems that aren't all files uploaded.

**Comment by habaumgardner** [comment]
That took care of it. Thank you.
