### ISSUE TITLE
PHP Fatal error:  Call to undefined function wp_get_current_user()

### ISSUE THREAD

**Issue by rbahassine** [GM-Alex/user-access-manager#34]
Since the update of the 2017/04/23 I got this error :

 PHP Fatal error:  Call to undefined function wp_get_current_user() in /var/www/intranet-preprod/wp-content/plugins/user-access-manager/src/UserAccessManager/Wrapper/Wordpress.php on line 344

I patched it myself (waiting for the official patch) by adding this :+1: 

require_once( ABSPATH . '/wp-includes/pluggable.php' );

**Comment by GM-Alex** [comment]
Fixed with 2.0.2
