### ISSUE TITLE
Fatal Error after upgrading to PHP 8

### ISSUE THREAD

**Issue by theninabird** [GM-Alex/user-access-manager#349]
After upgrading to PHP 8 I'm receiving a fatal error:

PHP Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /nas/content/live/htibuyinggroup/wp-content/plugins/user-access-manager/src/UserAccessManager/Util/Util.php on line 100

**Comment by GM-Alex** [comment]
Hi @theninabird,

which version of the plugin are you using? Since 2.1.13 this should be fixed, so please upgrade to the latest version.
