### ISSUE TITLE
Scaled media files not showing while media setting is restricted

### ISSUE THREAD

**Issue by feuerballer** [GM-Alex/user-access-manager#350]
Hi,
I activated UAM on a fresh installation of Wordpress and locked files in UAM settings. No media file has been marked for restricted access and I can almost see every uploaded image file. Except images that are too large and are automatically beeing scaled by Wordpress during upload.

I can see the scaled image. But I can not see the original or any size version of the image. Probably because of the naming. In difference to edited images the scaled image is getting an additional name "-scaled". The different sizes of the image are not getting this additional name.

image.jpg (original)
image-scaled.jpg (scaled)
image-150x150.jpg (size 150x150)
...
image-2048x2048.jpg (size 2048x2048)

UAM obviously can't handle these filenames. Only the full-size scaled image (image-scaled.jpg) is displayed properly.
I am using the latest version of Wordpress (5.9) and the latest version of UAM (2.2.6).

Is there a solution to fix that or a workaround?
Thank you!

Florian

**Comment by GM-Alex** [comment]
Hi Florian,

since files are protected the delivery of the files needs to be done via php instead directly via the server. So direct links will not work if you activate the file protection. Where are the other file names from? Are these files created by Wordpress? Scaled is none default Wordpress naming as far I know. I also tested it right now with a fresh install of wordpress and the default media gallery an it works for me without problems. Are you using a third party plugin?

Greetings,
Alex

**Comment by feuerballer** [comment]
Hi Alex,

thanks for your quick reply. No. No other plugins or modifications are installed. It seems to be a feature introduced in 5.3 concerning the upload of huge images (> 2560px).
[https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/]

Regards,
Florian

**Comment by GM-Alex** [comment]
@feuerballer Would you be so kind an try the following version: https://github.com/GM-Alex/user-access-manager/archive/refs/heads/next.zip

**Comment by feuerballer** [comment]
> @feuerballer Would you be so kind an try the following version: https://github.com/GM-Alex/user-access-manager/archive/refs/heads/next.zip

No difference. I can see the automatic scaled image (image-scaled.jpg) but neither the original (image.jpg) nor the different sizes (image-150x150.jpg, ..., image-2048x2048.jpg).

**Comment by GM-Alex** [comment]
Could you debug which postId is returned for the scaled image (var_dump($postId) before the $postId === 0 condition)?

**Comment by feuerballer** [comment]
My bad. You're right. It is working. $postId === 0

Well done. Thank you!

**Comment by GM-Alex** [comment]
Thanks for the feedback.
