### ISSUE TITLE
File could not be loaded in Chrome

### ISSUE THREAD

**Issue by GMS89** [GM-Alex/user-access-manager#363]
Since the last update of WordPress, you can no longer open files in Chrome. He gives the message:

Error
Unable to load PDF document
 
It is still possible in Firefox or Safari, but not in Chrome. Very weird.

Any idea how to solve this?

**Comment by chrissberr** [comment]
The same problem here, Downloads protected by UAM don't work in Chrome and Edge:
Console: "Failed to load resource: the server responded with a status of 404 ()"

WordPress 6.1
User Access Manager Version 2.2.16 
PHP 7.4 or 8.1 doesn't matter

Thanks in advance for any inputs on this...

**Comment by chrissberr** [comment]
Today all downloads are broken, also in Firefox... I had to switch off UAM File settings > Lock files

**Comment by GM-Alex** [comment]
Fixed with 2.2.18, release soon.

**Comment by GMS89** [comment]
Thank you and glad it will be adjusted.
