### ISSUE TITLE
How to assign default rights to Custom Content Type

### ISSUE THREAD

**Issue by gerdw117** [GM-Alex/user-access-manager#369]
Hi!
I try to get the following behavior: 

A Custom Content Type (lets call it "team_page") should be readable by the group "team" and writable to the group "teameditors".

On the Tab "default user groups" I selected my Content Type team_page and assigned both groups to it.

If the WP-Admin now creates as new team_page the accessibility is correctly predefined, an the result is as i want it.

But if a member of the group "teameditors" creates a page of the type team_page, the page is world readable.

Can sombody give me a hint how i can get it to work?
Yours,
Gerd

**Comment by GM-Alex** [comment]
Please use the Wordpress support forum page of the plugin for general questions. This issue tracker is for bugs. Thanks a lot.
