### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by amyschan** [GM-Alex/user-access-manager#37]
I just updated to version 2.02 and updated the database accordingly.

![database-updated](https://cloud.githubusercontent.com/assets/900909/25352537/368942ba-28e1-11e7-81db-61528fe96f7a.jpg)

Then when I go to "Pages", I get a "Catchable fatal error".

![catchable-fatal-error](https://cloud.githubusercontent.com/assets/900909/25352546/3eb62e1c-28e1-11e7-810f-f03608581be2.jpg)

Let me know if you need more info to help troubleshoot.

Thanks again!

**Comment by GM-Alex** [comment]
Could you tell me what cms_tpv is, I think that makes trouble in combination with the UAM?

**Comment by amyschan** [comment]
Sure! It's the [CMS Tree Page View](https://wordpress.org/plugins/cms-tree-page-view/) plugin.

**Comment by GM-Alex** [comment]
Could you try to deactivate it and test again?

**Comment by amyschan** [comment]
That worked!

So looks like CMS Tree Page View combined with latest version of UAM is what was causing the trouble.

Thank you for the fast response and wonderful plugin!

**Comment by GM-Alex** [comment]
I add an extra check. Fixed with 2.0.3
