### ISSUE TITLE
htaccess content for file lock being erased

### ISSUE THREAD

**Issue by monkee333** [GM-Alex/user-access-manager#374]
Hi, 
Is there any reason why the content of the .htaccess in the uploads folder had been erased ? 
The files were no more protected and were readable to anyone who has the link.
After saving again the file settings page, it was filled again and the files protected, but I fear it may happen again.

Thanks

**Comment by GM-Alex** [comment]
Nobody reported this behaviour. Normally this happens if you set the setting to custom or disable the file locking at the backend.

**Comment by monkee333** [comment]
Thanks for the answer, what do you mean by “set the setting to custom” ?

Here is what is set in the screenshot. It was working well for hours, then I left and checked again, the htaccess was empty.
Can it be the host settings ? I'm waiting for them to upgrade to PHP 8.1 (now it's 7.3), but I wonder if it can be caused by some file permission, any server cache... 
Thanks

![Screen Shot 2023-03-30 at 6 15 41 PM](https://user-images.githubusercontent.com/129412507/228976073-6964a581-af1c-4e2e-a2e1-2388b28ef544.png)
