### ISSUE TITLE
Unklare Beschreibung bei den Einstellungen zum Anmeldeformular

### ISSUE THREAD

**Issue by Clasame** [GM-Alex/user-access-manager#375]
"Inhalt, der angezeigt wird, wenn ein Benutzer keinen Zugriff hat. Es kann ein Anmeldefotmular hinzugefügt werden, indem das Schlüsselwort [LOGIN_FORM] verwendet wird. Dieses Feld wird auf Einzel %s angezeigt. Auf anderen Seiten wird ein Link eingefügt."

Leider ist diese Anweisung nicht klar - hilfreich wären weiterführende Informationen oder Screenshots des weiteren Vorgehens

**Comment by GM-Alex** [comment]
Hi @Clasame,

just type `[LOGIN_FORM]` within the text input and it renders a login form or a link to the login form, depending on the fact if the post is shown in a list or as single post, if a user has no access. Feel free to submit your translation for German here: https://translate.wordpress.org/locale/de/default/wp-plugins/user-access-manager/

Greetings,
Alex
