### ISSUE TITLE
Fatal Error and no access to the site

### ISSUE THREAD

**Issue by Sorbas48** [GM-Alex/user-access-manager#38]
After updating to version 2.0.1 instead of my WEB-site I have got the message:
Fatal error: Uncaught Error: Call to undefined method UserAccessManager\Util\Util::get_option_value() in /home/.sites/65/site1428/web/wp-content/plugins/seo-redirection/seo-redirection.php:415 Stack trace: #0 /home/.sites/65/site1428/web/wp-includes/class-wp-hook.php(298): WPSR_redirect(Object(WP)) #1 /home/.sites/65/site1428/web/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #2 /home/.sites/65/site1428/web/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #3 /home/.sites/65/site1428/web/wp-includes/class-wp.php(746): do_action_ref_array('wp', Array) #4 /home/.sites/65/site1428/web/wp-includes/functions.php(955): WP->main('') #5 /home/.sites/65/site1428/web/wp-blog-header.php(16): wp() #6 /home/.sites/65/site1428/web/index.php(17): require('/home/.sites/65...') #7 {main} thrown in /home/.sites/65/site1428/web/wp-content/plugins/seo-redirection/seo-redirection.php on line 415
Update of the database after updating responded proper update, but after change to another page om my site the error occurred.
Access was impossible, until the Plugin was deleted via FTP from ../wp-content/plugins/…
Is the problem fixed, with actual version 2.0.2?
Changelog does not report about versions since 1.2.14
(as 2017/01/07  Fix IP access issue.                         Some small optimization.

**Comment by GM-Alex** [comment]
Could you please test the current dev version from here: https://github.com/GM-Alex/user-access-manager/archive/master.zip

**Comment by GM-Alex** [comment]
Was an issue with the seo redirection plugin. Fixed with 2.0.3

**Comment by Sorbas48** [comment]
I'm away from my PC until the evening, I'l test it after 19:00 CEST

**Comment by Sorbas48** [comment]
The problem together with SEO redirection is fixed on my site http://www.symi.at, thanks.

**Comment by Sorbas48** [comment]
Is there any open issue on user access manager? (Currently installed 2.0.5)

I have noticed a number of attempts on my SEO report for somebody calling or dumping details as follows:

date+time/link/attempts/IP/OS/Browser

      25.04.2017 18:28
     /wp-content/plugins/user-access-manager/css/uamLoginForm.css?ver=1.0
     9
     79.206.178.154
     Safari
     Chrome
     
      25.04.2017 18:28
     /wp-content/plugins/user-access-manager/css/uamAdmin.css?ver=1.0
     9
     79.206.178.154
     Safari
     Chrome
     
      25.04.2017 18:29
     /wp-content/plugins/user-access-manager/js/functions.js?ver=4.7.3
     2
     87.166.157.228
     iPhone
     Safari
     



Kind regards

Hans
