### ISSUE TITLE
versionReturns 404 error on a unauthorized page (v2.0.2)

### ISSUE THREAD

**Issue by mtomasg** [GM-Alex/user-access-manager#39]
I've updated your plugin to version v2.0.2 and now, when I enter to an unauthorized page (and I'm not logged), wordpress throws error 404. I've searched in settings, documentation, and I haven't found no solution to that problem, any way to fix it?

Last version of Wordpress (4.7.4)

**Comment by GM-Alex** [comment]
If you completely hide a page / post or what ever that is the normal behavior, so it's not a bug.

**Comment by mtomasg** [comment]
Thanks, you're right, sorry! I've upgraded the version and it starts to fail, I haven't seen that properties.
