### ISSUE TITLE
isMember mixed case

### ISSUE THREAD

**Issue by nwoetzel** [GM-Alex/user-access-manager#4]
https://github.com/GM-Alex/user-access-manager/blob/master/class/UamUserGroup.php#L430
I am not sure if this can cause any problem, but in the __call function, the $sPrefix is set to 'isMember' but in the following if cases, it is checked for 'ismember'.

So I would suggest to change the line to
<pre>
        } elseif ($sPrefix == 'isMember') {
</pre>

**Comment by GM-Alex** [comment]
You are right. I will change this.

**Comment by GM-Alex** [comment]
See https://github.com/GM-Alex/user-access-manager/commit/b88c810a93c01a489b64ab9db3b777849efbdbd3
