### ISSUE TITLE
Maybe it's a common mistake

### ISSUE THREAD

**Issue by adrianmike** [GM-Alex/user-access-manager#40]
I update plugin User Access Manager and I receive this error:
**Parse error: syntax error, unexpected '[' in /home/ingutgjiu/public_html/wp-content/plugins/user-access-manager/user-access-manager.php on line 171**
I don't know how can I fix this! If you want, please help!

At line 171 in file user-access-manager.php is this command: **$wordpress->doAction('uam_init', [$userAccessManager]);**

**Comment by GM-Alex** [comment]
Since version 2.0.0 the plugin requires at least PHP 5.4. You are running a version lower than PHP 5.4.

**Comment by adrianmike** [comment]
Thanks! May I asked you a very silly question? How can I update PHP?

**Comment by GM-Alex** [comment]
Please ask your hoster to do that.

**Comment by adrianmike** [comment]
Ok. Thanks again. Have a nice day!
