### ISSUE TITLE
big problem with the last release of plugin

### ISSUE THREAD

**Issue by toronto2015** [GM-Alex/user-access-manager#41]
HI i have big problem with the last release of your plugin, after the installation the site is very very slow almost impossible work, and when i disable the plugin the site return in normal condition of navigation.

Please can you help me?

Thank best regards

**Comment by GM-Alex** [comment]
Could you provide me a dump of your database?

**Comment by toronto2015** [comment]
ok just 
a amoment

**Comment by toronto2015** [comment]
the file is too much big about 180mb

**Comment by toronto2015** [comment]
give mi please your email i send you with wetranfer

**Comment by GM-Alex** [comment]
Use alexanderschneider85@gmail.com

**Comment by toronto2015** [comment]
ok thank you

**Comment by toronto2015** [comment]
just do it

**Comment by toronto2015** [comment]
site: www.iccremonauno.it.
now the plugin is disabled!!

**Comment by toronto2015** [comment]
if you need i haven't no problem give you credential of access to admin panel

**Comment by toronto2015** [comment]
please have a news??

**Comment by GM-Alex** [comment]
Please try the version from here: https://github.com/GM-Alex/user-access-manager/archive/user-access-manager-41.zip

Please double and tripple test if that solves your issue and everything else works as expected. If yes I will release it soon.

**Comment by toronto2015** [comment]
Hi i try the plugin and for the moment thats ok

**Comment by GM-Alex** [comment]
Sounds not very satisfying :) Thanks for feedback. I will merge it.

**Comment by toronto2015** [comment]
hi ,thank you for your feedback , now i have another problem , in only two sites when a active the plugin i miss the link on file in media gallery. i try with the permanlink but without solution
Can i help me about?

**Comment by GM-Alex** [comment]
Could you say me exactly which files on which page makes trouble.

**Comment by toronto2015** [comment]
all attachement  in media gallery non functionally only see the image file

**Comment by toronto2015** [comment]
if you want i need you the credential of site

**Comment by GM-Alex** [comment]
Ok on my local dev environment everything seems fine. Please send me your credentials to my mail address. I will have a look.

**Comment by toronto2015** [comment]
please give me more your email address

**Comment by GM-Alex** [comment]
alexanderschneider85@gmail.com

**Comment by toronto2015** [comment]
just do it

**Comment by GM-Alex** [comment]
Ok there is no way to modify the files. Could you give me access via ssh or ftp to the plugin folder (best would be to restrict my access only to this folder!).

**Comment by toronto2015** [comment]
just do it ........i have not problem give you the credential you are best workfriend,  thank you very much for your help

**Comment by GM-Alex** [comment]
Thanks for your trust. Seems I was able to fix it. But I seen you used the version from GitHub. I would recommend that you are using the official version from the Wordpress plugin directory. I think I will release the version including the fix today.

**Comment by GM-Alex** [comment]
I seen that some pdf thumbnails aren't loading. These files aren't using the default naming for the thumbnails which is needed to work properly. You could reupload the files and it should work.
