### ISSUE TITLE
Site not working after upgrade to latest version 2.0.3

### ISSUE THREAD

**Issue by elseyadcock** [GM-Alex/user-access-manager#42]
Just updated to the latest version of WP, then updated UAM. No other plug-ins updated.

Now getting blank pages front and back-end with this error 👎 

Parse error: syntax error, unexpected '[' in /home/sites/breheny.co.uk/public_html/WP/wp-content/plugins/user-access-manager/user-access-manager.php on line 171

If I roll back to previous version all OK.

Hope this helps.
Thanks,
Steve.

**Comment by GM-Alex** [comment]
See https://github.com/GM-Alex/user-access-manager/issues/40 (Please have a look if an issue still exists)
