### ISSUE TITLE
table "wp_uam_accessgroup_to_object" updates new users as "object_type"="_user_" instead of "user"

### ISSUE THREAD

**Issue by chrlii** [GM-Alex/user-access-manager#43]
Dear Alex,
after the last update new users are saved in the table "wp_uam_accessgroup_to_object" with an object_type that uses underscores, see table below object_id =87

![screenshot db usertoobject](https://cloud.githubusercontent.com/assets/28020040/25402975/e9841f6a-29fa-11e7-9b70-ecf81a00850e.JPG)

I used the table for some own code and my database query failed. I have found a workaround now, but just want to let you know about this inconsistency.

Regards,
Christine

**Comment by GM-Alex** [comment]
I think it's currently no problem and effect the plugin in any way, expect for custom queries, but I will fix that. Thanks for pointing it out.

**Comment by GM-Alex** [comment]
After a save the object_type is set to the new value `_user_` which is the new correct value for the object_type if it's a user.

**Comment by GM-Alex** [comment]
I decided to don't fix it. People getting crazy about database updates and it shouldn't affect the plugin in any way, as I said above. But I made this entry at the wiki: https://github.com/GM-Alex/user-access-manager/wiki/Troubleshoot#possible-inconsistency-for-users-at-uam_access_group_to_object-table

I hope that's ok for you.
