### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /home/lubedire/public_html/accountdirect/wp-content/plugins/user-access-manager/user-access-manager.php on line 171

### ISSUE THREAD

**Issue by msparks23** [GM-Alex/user-access-manager#44]
If I counted correctly: $wordpress->doAction('uam_init', [$userAccessManager]);

**Comment by GM-Alex** [comment]
See https://github.com/GM-Alex/user-access-manager/issues/40 (Please have a look if an issue still exists)
