### ISSUE TITLE
Users group names and group descriptions with special characters (é, è, à...) don't display well. 

### ISSUE THREAD

**Issue by joomlafab** [GM-Alex/user-access-manager#45]
Users group names and group descriptions with special characters like french accents : é è à etc... don't display well. They turn into something like Ã©, Ã¨, Ã , Ã¹, etc...

Server : Debian 8.7 / Apache/2.4.10 (Debian) / PHP Version 5.6.30-0+deb8u1 / Mysql 5.5.55 for debian

**Comment by GM-Alex** [comment]
I can not reproduce the issue. I think your collation of your db is set to something different than utf8. You can check it with `SHOW TABLE STATUS` for all table. UAM uses the default collation from the Wordpress settings.

**Comment by joomlafab** [comment]
Hi thanks for the highlight. My tables collations were fine, but somehow the "default_charset" in my php-fpm pool settings was set up wrong. I switched it to utf-8 and everything is fine.
