### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by mophilly** [GM-Alex/user-access-manager#46]
The following error occurred today and "killed" the web site. disabling UAM allows us to continue but without its services. 

`Apr 26 14:10:46 httpd: PHP Parse error:  syntax error, unexpected '[' in /.../.../html/wp-content/plugins/user-access-manager/user-access-manager.php on line 171`

UAM version 2.0.3
PHP version 5.3.3

**Comment by GM-Alex** [comment]
See: #40 and #42
