### ISSUE TITLE
Warning: vsprintf(): Too few arguments in .....

### ISSUE THREAD

**Issue by cghellere** [GM-Alex/user-access-manager#48]
After update on option I have this error

Warning: vsprintf(): Too few arguments in /web/htdocs/www.mysite.xxx/home/wpic/wp-content/plugins/user-access-manager/src/UserAccessManager/Controller/AdminSettingsController.php on line 237

Version php 5.6.24 
Version plugin: 2.0.4

![immagine](https://cloud.githubusercontent.com/assets/8959593/25482347/a9bee6d2-2b51-11e7-9f7e-a9472629730a.png)

**Comment by GM-Alex** [comment]
Could you change you language settings to English and test again. Seems a translation issue.

**Comment by cghellere** [comment]
Ok thanks is correct.
