### ISSUE TITLE
UAM wants PHP 5.4, I have 7.0???

### ISSUE THREAD

**Issue by DerVater** [GM-Alex/user-access-manager#49]
After activating UAM, I get an error message "Sorry you need at least PHP version 5.4 to use the User Access Manager. Your current PHP version is 5.3.29." This is strange to me, I just checked with my provider, my webspace is run under PHP 7.0?

Thanks
DarVader

**Comment by GM-Alex** [comment]
Most hoster allow it to configure php for each folder/docroot. Just create a file ending on `.php` with the following content and put it to your wordpress rootdir:

```php
<?php
phpinfo();
```

Than open it via your browser. Now you should see the running PHP version. You should name the file something secret and delete it after you got the info, if someone has access to it he could use it for bad purpose.

**Comment by DerVater** [comment]
Thanks, but what will I do with that information? How will UAM learn that I have 7.0 already?

**Comment by GM-Alex** [comment]
It will show use if you have miss configured your server or if there is a bug with UAM.

**Comment by GM-Alex** [comment]
Any update on this?

**Comment by GM-Alex** [comment]
I tested it with PHP 7 and everything works as expected. I will close this issue now. If there are any updates don't hesitate to reopen it.
