### ISSUE TITLE
Issue with html files in media library

### ISSUE THREAD

**Issue by kikigros** [GM-Alex/user-access-manager#50]
Hi,
i use media library for html files (PC inventory).
Now, when i download this files, they are modify by UAM.
At the end of original files UAM add source code of my 404 page
`...</html>`
becomes
`...</html>`
`<!DOCTYPE html>`
`all my 404 page with admin bar and all stuff`
`</html>`

I hope help you. It's my first github contrib and i love UAM :)

**Comment by GM-Alex** [comment]
Please try version 2.0.5 (should be up within around 40 minutes).

**Comment by kikigros** [comment]
Great !
That's work. You are so fast.

Thank you very much. 
The best of wishes for the future
