### ISSUE TITLE
Database update necessary

### ISSUE THREAD

**Issue by R0ad-Runn3r** [GM-Alex/user-access-manager#51]
Hey,

after downloading and activating the plugin i get a notice that i have to perform an database update.
I clicked the update button, but nothing happend.
It looks like that the tables havend been created in the database.

I hope you can help me!

kind regards

**Comment by GM-Alex** [comment]
Please try 2.0.5 (should be available within the next 40 minutes).

**Comment by R0ad-Runn3r** [comment]
I deleted and reinstalled the plugin, but the same problem still excist.

**Comment by GM-Alex** [comment]
Do you have the multi site feature enabled?

**Comment by R0ad-Runn3r** [comment]
How can i check that?
I am not sure, it should be default.

**Comment by GM-Alex** [comment]
If you don't know it you probably doesn't use it. If your wp-config.php file should contains like that

```php
define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
```

you are using the multi site feature.

**Comment by R0ad-Runn3r** [comment]
I edited the file and installed the plugin again, but no success.

**Comment by GM-Alex** [comment]
Ah sorry for the miss understanding don't edit the file. Just revert your changes. Seems I need access to your page (if that's ok) to investigate what's going on.

**Comment by d4igroup** [comment]
Any news on this? I need this plugin to work for me urgently. I have two different websites and on one I have had UAM for a while and now I added it today to my new website and got the same issue as R0ad-Runn3r .

**Comment by daschug** [comment]
hi, i got an error message, although doing the databdase update:
"WordPress-Datenbank-Fehler: [Table 'my-site-name.wp_uam_accessgroups' doesn't exist]
SELECT ID FROM wp_uam_accessgroups"
Tables just not created? - I can't find any with uam-suffix if using phpmyadmin...
Best regards, Ralf

**Comment by GM-Alex** [comment]
The issue was a wrong path for the install hook. Download or update to 2.0.6 (should be available within the next minutes) just deactivate and activate the plugin again or reset it under UAM > Setup > Reset. That should install the tables and everything should work.

**Comment by daschug** [comment]
I did that. If I now add a group it says: "INSERT INTO `wp_uam_accessgroup_to_object` (`group_id`, `object_id`, `general_object_type`, `object_type`) VALUES (NULL, 'wpcw_instructor', '_role_', '_role_')"

**Comment by GM-Alex** [comment]
Please wait for Version 2.0.6 it's not released now. See my comment before.

**Comment by d4igroup** [comment]
Now it works. Thanks Alex.   :)

**Comment by R0ad-Runn3r** [comment]
Thanks!
