### ISSUE TITLE
Incompatibility with Subscribe to Comments Reloaded Plugin (StCR)

### ISSUE THREAD

**Issue by ssguptainc** [GM-Alex/user-access-manager#52]
The StCR management page started giving 404 error. When UAM is deactivated StCR management page shows up, when UAM is activated it is 404 again for StCR. Thanks.

**Comment by GM-Alex** [comment]
The backend pages? Seems to work for me. Are you using version 2.0.5?

**Comment by ssguptainc** [comment]
Yes using 2.05. The virtual management page created here:

/wp-admin/admin.php?page=stcr_management_page.

It doesn't shows up in the frontend, gives 404 error.

It was working in the older version of UAM.

**Comment by GM-Alex** [comment]
Ah thanks. Confirmed.
