### ISSUE TITLE
Huge performance decrease since version 2.0.0

### ISSUE THREAD

**Issue by MZwillus** [GM-Alex/user-access-manager#53]
I always found our WordPress site very slow using this plugin, but since version 2.0.0 a request takes about 11 seconds.

Having the plugin enabled:

![image](https://cloud.githubusercontent.com/assets/23220656/25518748/47d25bee-2bf5-11e7-9d83-85da02817588.png)

Disabled plugin:

![image](https://cloud.githubusercontent.com/assets/23220656/25518862/c3da2794-2bf5-11e7-9fa2-5272bdcaa788.png)

Did I misconfigure something?

**Comment by GM-Alex** [comment]
Which version you are currently using? 2.0.5?

**Comment by MZwillus** [comment]
Yes that's correct :)

**Comment by GM-Alex** [comment]
Would you mind to send me a dump of your database? If you have sensitive data in it just overwrite it with an empty string like

```mysql
UPDATE wp_posts SET post_content = '', post_title = '';
```

**Comment by MZwillus** [comment]
No I don't, but I'd like to ask you to remove this link from this issue as soon as you don't need this zip anymore, so that it's not publicly accessable.
[db_dump.zip](https://github.com/GM-Alex/user-access-manager/files/963791/db_dump.zip)

Thank you for your help

**Comment by GM-Alex** [comment]
Done. I will have a look this weekend.

**Comment by MZwillus** [comment]
I don't know it it's relevant, but we are using Microsoft IIS as web server and MySQL as database.

We are using an **Active Directory integration plugin** which will assign users groups created with the **User Role Editor** based on their groups in our Active Directory network.

The groups are based on our companys departments.

User Access Manager is the last but most important step for this workflow. Which will take the custom groups and restrict their access if necessary.

**Comment by MZwillus** [comment]
I think I've found the bottleneck. It's another plugin.
Anyway the loading time still increases by 2 to 3 seconds as soon as the User Access Manager is activated.

**Comment by MZwillus** [comment]
This fixes #53 for me :+1:

Changes made in `src\UserAccessManager\Controller\FrontendController.php` on line 126

For my server, there needs to be a slash in front of the assets folder.
```
        $urlPath = $this->config->getUrlPath();

        $this->wordpress->registerStyle(
            self::HANDLE_STYLE_LOGIN_FORM,
            $urlPath.'/assets/css/uamLoginForm.css',
            [],
            UserAccessManager::VERSION,
            'screen'
        );
```
Does this happen to Apache as well? Can't test it at work unfortunately.

**Comment by GM-Alex** [comment]
This affected the performance?

**Comment by MZwillus** [comment]
At least that's what the Chrome Inspector says. And I do feel an improvement.

**Comment by GM-Alex** [comment]
Ok chrome tries to load the file which he can't find. That makes the difference but what make no sense to me is the following. The function `getUrlPath` looks like the following:

```php
public function getUrlPath()
{
    return $this->wordpress->pluginsUrl('', $this->baseFile).DIRECTORY_SEPARATOR;
}
```

So could you please have a look as what `DIRECTORY_SEPARATOR` is defined? Maybe that is an issue related to IIS.

**Comment by GM-Alex** [comment]
Ah it's my issue windows uses `\` instead of `/`and I mixed urls with paths, because on unix the are both using `/`...

**Comment by MZwillus** [comment]
Sorry, I won't be able to check earlier than Monday. I'm not in the office anymore.
