### ISSUE TITLE
After last update 2.0.6 i had backend and frontend as blank page

### ISSUE THREAD

**Issue by webprom** [GM-Alex/user-access-manager#54]
After disabling plugin from ftp by changing its name, then enabling it. still errors. 
Then deleted it and installed again. But still can't activate, error in plugins upon activation:

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected T_FUNCTION in /xxx/xxx/public_html/wp-content/plugins/user-access-manager/user-access-manager.php on line 36

what could it be?

thanks.

**Comment by GM-Alex** [comment]
I would say you are using PHP 5.2 or lower. Please don't do it in production. It's not secure anymore.

**Comment by webprom** [comment]
yes, thanks. I will try to upgrade it and will see.
