### ISSUE TITLE
Lock files put the site in jamming out condition

### ISSUE THREAD

**Issue by masimies** [GM-Alex/user-access-manager#56]
First i have to say, that this plugin is what i have waiting for. Simple to manage, and do what it should do with member-sites. Good job!
So far i have managed to cover my main problem with everyone access to all sites articles.
Second is to secure files. But using Lock files, it puts the site to very unusable state. For uploaded files, it works like a charm, but not for images. Media-libray is jamming, and even with super-admin rights, cannot see the images. Images did have options for access groups, but choosing them does nothing more for visibility. The media opening process was extremely slow. Even, if i choose for not lock images, did no improvement. So, the file and image locking goes side by side in practical? Or the .htaccess-file does not updated easily choosing files or images.
I have Multisite-enviroment and memberships are handled with Ultimate Member. I will test this more with less amount of other plugins in test-environment, but if someone have good tips to try here, i will test them also.
For the wishlist. If the access could be somehow sync with common WP-roles. Would it be that there is then no need to create new acces-groups anymore. (I have to manage security now with 3-things. Memeber-login with UM, role access with Member and now category access with UAM)

br,
-matti

**Comment by GM-Alex** [comment]
Hey matti,

thanks for feedback. If I got you right you have identify one problem

https://github.com/GM-Alex/user-access-manager/issues/57

and one feature request

https://github.com/GM-Alex/user-access-manager/issues/58

GitHub is an issue tracker so the issues should be task to be done, that helps me to keep an overview and see what I should do next. I create two new issues from this one. For your questions about alternatives I would like to suggest the Wordpress community threads. And if you want to give some feedback a rating for the plugin would be nice. Don't be hesitate to comment within the new issues or if I forgot something to create a new issue. Thanks.

Regards,
Alex
