### ISSUE TITLE
Sync with common wp-roles

### ISSUE THREAD

**Issue by GM-Alex** [GM-Alex/user-access-manager#58]
Taken from #56
> If the access could be somehow sync with common WP-roles. Would it be that there is then no need to create new acces-groups anymore.

**Comment by GM-Alex** [comment]
@masimies I'm thinking of a dynamic group feature for users, so that there is a virtual group for every user. It think once implemented it could be easily extended to do the same for user groups. But currently you could create an user group for each role and use the role affiliation feature. Did you already known about that feature?

**Comment by masimies** [comment]
Yes, i have added roles also to groups. But just thinking that how to decrease different funtions for security. I'm developing site, what is used from frontend, with minimal need of administration. It would be greate if membersite-plugin developers starts to see your point how the access should be handled.
As there is needs to cover more than only menus,widgets and pages. These days WP is coming more and more out from backend.

**Comment by GM-Alex** [comment]
I will close this one due #64
