### ISSUE TITLE
category widget but a problem

### ISSUE THREAD

**Issue by Kminowa** [GM-Alex/user-access-manager#59]
I upgraded to "User Access Manager 2.0.6", but a problem occurred.
The tree display is not displayed correctly in the category widget, and it is displayed in strange order.
It will be displayed normally when User Access Manager 2.0.1 or earlier or User Access Manager is disabled.

·Confirmation method
1. Create multiple categories
2. Change some categories to a tree
3. Confirm display by Category Widget

"User Access Manager 2.0.6"にアップグレートしたところ、問題が発生しました。
カテゴリーウィジットでツリー表示が正しく表示されず、不思議な順番で表示されます。
User Access Manager 2.0.1以前や、User Access Managerを無効にした時は正常に表示されます。

・確認方法
1.複数のカテゴリーを作成
2.カテゴリーをいくつか、ツリーへ変更
3.カテゴリーウィジットで表示確認

**Comment by GM-Alex** [comment]
The release will took some days. If it's urgent you can use the version from here: https://github.com/GM-Alex/user-access-manager/archive/master.zip

**Comment by Kminowa** [comment]
Thank you very much!.
I confirmed normal operation!!.
