### ISSUE TITLE
Allow html as no access content

### ISSUE THREAD

**Issue by GM-Alex** [GM-Alex/user-access-manager#63]
Allow html as no access content to give the user more freedom to design theses messages.

**Comment by Garconis** [comment]
Yeah, what happened to this? Prior to V2, this worked. Now it causes improper escaping of HTML. E.g., 

<h2 class=\\\"fancy-heading-1 blue\\\">Sorry</h2> <h4>You need to be a <a href=\\\"/pit-crew/\\\"><strong>Pit Crew</strong></a> member to view this page.</h4> <br><br> Please <a href=\\\"/login/\\\" class=\\\"upper\\\">login</a> or <a href=\\\"/register/\\\" class=\\\"upper\\\">register</a>.
