### ISSUE TITLE
Dynamic user groups

### ISSUE THREAD

**Issue by GM-Alex** [GM-Alex/user-access-manager#64]
There should be dynamic user groups for the following use cases:

- Users
- Roles
- Not logged in users

These user groups have set the `read access` and `write access` set always to `only group members` and aren't listed at the user group overview. Because there could be many user groups like that the should be assigned similar to the wp tag feature, by a search field an auto suggestion.

**Comment by EYBTM** [comment]
This is an awesome plugin, will it be possible somehow to assign a person to a group by a questionnaire / quiz or something like this? if not do you take paid jobs? If so would be really happy to contact you by mail

elad@volcano-s.com 

thanks!
