### ISSUE TITLE
Updated to V2.0.6 flattened the wordpress menu hierarchy

### ISSUE THREAD

**Issue by geipan** [GM-Alex/user-access-manager#67]
I just updated the UAM. I ran into some errors and finally managed to update it by deactivating the plugin first. Updating the plugin and updating the database was then successful but as soon as UAM is activated my formerly cascaded menu is flat ![igzh uam activated](https://cloud.githubusercontent.com/assets/28387579/25698423/1ae6b0ca-30bf-11e7-800a-5fcfed84e163.png). I deactivate UAM and it is cascaded again ![igzh uam deactivated](https://cloud.githubusercontent.com/assets/28387579/25698429/1daae150-30bf-11e7-9c30-7275c6cbdcdc.png). 

Do you have any suggestions how to solve this? I really like the plugin and don't want to replace it.

**Comment by masimies** [comment]
Interesting, because i do not have any effect to my menu. My menu access is controlled only by membership-plugin. UAM is handling page-access within membership-access tabs. Working together just fine. Maybe theme issue.

**Comment by GM-Alex** [comment]
Ard these elements categories?

**Comment by geipan** [comment]
Yes they are. Most of them.

**Comment by GM-Alex** [comment]
Okay, so please see #59 you can download the version mentioned in the issue. Please report back if this fix it.

**Comment by geipan** [comment]
This one fixed the problem. Thank you very much for your speedy answer!
