### ISSUE TITLE
Broken RSS feeds

### ISSUE THREAD

**Issue by andybennett1985** [GM-Alex/user-access-manager#68]
We have found since upgrading to version 2.0.0 and subsequent releases, RSS feeds (specifically for post categories) from our WordPress site have failed. We use RSS feeds to deliver content to various pages around our site and is an essential element.

We have found the only way to produce an RSS feeds is to manually disable UAM. We have implemented various fixes such as removing any white space at the head of RSS feeds, but still encounter the same problem.

If you require copies of code to examine please let me know. Any assistance you can provide would be great as we really need get this working once again.

Thank you

**Comment by masimies** [comment]
Hi, for info,
I use WP RSS Aggregator to produce RSS-feeds, and this plugin is fully compatible with UAM.
You can see the results here:
https://feedly.com/i/subscription/feed/https://teamsin.net/feed/

**Comment by andybennett1985** [comment]
Sorry I probably wasn't clear - the RSS feeds from WordPress are used to create content for other pages External to WordPress. We have a process which takes the RSS feed and populates another page using the raw data.

UAM appears to prevent the post information from being populated within the RSS feed. When UAM is enabled we see the following output:

```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>DU news story 1 &#8211; News</title>
	<atom:link href="" rel="self" type="application/rss+xml" />
	<link>https://link-to-our-site.com/</link>
	<description>Web News</description>
	<lastBuildDate>Mon, 20 Mar 2017 16:25:59 +0000</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.7.4</generator>
</channel>
</rss>
```

When UAM is disabled this feed is populated with post data.

Thanks

**Comment by GM-Alex** [comment]
The RSS feed works like expected. If you hide post completely the are also hidden in the feed, otherwise you would be able to access the protected content by the RSS feeds, which would corrupt the protection. If you don't want to protected the feed disable it at the settings, but refresh your cache after you changed the settings.

**Comment by GM-Alex** [comment]
Reopen because of https://wordpress.org/support/topic/rss-feed-broken-30/#post-9106646
