### ISSUE TITLE
Auto assign people who are not registered to a specific group

### ISSUE THREAD

**Issue by Razow** [GM-Alex/user-access-manager#69]
Hi, first of all lovely plugin.
I would like to know if you do modifications to the plugins (not for free of course).
If so, I would like to make an auto assignment of people who are not registered to a specific group that will see specific content.

Is it possible?

Best regards!

**Comment by GM-Alex** [comment]
Already planned with https://github.com/GM-Alex/user-access-manager/issues/64 ;)

**Comment by Razow** [comment]
Wow, awesome!!!
so when will this be implemented?

**Comment by GM-Alex** [comment]
I can't give any exact eta, depends strongly on my free time and how much other features are included in 2.1.0. Maybe one month, but could be sooner or later.
