### ISSUE TITLE
Twenty Seventeen: Restricted Pages Still Appears as Sections

### ISSUE THREAD

**Issue by leocalbusch** [GM-Alex/user-access-manager#70]
Hi, I´m setting access to certain pages to certain user groups. It hides pages and menu items like a charm. However, the pages still appears at front page sections of Twenty Seventeen.

**Comment by GM-Alex** [comment]
Is the front page section a widget or like I think the main page? Cause it seems to work for me like it should.

**Comment by leocalbusch** [comment]
Main page... see here: http://calbusch.com.br/plazagaudi/principal thats the main page. Section 1: teste. try access http://calbusch.com.br/plazagaudi/principal/teste (the actual page), there you will find the page is restricted. But at the main page the content is shown anyway. Maybe my scenario is interfering? The plugin is installed at multisite and network activated.

**Comment by GM-Alex** [comment]
If you don't choose to hide the post completely they are listed where they should appear without a restriction. Just choose hide post completely and they should be hidden.

**Comment by leocalbusch** [comment]
Sorry for using this issues board like a support thread, but apparently I´m doig everything right... the options "Hide complete Posts" and "Hide complete Pages" are set to yes, the Access of the page is set to the user group I created, and I´m trying to access the page without logging in. If I try to access the restricted page directly, the plugin do its job, but through the main page where the restricted page is set to the section of the theme, it is shown normally. Am I doing something wrong? It seems like the theme ignores the plugin and shows the restricted page at the sections of the main page anyway.

**Comment by GM-Alex** [comment]
Could you please try the version from here: https://github.com/GM-Alex/user-access-manager/archive/user-access-manager-70.zip

**Comment by GM-Alex** [comment]
@leocalbusch Any feedback?
