### ISSUE TITLE
Performance issue with 2.x on my Pagely hosted sites

### ISSUE THREAD

**Issue by starnesd** [GM-Alex/user-access-manager#71]
UAM is contributing over 50% of the response time for pages on 2 of my sites hosted by Pagely. They are running WP 4.7.3 and PHP7. See below what Newrelic is reporting related to your plugin. I upgraded this morning to 2.0.8 from 2.0.6 and it dropped the response time of getVisibleElementsCount from 30+s to 15+s, hideObject from almost 3s to 600ms, hidePostType from 5+s to 600+ms. So the changes from 2.06 to 2.08 did make a difference to my sites. However 15s per page is really slow. Can you look into this issue please? Let me know what you need to investigate. The two sites i have experiencing issues are www.artistdaily.com and www.digitalbookworld.com.

Category	Slowest components	Count	Duration	%
Custom	UserAccessManager\Controller\FrontendController::getVisibleElementsCount	49	15,700 ms	53%
Custom	UserAccessManager\AccessHandler\AccessHandler::checkObjectAccess	323	1,040 ms	4%
Custom	wpdb::query	6	877 ms	3%
Custom	apply_filters	122	790 ms	3%
Custom	UserAccessManager\Config\Config::hideObject	31	646 ms	2%
Custom	UserAccessManager\Config\Config::hidePostType	48	610 ms	2%
Remainder	Remainder	1	9,750 ms	33%
Total time			29,400 ms	100%
URL	/2012/e-book-subscription-service-oyster-gets-3-million-in-funding-wants-to-be-spotify-for-books/

**Comment by starnesd** [comment]
_I've received some input from pagely I'm passing on here._

Looking at that stat from New Relic:

UserAccessManager\Controller\FrontendController::getVisibleElementsCount     Count:135   Duration: 32,200 ms     %:62
The function it's calling is in:

./wp-content/plugins/user-access-manager/src/UserAccessManager/Controller/FrontendController.php
Line 533 & on:

    /**
     * Returns the post count for the term.
     *
     * @param string $termType
     * @param int    $termId
     *
     * @return int
     */
    private function getVisibleElementsCount($termType, $termId)
    {
        $count = 0;

        $fullTerms = [$termId => $termType];
        $termTreeMap = $this->objectHandler->getTermTreeMap();

        if (isset($termTreeMap[ObjectHandler::TREE_MAP_CHILDREN][$termType]) === true
            && isset($termTreeMap[ObjectHandler::TREE_MAP_CHILDREN][$termType][$termId]) === true
        ) {
            $fullTerms += $termTreeMap[ObjectHandler::TREE_MAP_CHILDREN][$termType][$termId];
        }

        $posts = [];
        $termPostMap = $this->objectHandler->getTermPostMap();

        foreach ($fullTerms as $fullTermId => $fullTermType) {
            if (isset($termPostMap[$fullTermId]) === true) {
                $posts += $termPostMap[$fullTermId];
            }
        }

        foreach ($posts as $postId => $postType) {
            if ($this->config->hidePostType($postType) === false
                || $this->accessHandler->checkObjectAccess(ObjectHandler::GENERAL_POST_OBJECT_TYPE, $postId) === true
            ) {
                $count++;
            }
        }

        return $count;
    }
If that's simply returning a count & spending so much time doing it, I could imaging adding a patch to have that utilize WordPress native transient api @ https://codex.wordpress.org/Transients_API so it doesn't have to do the php work every-time the function is called, but only when it doesn't already exist in the transient object store.

Sudo-code, using the example on the WordPress page, it would be something like:

Added comments where the other snippets of getVisibleElementsCount function code should be coded in.
<?php
// Get any existing copy of our transient data
if ( false === ( $uam_return_count = get_transient( 'uam_return_count_' . $termId . $termType ) ) ) {
    // It wasn't there, so regenerate the data and save the transient

    // Do all the code that's already in the getVisibleElementsCount function

    // Set the transient to be used next time, before the return of $count
    set_transient( 'uam_return_count', $count, 12 * HOUR_IN_SECONDS );
    // Return the $count, just as if it were regularily returned by the function
    return $count;

}
^ Just free-handed it & didn't test it out for syntax, but there's some boilerplate which could be customized for the use-case of getting that call that takes ~62% of the page-loading time to get stored in object cache, so php doesn't have to do the work every single time its' called.

-Oscar G.

Check the FAQ at https://support.pagely.com for Answers to commonly asked questions.

**Comment by starnesd** [comment]
sorry, this got cut off.

// Get any existing copy of our transient data
if ( false === ( $uam_return_count = get_transient( 'uam_return_count_' . $termId . $termType ) ) ) {
    // It wasn't there, so regenerate the data and save the transient

    // Do all the code that's already in the getVisibleElementsCount function

    // Set the transient to be used next time, before the return of $count
    set_transient( 'uam_return_count', $count, 12 * HOUR_IN_SECONDS );
    // Return the $count, just as if it were regularily returned by the function
    return $count;

}
^ Just free-handed it & didn't test it out for syntax, but there's some boilerplate which could be customized for the use-case of getting that call that takes ~62% of the page-loading time to get stored in object cache, so php doesn't have to do the work every single time its' called.

-Oscar G.

Check the FAQ at https://support.pagely.com for Answers to commonly asked questions.

**Comment by GM-Alex** [comment]
Hey I don't think it's `getVisibleElementsCount` but `getTermTreeMap` or `getTermPostMap`. The best would be if you could provide me a dump of your database, because currently I haven't a "heavy" database for optimisation testing.

**Comment by starnesd** [comment]
I could clone the artistdaily.com site and provide you access. I'm not
comfortable sending a db off to someone else.



Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
I fully understand that but that's the best way to improve the code. I would also happy if you truncate all user data and invalidate the post/category contents by update the contents with empty strings using mysql (maybe keep the titles for readability at the backend :) ). I'm only interested at the number of post/pages/categories and their dependencies.

**Comment by starnesd** [comment]
let me see if i can clean up the data.

Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
That would be awesome.

**Comment by starnesd** [comment]
you can access the MYSQL DUMP at ​
 dev.artistdaily.com.sql.gz
<https://drive.google.com/a/fwmedia.com/file/d/0B2T8q9fWDZohR1RtZnMwZkQ0ZGs/view?usp=drive_web>
​

Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by starnesd** [comment]
Any status/update?

**Comment by GM-Alex** [comment]
Not now sorry. I think I will get my hands on tomorrow evening (UTC+2).

**Comment by starnesd** [comment]
I have 12 sites getting 502/503 errors because of the plugin. it's
impacting my business. Please look into this as soon as you can.

Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
I understand it's important for you but please see I have a 40h week (by contract reality looks different as usually) two kids and doing this in my free time. So I'm can't give you 24/7 support like a company could do it.

**Comment by starnesd** [comment]
I just noticed that i sent you the DB before 1.4 upgrade. I did the 1.4 upgrade before my site went live on php7/wp 4.7.4

**Comment by GM-Alex** [comment]
This should not be an issue.

**Comment by GM-Alex** [comment]
What I can say for now that I will not solve this tomorrow, so my suggestion would be to downgrade to 1.2.4. Use the revert function of uam 2.0.0 and higher and download the old version (which if I got you right worked) and replace the current one. This gives me some time to optimize the plugin. But your database is a really good database for optimization. I have a delivery time around 10 seconds at my test environment (all other plugins are disabled).

**Comment by starnesd** [comment]
actually we implemented the suggestion of pagely and cached the count in
transient storage and it has made a world of difference. instead of over
30s home page we have 2s home page.



Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
The sugesstion of pagely corrupt the access logic. If an admin access the page before a guest there is a chance that everyone gets access. It's NOT only a count!

**Comment by starnesd** [comment]
Ok, we only have one admin. we'll not cache it for admins.

Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
It's the same problem for user assigned to the UAM group (fill access to the content - "admin") vs users not in the group.

**Comment by starnesd** [comment]
we used the cache key with the addition of role so we cache admin,
subscriber, editor, guest all separately


Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
I your roles maps to you groups it should be fine. 100% safe is it if you use the user groups.


```php
$keys = array_keys($this->accessHandler->getUserGroupsForUser());
asort($keys);
$userGroupsKey = implode('|', $keys);
```

**Comment by starnesd** [comment]
we only use a single group in our site and all registered users are in that
group.

Darrell Starnes
Enterprise Operations
C: 970-692-9780 *(new number)*
Skype: darrell.starnes

**Comment by GM-Alex** [comment]
Hey,

I have good and bad news, the good one is I did a rough prototype which needs around one second for delivery. The bad is that needs now be implemented in a clean way, which I would estimate to be finished in around one week (but no promises made maybe more maybe less). I will put it on the top of the todo list.

**Comment by starnesd** [comment]
Thanks. My work around is keeping us afloat. I look forward to the
permanent fix.


Darrell Starnes
Enterprise Operations
c: 970-692-9780

**Comment by GM-Alex** [comment]
Short status update, the run time is now at around 450 ms for the homepage once cached (all other plugins disabled expect uam and Wordpress default theme, using PHP 7.0 with opcache) and the implementation itself is done. What needs to be done is the backend configuration and adjusting the unittests.

**Comment by starnesd** [comment]
That's great news.



Darrell Starnes
Enterprise Operations
c: 970-692-9780

**Comment by GM-Alex** [comment]
I will close this one due #75. I will release a beta version of the cache functionality which should be fully usable (but not "polished"),  because I plan to release it final with 2.1.0 but the other features will be took more time.
