### ISSUE TITLE
404 Redirection not working

### ISSUE THREAD

**Issue by boasthesnake** [GM-Alex/user-access-manager#72]
On my page I set to redirect users with no access to the login page. Tried to set to whatever page, custom URL etc. These settings are ignores, still 404 appears

**Comment by GM-Alex** [comment]
Is the content set to hide completely at the settings?

**Comment by boasthesnake** [comment]
Yes, all content is set to be hidden

**Comment by GM-Alex** [comment]
Than it's the normal behavior. The content is completely hidden. :) Otherwise user would be able to brut force the post titles etc.
