### ISSUE TITLE
Error on install (Windows)

### ISSUE THREAD

**Issue by NBley** [GM-Alex/user-access-manager#73]
Hello, I want to update automatically the plugin UAM. This has unfortunately failed. Then I uploaded the plugin via FTp and wanted to activate it. The following error then appears:

Fatal error: Uncaught Error: Class 'UserAccessManager \ Wrapper \ Php' not found in /.../.../.../wp-content/plugins/user-access-manager/init.php:23 Stack trace: # 0 /.../.../../wp-content/plugins/user-access-manager/user-access-manager.php(68): initUserAccessManger () # 1 / ... / ... /wp-admin/includes/plugin.php(1882): include ('/ ... / ... / ...') # 2 /.../.../.../wp-admin/ Plugin.php (164): plugin_sandbox_scrape ('user-access-man ...') # 3 {main} thrown in /.../.../.../wp-content/plugins/user-access- Manager / init.php on line 23

What could be the problem? The plugin is very good and I would like to use it again.
Thank you
greetings
Nick

**Comment by GM-Alex** [comment]
Hey Nick,

könntest du hier bitte Englisch schreiben damit andere User ebenfalls etwas vom Ticket haben falls sie den gleichen Fehler haben? Danke. (Ich werde dann die Antwort auch dem entsprechen anpassen). Es sieht mir aus als wäre das Plugin nicht vollständig hochgeladen worden. Ggf. verwendest du auch Windows, kann das sein?

**Comment by GM-Alex** [comment]
Do you have some php experience? Currently I have no windows PC to test it, but I would give you some hints that we could debug it together.

**Comment by GM-Alex** [comment]
Ok got some contact with other windows user and it works for them. I think it's a permission problem. Make all files readable. I will close that for now. If you need more help don't hesitated to write again.
