### ISSUE TITLE
Feature request: Deny wp-admin contents if user is logged out

### ISSUE THREAD

**Issue by PeopleInside** [GM-Alex/user-access-manager#77]
Hi,
I REALLY LOVE this plugin.

IF you create a page who need to be restricted to the only admin only you can use this plugin and the amazing things is that this plugin also deny access to the page if you are logged out.
In WordPress once you are logged out you are able to see everything you visit before by using the back browser button ... I think this is very bad, WordPress should do what you are doing on a protected page.

If I edit a protected page restricted to the only administrator (thanks to your plugin) and after I logout I AM able to go back and see private dashboards also go back on edit public page (I cannot edit but I can read everything) but IF I try to go back to a protected only admin page is requested to log-in.

I want ask if you can implement that for all logged area: when an user logout from Word§Press should not be able to press back button and see dashboard and all pages visited in the logged area if you are not logged.

I really want to implement this also to WordPress.. When user log out should not be able to see previous pages of the logged area.

Do you think you can implement a function that help to keep all reserved area not visible with the back button when user or admin has been logged out? User should see again log-in page as your plugin do with restricts pages.

**Comment by GM-Alex** [comment]
This one is related to your browser cache, sorry I can't do anything. The dashboard doesn't have any http request which requires a reauthentication so the dashboard is fully cached by your browser, even Wordpress can do anything.

**Comment by PeopleInside** [comment]
OK thanks for the feedback. I still not understand why some application with login when you logout you are unable to go back with the browser and with Wordpress you can do. It's not very nice :P Thanks again.
