### ISSUE TITLE
Security gap between UAM and Flowpaper

### ISSUE THREAD

**Issue by KELogeHH** [GM-Alex/user-access-manager#78]
Hello,

I use WordPress 4.7.4 and the User Access Manager 2.0.8, short UAM, (https://wordpress.org/plugins/user-access-manager/) in connection with the plugin FlowPaper 1.8.4 (https: // wordpress.org/plugins/flowpaper-lite-pdf-flipbook/).

My page is freely visible to everyone (http://innerer-orient.de/test).
The PDF document only for a user role.

I would have expected the page to be displayed, but it would have to give an error message, due to the user role, when loading the document.

This is not the case, the document is loaded and displayed completely.
Is this a bug of one of the plugins?
I am not sure if I can ask for help, therefore, the question in the round here.
As a beginner, I would first suspect the UAM, which does not hand over the role correctly.
Maybe someone can help me, because I think that is a security problem.

Many Thanks

**Comment by masimies** [comment]
Hi, lookup #57 
If you have asked google to index your pages, it will crawl all your files as well and show direct links to them.
With my case, i cannot use file locks until new update, due the heavy load issue. But in common, file lock protect the files as exepted, and redirects visitor to homepage instead of opening file.

**Comment by KELogeHH** [comment]
Hello,

Thank you for the information. It's not about Google. The problem is that I can use the FlowPaper plugin to display the file even though a user role has been set.
Other Plugins e.g. PDFjs Viewer (Source: https://de.wordpress.org/plugins/pdfjs-viewer-shortcode/) create an error with the same setting as Flowpaper.

Example: FlowPaper: http://innerer-orient.de/test.html

Example: PDFjs Viewer: http://innerer-orient.de/test1.html

The behavior of PDFjs Viewer is also expected. The plugin determines that the PDF to be displayed has a user role that a guest does not have. It can not be displayed at all.

On the other hand, Flowpaper shows that it can not be right and poses a risk.
