### ISSUE TITLE
Unable to un-select access groups on a page

### ISSUE THREAD

**Issue by snoek8** [GM-Alex/user-access-manager#81]
I am unable to un-select an access group on a page because the checkbox of the selected group is inactive.

**Comment by GM-Alex** [comment]
Please see https://github.com/GM-Alex/user-access-manager/issues/74

**Comment by snoek8** [comment]
I don't think #74 is the same issue. I was able to save it fine. But now I cannot un-select a group.

**Comment by GM-Alex** [comment]
Is there a [LR]?

**Comment by snoek8** [comment]
yes

**Comment by GM-Alex** [comment]
This means it's locked recursive by an other element, hover the group and it will show you by which element.

**Comment by snoek8** [comment]
I think then the issue may be related to the fact that the site is multilanguage. Please see this image. This is a single post I wanted to change permission on so there is no recursion.
![screenhunter_247 may 15 16 52](https://cloud.githubusercontent.com/assets/448871/26081123/0aed5830-398f-11e7-9e14-6d920a668cb1.jpg)

**Comment by GM-Alex** [comment]
Yes there is its locked by post_translation object, what ever that is.

**Comment by snoek8** [comment]
Ok. Thanks. That means that the multilanguage plugin the site uses is causing the access module to use the wrong element.

**Comment by GM-Alex** [comment]
Sorry I can't say anything about that, I don't know the plugin, but it could be possible.

**Comment by snoek8** [comment]
For now I think I can work around it by turning off recursive. Thank you.
