### ISSUE TITLE
Only admins can change access ?

### ISSUE THREAD

**Issue by keeslina** [GM-Alex/user-access-manager#83]
Hi, 

At the moment , only users with 'administrator rights' , can link a post/page/product to a user group. 
For all other user levels, the settings doesn't show up in the edit post sidebar.

I have a specific user which has the role ' Shop manager' (Woocommerce). I want to also give this person the ability to link posts/pages/products to a user group.  Can you tell me if this is possible and how I can manage to do this? 

Thanks!

Kees

**Comment by GM-Alex** [comment]
For user questions please use https://wordpress.org/support/plugin/user-access-manager
