### ISSUE TITLE
IP Range required bug - undefined offset?

### ISSUE THREAD

**Issue by Kwapi** [GM-Alex/user-access-manager#87]
Hi, I'm trying to test your plug-in but I'm getting multiple `undefined offset` bugs for unauthenticated users. I tried providing random IP Range and also leaving that field empty - the same errors pop up.

Here's the stack:

`Notice: Undefined offset: 1 in /Users/michal/Projects/keepplus/wp-content/plugins/user-access-manager/src/UserAccessManager/AccessHandler/AccessHandler.php on line 262
1.	0.0039	366136	{main}( )	.../index.php:0
2.	0.0293	368776	require( '/Users/michal/Projects/keepplus/wp-blog-header.php' )	.../index.php:17
3.	0.6507	24827280	wp( ??? )	.../wp-blog-header.php:16
4.	0.6507	24827328	WP->main( ??? )	.../functions.php:955
5.	0.6565	24887120	WP->query_posts( )	.../class-wp.php:735
6.	0.6565	24887120	WP_Query->query( ??? )	.../class-wp.php:617
7.	0.6565	24952656	WP_Query->get_posts( )	.../class-wp-query.php:3238
8.	0.6595	24959112	apply_filters_ref_array( ???, ??? )	.../class-wp-query.php:2522
9.	0.6595	24959112	WP_Hook->apply_filters( ???, ??? )	.../plugin.php:244
10.	0.6596	24960616	UserAccessManager\Controller\FrontendController->showPostSql( ??? )	.../class-wp-hook.php:300
11.	0.6596	24960616	UserAccessManager\AccessHandler\AccessHandler->getExcludedPosts( )	.../FrontendController.php:449
12.	0.6636	25057056	UserAccessManager\AccessHandler\AccessHandler->getUserGroupsForUser( )	.../AccessHandler.php:512
13.	0.6651	25061072	UserAccessManager\AccessHandler\AccessHandler->isIpInRange( ???, ??? )	.../AccessHandler.php:318
14.	0.6651	25061448	UserAccessManager\AccessHandler\AccessHandler->calculateIp( ??? )	.../AccessHandler.php:276
`

**Comment by GM-Alex** [comment]
Seems your `$_SERVER["REMOTE_ADDR"]` returns IPV6 instead of IPV4 can you confirm that?

**Comment by GM-Alex** [comment]
Due no response within one week I will close this issue. If you have more information please don't hesitated to write again and I will reopen the issue.
