### ISSUE TITLE
preview images not showing

### ISSUE THREAD

**Issue by numerosept** [GM-Alex/user-access-manager#88]
Hey after plugin updates, the featured images of my restricted posts are not showing on my homepage slider. Before last update everything was working well, now i got an error 400 on the images (failed to load ressources...). when logged in as user the images display without any problems.

I believe they are also protected ?

Do you have a clue ? 

website is : http://beaute-info.ch

**Comment by GM-Alex** [comment]
Seems the urls are invalid: 

Not working (missing image name http://beaute-info.ch/wp-content/uploads/2017/02/HERE&...)

```
http://beaute-info.ch/wp-content/themes/goodnews/framework/scripts/timthumb.php?src=http://beaute-info.ch/wp-content/uploads/2017/02/&h=340&w=615&zc=1
```

vs working (with image 'Demi-couv-BI88-FR.jpg' http://beaute-info.ch/wp-content/uploads/2016/04/Demi-couv-BI88-FR.jpg&...)

```
http://beaute-info.ch/wp-content/themes/goodnews/framework/scripts/timthumb.php?src=http://beaute-info.ch/wp-content/uploads/2016/04/Demi-couv-BI88-FR.jpg&h=340&w=615&zc=1
```

At the first look it doesn't seems it's a uam problem.

**Comment by GM-Alex** [comment]
Due no response within one week I will close this issue. If you have more information please don't hesitated to write again and I will reopen the issue.
