### ISSUE TITLE
Login on restricted page

### ISSUE THREAD

**Issue by luzamartinez** [GM-Alex/user-access-manager#89]
Hi!!

There is a way that when the user enters to the restricted page, the site shows the login and display the page unlocked once logged in?

Thank you.

**Comment by petewarrior** [comment]
According to the feature list, this feature exists, but there's no option for it in the Settings.

**Comment by GM-Alex** [comment]
Use the login form tag `[LOGIN_FORM]` for the restricted content. The content type must not be hidden and redirect must turned of that the form is shown.
