### ISSUE TITLE
getTerm uses wp get_term - could it use get_term_by

### ISSUE THREAD

**Issue by nwoetzel** [GM-Alex/user-access-manager#9]
https://github.com/GM-Alex/user-access-manager/blob/master/class/UserAccessManager.php#L201
I was wondering, if the code
<pre>
            $iPriority = has_filter('get_term', array($this, 'showTerm'));
            $blRemoveSuccess = remove_filter('get_term', array($this, 'showTerm'), $iPriority);

            $this->_aTerms[$sId] = get_term($sId, $sTaxonomy);

            if ($blRemoveSuccess === true) {
                add_filter('get_term', array($this, 'showTerm'), $iPriority, 2);
            }
</pre>
by replacing it with
<pre>
            $this->_aTerms[$sId] = get_term_by('ID',$sId, $sTaxonomy);
</pre>
[get_term_by](https://codex.wordpress.org/Function_Reference/get_term_by) does not apply filters, so there would be no need to remove the filter, and add it back. Except for the case, where it relies and all other filters to be applied?!
If this is the case, I would suggest to document it in the code, if it is not the case, using get_term_by would be the simpler implementation.

**Comment by GM-Alex** [comment]
Good hint, but maybe it's not necessary after the refactoring. I will have a look if I start optimizing the code.

**Comment by nwoetzel** [comment]
I do not exactly know what your plans are for the refactoring. So it is absolutely OK with me if you concentrate on refactoring! I just want to make sure these things get your attention and are considered in one way or the other.
Thanks again for the work.

**Comment by GM-Alex** [comment]
First step is to split everything to smaller classes, add a abstraction layer for the wordpress functions and add dependency injection. If you have a look at the next branch you will see how it will look like. Than the next step will be unit tests and performance improvements. Also to structure it a little bit more logical.

**Comment by GM-Alex** [comment]
The code isn't necessary anymore. The next version will be much faster.
