### ISSUE TITLE
File block and images

### ISSUE THREAD

**Issue by dlalla83** [GM-Alex/user-access-manager#91]
Once I activate the file block all my images are not available anymore. If I try to reach them with direct link I get a 404. Pdf files have no problem. I tried also to choose the types which will not be locked but it doesn't seems to work. If I disable the file block everything works fine. I'm pretty sure that I'm doing something wrong.
Thanks in advance.

**Comment by gjmenten** [comment]
Did you find a solution? I have a similar problem in that the thumbnails for the featured images of the blocked pages do not show up anywhere on the website.

**Comment by masimies** [comment]
Hi,
Checkout this:
https://wordpress.org/support/topic/medias-locked/#post-9268700

**Comment by GM-Alex** [comment]
Please use the latest version and set `Locked directory type` to `Wordpress`, see [https://github.com/GM-Alex/user-access-manager/wiki/Settings-%7C-File-settings](https://github.com/GM-Alex/user-access-manager/wiki/Settings-%7C-File-settings)
