### ISSUE TITLE
Can no longer use HTML in 'no access' text

### ISSUE THREAD

**Issue by ImOnMars** [GM-Alex/user-access-manager#93]
I used to have HTML in my page no access content so that when they had no access to the page there would be HTML header text + a login form allowing them to sign in.

Now, it's impossible to add working HTML to the content. See WordPress forum support thread [here](https://wordpress.org/support/topic/cannot-add-html-since-last-update/) for more info.

**Comment by ImOnMars** [comment]
I don't understand how this is an enhancement. It's something that used to work and no longer works, it's a bug.

**Comment by GM-Alex** [comment]
No this doesn't work since 2.0.0 because I decided to remove it. So now some users requesting it and I changed my mind. => enhancement

**Comment by GM-Alex** [comment]
duplicates #63
