### ISSUE TITLE
Access only to assigned user group + post author

### ISSUE THREAD

**Issue by nicksss93** [GM-Alex/user-access-manager#95]
Hi,

Thank you for taking the time to develop this plugin - it's really useful. I've installed it on my website and I want to make it work like this - restrict acess to a certain type of posts so that they would be available only for specific user groups and the author of the post himself. However, I can't find a way to allow access for the post author to his post and when it gets assigned to a specific user group, he loses access to it.

Is there a way in which I could add the post author to always have access to his posts?

Thanks!

**Comment by ImOnMars** [comment]
While I'm not sure if the option actually works, on the Settings page for UAM, under "Author Settings" (near the bottom), there is an option titled "Authors always has access to own posts/pages", click Yes.

Again, not sure if this works (or work in the way it sounds).

**Comment by nicksss93** [comment]
Hi, was just about to edit my question. Yes, I found it in the settings menu and it's set to Yes, but it doesn't work, unfortunately.

**Comment by GM-Alex** [comment]
Yes the feature is exactly for that, but it seems broken. I will fix it with the next version.

**Comment by nicksss93** [comment]
OK. Will be waiting for it then. Can you tell me when do you expect to release the next update?

Thanks.

**Comment by Garconis** [comment]
+1. The most recent update says it fixed it, but the author still doesn't have access to their own page...

**Comment by GM-Alex** [comment]
@Garconis Tested it again, works like expected. Did you set `Authors always has access to own posts/pages` to `Yes`?

**Comment by Garconis** [comment]
@GM-Alex, yes I did. :(

**Comment by GM-Alex** [comment]
@Garconis That doesn't come from the User Access Manager. The plugin doesn't provide such a functionality to hide menu entries at the backend completely. Could you try disable uam and see if the page entry comes back, if not an other plugin is the culprit. If yes it seems like a plugin conflict. Then please disable all other plugins expect uam and see if the page entry is still there, which should be the case. Than activate all the other plugins step by step so see which causes the conflict.

**Comment by nicksss93** [comment]
Works fine with me with the new update. Thanks for releasing it promptly!

**Comment by GM-Alex** [comment]
@nicksss93 Thanks for feedback.

**Comment by Garconis** [comment]
This is strange. I deactivated all plugins and even put theme back to 2017, and that user still doesn't have access to that page. Maybe because I set them to the Author, AFTER the page was already published by someone else. Ugh. Oh well. Time to go down a rabbit hole.
