### ISSUE TITLE
Uploading files on secured posts the file is anyway available and indexed by search engines (using a previous version of user-access-manager)

### ISSUE THREAD

**Issue by pupunzi** [GM-Alex/user-access-manager#96]
Hi,
We are using version 1.2.5 of user-access-manager and we're experiencing a bug when we upload a file on a secured post. The link to the media element post from the front-end is secured and it asks for the log-in to get the file but if we point directly to the file we can download it.

Has this behaviour been fixed with the latest release of user-access-manager?

We're not updating the plug-in because the last time we tried some of the documents lost the security; but if that issue is solved we'll try again.

All the best,
Matteo

**Comment by pupunzi** [comment]
Any answer?...

**Comment by GM-Alex** [comment]
I don't know anyone else having the issue you described, also the support for versions lower than 2.0 has discontinued (so I will close this issue for now). Maybe your htaccess file is missing. Best would be to try the update in a testing environment.

**Comment by pupunzi** [comment]
@GM-Alex Thank you Alex, your hint give us the solution; the .htaccess in the upload folder was missing ;-) 

All the best,
Matteo

**Comment by GM-Alex** [comment]
Great, I'm happy that it works now.

**Comment by masimies** [comment]
@pupunzi , i'm curious. You are using file lock? and you don't have any load problems with all images in media library?

br,

-matti

**Comment by pupunzi** [comment]
@masimies No, any problem with images on media library

**Comment by GM-Alex** [comment]
@pupunzi Can I close this issue?
