### ISSUE TITLE
Warning in AccessHandler.php with PHP 7.1.4

### ISSUE THREAD

**Issue by m3rlin7** [GM-Alex/user-access-manager#97]
Hello,
i tried to upgrade on of my projects to PHP 7.1.x and get the following error in Backend > Pages:
`Warning: A non-numeric value encountered in C:\xampp\htdocs\wordpress\wp-content\plugins\user-access-manager\src\UserAccessManager\AccessHandler\AccessHandler.php on line 262`

The two pages with restriction won't appear at all. It seems that for every page missing creates one warning. 
I reproduced the error with a clean wordpress installation (v7.4.5), created a second user (editor), two user groups, two pages - each assigned to one group. After login with the second user, i get the error as described. The admin user gets no error at all.

In my productive site the problem also appears on the home page and the dashboard.

Any idea on how to fix this?
What is the latest PHP-Version supported?

Regards
Maik

**Comment by GM-Alex** [comment]
Seems related to #87. Could you please check if you are using IPv6?

**Comment by m3rlin7** [comment]
Xampp/PHP says that my $_SERVER["REMOTE_ADDR"] is IPv6. I tried http://127.0.0.1/ instead if http://localhost/ and now it is working. Seems that localhost is resolved with IPv6. 
Problem is solved, thx for the help.

Has the plugin successfuly been tested with PHP 7.0 or 7.1 yet? PHP Errors are gone, but things don't work like intended.

**Comment by GM-Alex** [comment]
My test environment is based on PHP 7.0 and works like it should. PHP also shouldn't make any difference.
